/** Compact country list (ISO alpha-2, dial code, EN/AR names). Oman + GCC first. */
export const countries: { code: string; dial: string; en: string; ar: string }[] = [
  { code: "OM", dial: "968", en: "Oman", ar: "عُمان" },
  { code: "AE", dial: "971", en: "United Arab Emirates", ar: "الإمارات" },
  { code: "SA", dial: "966", en: "Saudi Arabia", ar: "السعودية" },
  { code: "QA", dial: "974", en: "Qatar", ar: "قطر" },
  { code: "KW", dial: "965", en: "Kuwait", ar: "الكويت" },
  { code: "BH", dial: "973", en: "Bahrain", ar: "البحرين" },
  { code: "GB", dial: "44", en: "United Kingdom", ar: "المملكة المتحدة" },
  { code: "US", dial: "1", en: "United States", ar: "الولايات المتحدة" },
  { code: "DE", dial: "49", en: "Germany", ar: "ألمانيا" },
  { code: "FR", dial: "33", en: "France", ar: "فرنسا" },
  { code: "IT", dial: "39", en: "Italy", ar: "إيطاليا" },
  { code: "ES", dial: "34", en: "Spain", ar: "إسبانيا" },
  { code: "NL", dial: "31", en: "Netherlands", ar: "هولندا" },
  { code: "CH", dial: "41", en: "Switzerland", ar: "سويسرا" },
  { code: "AT", dial: "43", en: "Austria", ar: "النمسا" },
  { code: "BE", dial: "32", en: "Belgium", ar: "بلجيكا" },
  { code: "SE", dial: "46", en: "Sweden", ar: "السويد" },
  { code: "NO", dial: "47", en: "Norway", ar: "النرويج" },
  { code: "DK", dial: "45", en: "Denmark", ar: "الدنمارك" },
  { code: "FI", dial: "358", en: "Finland", ar: "فنلندا" },
  { code: "PL", dial: "48", en: "Poland", ar: "بولندا" },
  { code: "CZ", dial: "420", en: "Czechia", ar: "التشيك" },
  { code: "PT", dial: "351", en: "Portugal", ar: "البرتغال" },
  { code: "IE", dial: "353", en: "Ireland", ar: "أيرلندا" },
  { code: "GR", dial: "30", en: "Greece", ar: "اليونان" },
  { code: "TR", dial: "90", en: "Türkiye", ar: "تركيا" },
  { code: "RU", dial: "7", en: "Russia", ar: "روسيا" },
  { code: "UA", dial: "380", en: "Ukraine", ar: "أوكرانيا" },
  { code: "CA", dial: "1", en: "Canada", ar: "كندا" },
  { code: "MX", dial: "52", en: "Mexico", ar: "المكسيك" },
  { code: "BR", dial: "55", en: "Brazil", ar: "البرازيل" },
  { code: "AR", dial: "54", en: "Argentina", ar: "الأرجنتين" },
  { code: "AU", dial: "61", en: "Australia", ar: "أستراليا" },
  { code: "NZ", dial: "64", en: "New Zealand", ar: "نيوزيلندا" },
  { code: "IN", dial: "91", en: "India", ar: "الهند" },
  { code: "PK", dial: "92", en: "Pakistan", ar: "باكستان" },
  { code: "BD", dial: "880", en: "Bangladesh", ar: "بنغلاديش" },
  { code: "LK", dial: "94", en: "Sri Lanka", ar: "سريلانكا" },
  { code: "CN", dial: "86", en: "China", ar: "الصين" },
  { code: "JP", dial: "81", en: "Japan", ar: "اليابان" },
  { code: "KR", dial: "82", en: "South Korea", ar: "كوريا الجنوبية" },
  { code: "SG", dial: "65", en: "Singapore", ar: "سنغافورة" },
  { code: "MY", dial: "60", en: "Malaysia", ar: "ماليزيا" },
  { code: "TH", dial: "66", en: "Thailand", ar: "تايلاند" },
  { code: "ID", dial: "62", en: "Indonesia", ar: "إندونيسيا" },
  { code: "PH", dial: "63", en: "Philippines", ar: "الفلبين" },
  { code: "EG", dial: "20", en: "Egypt", ar: "مصر" },
  { code: "JO", dial: "962", en: "Jordan", ar: "الأردن" },
  { code: "LB", dial: "961", en: "Lebanon", ar: "لبنان" },
  { code: "IQ", dial: "964", en: "Iraq", ar: "العراق" },
  { code: "MA", dial: "212", en: "Morocco", ar: "المغرب" },
  { code: "TN", dial: "216", en: "Tunisia", ar: "تونس" },
  { code: "DZ", dial: "213", en: "Algeria", ar: "الجزائر" },
  { code: "ZA", dial: "27", en: "South Africa", ar: "جنوب أفريقيا" },
  { code: "KE", dial: "254", en: "Kenya", ar: "كينيا" },
  { code: "NG", dial: "234", en: "Nigeria", ar: "نيجيريا" },
  { code: "IR", dial: "98", en: "Iran", ar: "إيران" },
  { code: "IL", dial: "972", en: "Israel", ar: "إسرائيل" },
  { code: "HU", dial: "36", en: "Hungary", ar: "المجر" },
  { code: "RO", dial: "40", en: "Romania", ar: "رومانيا" },
];

export const countryName = (code: string, locale: string) => {
  const c = countries.find((x) => x.code === code);
  return c ? (locale === "ar" ? c.ar : c.en) : code;
};
