export const categoriesSeed = [
  { key: "city_tours", icon: "Landmark", name: { en: "City Tours", ar: "جولات المدينة" }, slug: { en: "city-tours", ar: "جولات-المدينة" }, description: { en: "Discover Muscat's mosques, souqs and coastline with a local guide.", ar: "اكتشف مساجد مسقط وأسواقها وساحلها برفقة مرشد محلي." } },
  { key: "day_trips", icon: "Sun", name: { en: "Day Trips", ar: "رحلات يومية" }, slug: { en: "day-trips", ar: "رحلات-يومية" }, description: { en: "Full-day private excursions from Muscat.", ar: "رحلات خاصة ليوم كامل انطلاقًا من مسقط." } },
  { key: "multi_day", icon: "Map", name: { en: "Multi-day Packages", ar: "باقات متعددة الأيام" }, slug: { en: "multi-day-packages", ar: "باقات-متعددة-الأيام" }, description: { en: "Two to eight-day journeys across the Sultanate.", ar: "رحلات من يومين إلى ثمانية أيام عبر السلطنة." } },
  { key: "desert_4x4", icon: "Mountain", name: { en: "Desert & 4x4 Adventures", ar: "مغامرات الصحراء والدفع الرباعي" }, slug: { en: "desert-4x4-adventures", ar: "مغامرات-الصحراء" }, description: { en: "Dune bashing, Bedouin camps and starlit nights in Wahiba Sands.", ar: "تسلّق الكثبان ومخيمات البدو وليالٍ مرصّعة بالنجوم في رمال وهيبة." } },
  { key: "mountain_wadi", icon: "Waves", name: { en: "Mountain & Wadi Adventures", ar: "مغامرات الجبال والأودية" }, slug: { en: "mountain-wadi-adventures", ar: "مغامرات-الجبال-والأودية" }, description: { en: "Emerald pools, canyon hikes and Jebel Akhdar terraces.", ar: "برك زمردية، مسارات في الأخاديد، ومدرجات الجبل الأخضر." } },
  { key: "cultural", icon: "Castle", name: { en: "Cultural & Heritage", ar: "ثقافة وتراث" }, slug: { en: "cultural-heritage", ar: "ثقافة-وتراث" }, description: { en: "Forts, castles, souqs and UNESCO heritage.", ar: "قلاع وحصون وأسواق ومواقع تراث اليونسكو." } },
  { key: "food_family", icon: "UtensilsCrossed", name: { en: "Food & Family Dinner Experiences", ar: "تجارب الطعام والعشاء العائلي" }, slug: { en: "food-family-dinner", ar: "الطعام-والعشاء-العائلي" }, description: { en: "Share shuwa, halwa and kahwa with an Omani family.", ar: "شارك الشواء والحلوى والقهوة مع عائلة عُمانية." } },
  { key: "boat", icon: "Ship", name: { en: "Boat, Dolphin Watching & Snorkeling", ar: "رحلات بحرية ومشاهدة الدلافين والغطس" }, slug: { en: "boat-dolphin-snorkeling", ar: "رحلات-بحرية" }, description: { en: "Daymaniyat Islands, dolphins and coral reefs.", ar: "جزر الديمانيات والدلافين والشعاب المرجانية." } },
  { key: "hiking_camping", icon: "Tent", name: { en: "Hiking & Camping", ar: "المشي والتخييم" }, slug: { en: "hiking-camping", ar: "المشي-والتخييم" }, description: { en: "Guided treks and wild camping under Omani skies.", ar: "مسارات مشي بإرشاد وتخييم برّي تحت سماء عُمان." } },
  { key: "photography", icon: "Camera", name: { en: "Photography Tours", ar: "جولات التصوير" }, slug: { en: "photography-tours", ar: "جولات-التصوير" }, description: { en: "Golden-hour routes for photographers.", ar: "مسارات الساعة الذهبية لعشّاق التصوير." } },
  { key: "transfers", icon: "CarFront", name: { en: "Private Transfers & Car with Driver", ar: "نقل خاص وسيارة مع سائق" }, slug: { en: "private-transfers", ar: "نقل-خاص" }, description: { en: "Airport, hotel and inter-city transfers in private 4WDs.", ar: "نقل من المطار والفنادق وبين المدن بسيارات دفع رباعي خاصة." } },
  { key: "custom", icon: "Compass", name: { en: "Custom Itineraries", ar: "برامج مخصّصة" }, slug: { en: "custom-itineraries", ar: "برامج-مخصصة" }, description: { en: "Tell us your dates and interests; we design the rest.", ar: "أخبرنا بمواعيدك واهتماماتك ونحن نصمّم الباقي." } },
] as const;

export type CategoryKey = (typeof categoriesSeed)[number]["key"];
