export const destinationsSeed = [
  {
    key: "muscat",
    name: { en: "Muscat", ar: "مسقط" },
    slug: { en: "muscat", ar: "مسقط" },
    tagline: { en: "Mosques, souqs and a harbour framed by mountains", ar: "مساجد وأسواق وميناء تحيط به الجبال" },
    description: {
      en: "Oman's capital blends the grandeur of the Sultan Qaboos Grand Mosque with the scent of frankincense in Mutrah Souq and the sea breeze along the Corniche.",
      ar: "تجمع عاصمة عُمان بين عظمة جامع السلطان قابوس الأكبر وعبق اللبان في سوق مطرح ونسيم البحر على الكورنيش.",
    },
    region: "Muscat Governorate",
    lat: 23.588,
    lng: 58.3829,
    image: "muscat",
  },
  {
    key: "nizwa",
    name: { en: "Nizwa", ar: "نزوى" },
    slug: { en: "nizwa", ar: "نزوى" },
    tagline: { en: "The ancient capital and its 17th-century fort", ar: "العاصمة القديمة وقلعتها من القرن السابع عشر" },
    description: {
      en: "Home to Oman's most famous fort, a bustling Friday goat market and a souq known for silver khanjars and pottery.",
      ar: "موطن أشهر قلاع عُمان، وسوق الماشية الصاخب يوم الجمعة، وسوق يشتهر بالخناجر الفضية والفخار.",
    },
    region: "Ad Dakhiliyah",
    lat: 22.9333,
    lng: 57.5333,
    image: "nizwa",
  },
  {
    key: "wahiba",
    name: { en: "Wahiba Sands", ar: "رمال وهيبة" },
    slug: { en: "wahiba-sands", ar: "رمال-وهيبة" },
    tagline: { en: "Rolling red dunes and Bedouin hospitality", ar: "كثبان حمراء متموّجة وضيافة بدوية" },
    description: {
      en: "Sharqiya Sands stretch 180 km of shifting dunes where Bedouin families still keep camels and welcome guests with coffee and dates.",
      ar: "تمتد رمال الشرقية على 180 كيلومترًا من الكثبان المتحرّكة حيث لا تزال العائلات البدوية تربّي الإبل وتستقبل الضيوف بالقهوة والتمر.",
    },
    region: "Ash Sharqiyah",
    lat: 22.2,
    lng: 58.8,
    image: "wahiba",
  },
  {
    key: "jebel_akhdar",
    name: { en: "Jebel Akhdar", ar: "الجبل الأخضر" },
    slug: { en: "jebel-akhdar", ar: "الجبل-الأخضر" },
    tagline: { en: "Rose terraces 2,000 m above the sea", ar: "مدرجات الورد على ارتفاع 2000 متر" },
    description: {
      en: "The Green Mountain of the Hajar range is famed for its cool climate, terraced pomegranate and rose gardens, and cliff-edge luxury resorts.",
      ar: "يشتهر الجبل الأخضر في سلسلة الحجر بمناخه المعتدل ومدرجات الرمان والورد ومنتجعاته الفاخرة على حافة الجرف.",
    },
    region: "Ad Dakhiliyah",
    lat: 23.0733,
    lng: 57.6667,
    image: "jebel-akhdar",
  },
  {
    key: "salalah",
    name: { en: "Salalah", ar: "صلالة" },
    slug: { en: "salalah", ar: "صلالة" },
    tagline: { en: "Frankincense coast and monsoon greenery", ar: "ساحل اللبان وخضرة الخريف" },
    description: {
      en: "Dhofar's capital turns emerald during the Khareef monsoon; explore frankincense groves, blowholes and the beaches of Mughsail.",
      ar: "تتحوّل عاصمة ظفار إلى اللون الزمردي خلال موسم الخريف؛ استكشف أشجار اللبان والنوافير البحرية وشواطئ المغسيل.",
    },
    region: "Dhofar",
    lat: 17.0151,
    lng: 54.0924,
    image: "salalah",
  },
  {
    key: "musandam",
    name: { en: "Musandam", ar: "مسندم" },
    slug: { en: "musandam", ar: "مسندم" },
    tagline: { en: "The Norway of Arabia", ar: "نرويج الجزيرة العربية" },
    description: {
      en: "Dramatic fjords, dhow cruises and dolphin pods at the tip of the Arabian Peninsula.",
      ar: "خلجان صخرية مهيبة ورحلات بالسفن التقليدية وأسراب الدلافين في أقصى شبه الجزيرة العربية.",
    },
    region: "Musandam Governorate",
    lat: 26.1935,
    lng: 56.2483,
    image: "musandam",
  },
  {
    key: "sur",
    name: { en: "Sur & Ras Al Jinz", ar: "صور ورأس الجنز" },
    slug: { en: "sur-ras-al-jinz", ar: "صور-ورأس-الجنز" },
    tagline: { en: "Dhow builders and nesting green turtles", ar: "صنّاع السفن التقليدية والسلاحف الخضراء" },
    description: {
      en: "Watch wooden dhows being crafted by hand in Sur, then witness green turtles nesting on the beach at Ras Al Jinz after dark.",
      ar: "شاهد صناعة السفن الخشبية يدويًا في صور، ثم راقب السلاحف الخضراء وهي تضع بيضها على شاطئ رأس الجنز بعد الغروب.",
    },
    region: "Ash Sharqiyah",
    lat: 22.5667,
    lng: 59.5289,
    image: "sur",
  },
  {
    key: "wadi_shab",
    name: { en: "Wadi Shab", ar: "وادي شاب" },
    slug: { en: "wadi-shab", ar: "وادي-شاب" },
    tagline: { en: "Turquoise pools and a hidden waterfall cave", ar: "برك فيروزية وكهف شلال مخفي" },
    description: {
      en: "A short boat crossing, a scenic canyon walk and a swim through a keyhole into a cave waterfall — Oman's most loved wadi.",
      ar: "عبور قصير بالقارب، مسار خلاب في الوادي، وسباحة عبر فتحة ضيقة إلى كهف الشلال؛ الوادي الأكثر شهرة في عُمان.",
    },
    region: "Ash Sharqiyah",
    lat: 22.8388,
    lng: 59.2381,
    image: "wadi-shab",
  },
  {
    key: "jabal_shams",
    name: { en: "Jabal Shams & Al Hamra", ar: "جبل شمس والحمراء" },
    slug: { en: "jabal-shams", ar: "جبل-شمس" },
    tagline: { en: "Oman's Grand Canyon and 400-year-old mud villages", ar: "أخدود عُمان الكبير وقرى الطين العريقة" },
    description: {
      en: "The highest mountain in Oman overlooks Wadi Ghul, the 'Grand Canyon of Arabia'. Nearby lie the terraced village of Misfat Al Abriyeen, the mud houses of Al Hamra and Al Hoota Cave.",
      ar: "يطل أعلى جبال عُمان على وادي غول، «أخدود الجزيرة العربية الكبير». وبالقرب منه قرية مسفاة العبريين المدرّجة وبيوت الطين في الحمراء وكهف الهوتة.",
    },
    region: "Ad Dakhiliyah",
    lat: 23.2372,
    lng: 57.2601,
    image: "jebel-akhdar",
  },
  {
    key: "nakhal",
    name: { en: "Nakhal & Wakan", ar: "نخل ووكان" },
    slug: { en: "nakhal-wakan", ar: "نخل-ووكان" },
    tagline: { en: "A fort on a rock, hot springs and a village of terraces", ar: "قلعة فوق صخرة وعيون حارة وقرية مدرّجة" },
    description: {
      en: "An hour from Muscat, Nakhal Fort rises from a rocky outcrop above date plantations and the Al Thowarah hot spring; higher up, the mountain village of Wakan hangs over Wadi Mistal at 2,000 m.",
      ar: "على بعد ساعة من مسقط، تنهض قلعة نخل فوق نتوء صخري بين مزارع النخيل وعين الثوارة الحارة؛ وفي الأعلى تتعلّق قرية وكان الجبلية فوق وادي مستل على ارتفاع 2000 متر.",
    },
    region: "South Al Batinah",
    lat: 23.395,
    lng: 57.829,
    image: "nizwa",
  },
  {
    key: "daymaniyat",
    name: { en: "Daymaniyat Islands", ar: "جزر الديمانيات" },
    slug: { en: "daymaniyat-islands", ar: "جزر-الديمانيات" },
    tagline: { en: "Turtles, reefs and the clearest water in the Gulf", ar: "سلاحف وشعاب وأصفى مياه الخليج" },
    description: {
      en: "A protected archipelago off the Batinah coast where coral gardens, green turtles and reef fish make for the best snorkelling in Oman.",
      ar: "أرخبيل محمي قبالة ساحل الباطنة، حيث حدائق المرجان والسلاحف الخضراء وأسماك الشعاب تجعل منه أفضل مكان للغطس السطحي في عُمان.",
    },
    region: "Muscat Governorate",
    lat: 23.85,
    lng: 58.1,
    image: "sur",
  },
] as const;

export type DestinationKey = (typeof destinationsSeed)[number]["key"];
