export const destinationsSeed = [
  {
    key: "muscat",
    name: { en: "Muscat", ar: "مسقط" },
    slug: { en: "muscat", ar: "مسقط" },
    tagline: { en: "Mosques, souqs and a harbour framed by mountains", ar: "مساجد وأسواق وميناء تحيط به الجبال" },
    description: {
      en: "Oman's capital blends the grandeur of the Sultan Qaboos Grand Mosque with the scent of frankincense in Mutrah Souq and the sea breeze along the Corniche.",
      ar: "تجمع عاصمة عُمان بين عظمة جامع السلطان قابوس الأكبر وعبق اللبان في سوق مطرح ونسيم البحر على الكورنيش.",
    },
    region: "Muscat Governorate",
    lat: 23.588,
    lng: 58.3829,
    image: "muscat",
  },
  {
    key: "nizwa",
    name: { en: "Nizwa", ar: "نزوى" },
    slug: { en: "nizwa", ar: "نزوى" },
    tagline: { en: "The ancient capital and its 17th-century fort", ar: "العاصمة القديمة وقلعتها من القرن السابع عشر" },
    description: {
      en: "Home to Oman's most famous fort, a bustling Friday goat market and a souq known for silver khanjars and pottery.",
      ar: "موطن أشهر قلاع عُمان، وسوق الماشية الصاخب يوم الجمعة، وسوق يشتهر بالخناجر الفضية والفخار.",
    },
    region: "Ad Dakhiliyah",
    lat: 22.9333,
    lng: 57.5333,
    image: "nizwa",
  },
  {
    key: "wahiba",
    name: { en: "Wahiba Sands", ar: "رمال وهيبة" },
    slug: { en: "wahiba-sands", ar: "رمال-وهيبة" },
    tagline: { en: "Rolling red dunes and Bedouin hospitality", ar: "كثبان حمراء متموّجة وضيافة بدوية" },
    description: {
      en: "Sharqiya Sands stretch 180 km of shifting dunes where Bedouin families still keep camels and welcome guests with coffee and dates.",
      ar: "تمتد رمال الشرقية على 180 كيلومترًا من الكثبان المتحرّكة حيث لا تزال العائلات البدوية تربّي الإبل وتستقبل الضيوف بالقهوة والتمر.",
    },
    region: "Ash Sharqiyah",
    lat: 22.2,
    lng: 58.8,
    image: "wahiba",
  },
  {
    key: "jebel_akhdar",
    name: { en: "Jebel Akhdar", ar: "الجبل الأخضر" },
    slug: { en: "jebel-akhdar", ar: "الجبل-الأخضر" },
    tagline: { en: "Rose terraces 2,000 m above the sea", ar: "مدرجات الورد على ارتفاع 2000 متر" },
    description: {
      en: "The Green Mountain of the Hajar range is famed for its cool climate, terraced pomegranate and rose gardens, and cliff-edge luxury resorts.",
      ar: "يشتهر الجبل الأخضر في سلسلة الحجر بمناخه المعتدل ومدرجات الرمان والورد ومنتجعاته الفاخرة على حافة الجرف.",
    },
    region: "Ad Dakhiliyah",
    lat: 23.0733,
    lng: 57.6667,
    image: "jebel-akhdar",
  },
  {
    key: "salalah",
    name: { en: "Salalah", ar: "صلالة" },
    slug: { en: "salalah", ar: "صلالة" },
    tagline: { en: "Frankincense coast and monsoon greenery", ar: "ساحل اللبان وخضرة الخريف" },
    description: {
      en: "Dhofar's capital turns emerald during the Khareef monsoon; explore frankincense groves, blowholes and the beaches of Mughsail.",
      ar: "تتحوّل عاصمة ظفار إلى اللون الزمردي خلال موسم الخريف؛ استكشف أشجار اللبان والنوافير البحرية وشواطئ المغسيل.",
    },
    region: "Dhofar",
    lat: 17.0151,
    lng: 54.0924,
    image: "salalah",
  },
  {
    key: "musandam",
    name: { en: "Musandam", ar: "مسندم" },
    slug: { en: "musandam", ar: "مسندم" },
    tagline: { en: "The Norway of Arabia", ar: "نرويج الجزيرة العربية" },
    description: {
      en: "Dramatic fjords, dhow cruises and dolphin pods at the tip of the Arabian Peninsula.",
      ar: "خلجان صخرية مهيبة ورحلات بالسفن التقليدية وأسراب الدلافين في أقصى شبه الجزيرة العربية.",
    },
    region: "Musandam Governorate",
    lat: 26.1935,
    lng: 56.2483,
    image: "musandam",
  },
  {
    key: "sur",
    name: { en: "Sur & Ras Al Jinz", ar: "صور ورأس الجنز" },
    slug: { en: "sur-ras-al-jinz", ar: "صور-ورأس-الجنز" },
    tagline: { en: "Dhow builders and nesting green turtles", ar: "صنّاع السفن التقليدية والسلاحف الخضراء" },
    description: {
      en: "Watch wooden dhows being crafted by hand in Sur, then witness green turtles nesting on the beach at Ras Al Jinz after dark.",
      ar: "شاهد صناعة السفن الخشبية يدويًا في صور، ثم راقب السلاحف الخضراء وهي تضع بيضها على شاطئ رأس الجنز بعد الغروب.",
    },
    region: "Ash Sharqiyah",
    lat: 22.5667,
    lng: 59.5289,
    image: "sur",
  },
  {
    key: "wadi_shab",
    name: { en: "Wadi Shab", ar: "وادي شاب" },
    slug: { en: "wadi-shab", ar: "وادي-شاب" },
    tagline: { en: "Turquoise pools and a hidden waterfall cave", ar: "برك فيروزية وكهف شلال مخفي" },
    description: {
      en: "A short boat crossing, a scenic canyon walk and a swim through a keyhole into a cave waterfall — Oman's most loved wadi.",
      ar: "عبور قصير بالقارب، مسار خلاب في الوادي، وسباحة عبر فتحة ضيقة إلى كهف الشلال؛ الوادي الأكثر شهرة في عُمان.",
    },
    region: "Ash Sharqiyah",
    lat: 22.8388,
    lng: 59.2381,
    image: "wadi-shab",
  },
] as const;

export type DestinationKey = (typeof destinationsSeed)[number]["key"];
