import { DAY, airportMuscat, commonExclusions, hotelMuscat, serviceFaqs, times, type TourSeed } from "./tourSeedTypes";

/** Transfers, car rental and tickets (Viator catalogue, September 2026). */
export const services: TourSeed[] = [
  {
    code: "OCT-022",
    viatorCode: "425555P17",
    kind: "service",
    title: { en: "VIP Muscat Airport Transfer – Private Sedan", ar: "نقل VIP من مطار مسقط: سيارة سيدان خاصة" },
    slug: { en: "vip-muscat-airport-transfer", ar: "نقل-مطار-مسقط-في-آي-بي" },
    summary: {
      en: "One-way private transfer between Muscat International Airport and any hotel in Muscat, with a driver holding your name board and flight tracking.",
      ar: "نقل خاص باتجاه واحد بين مطار مسقط الدولي وأي فندق في مسقط، مع سائق يحمل لوحة باسمك ومتابعة لرحلتك الجوية.",
    },
    description: {
      en: "Start or end your trip without queues. For arrivals, your driver waits in the arrivals hall with a name board, helps with your luggage and drives you to your hotel; we track your flight and adjust to delays at no charge. For departures, the car arrives at your hotel 15 minutes before the agreed pickup time. The sedan seats three passengers comfortably with luggage (about 20–30 kg each); larger parties or extra bags travel in a 4WD or minivan, which we quote on request. Book one transfer for each direction.",
      ar: "ابدأ رحلتك أو أنهِها من دون طوابير. عند الوصول ينتظرك السائق في صالة الوصول بلوحة تحمل اسمك، ويساعدك في الأمتعة، ويوصلك إلى فندقك؛ ونتابع رحلتك الجوية ونتكيّف مع التأخير دون رسوم. وعند المغادرة تصل السيارة إلى فندقك قبل 15 دقيقة من موعد الاستلام المتفق عليه. تتسع السيارة السيدان لثلاثة ركاب براحة مع الأمتعة (نحو 20–30 كجم لكل راكب)؛ وتسافر المجموعات الأكبر أو الأمتعة الإضافية في سيارة دفع رباعي أو حافلة صغيرة نسعّرها عند الطلب. احجز نقلًا لكل اتجاه.",
    },
    highlights: [
      { en: "Meet & greet with name board at arrivals", ar: "استقبال بلوحة اسم في صالة الوصول" },
      { en: "Flight tracking and free waiting time", ar: "متابعة الرحلة الجوية ووقت انتظار مجاني" },
      { en: "Comfortable sedan for up to three passengers", ar: "سيارة سيدان مريحة حتى ثلاثة ركاب" },
      { en: "Available 24 hours a day", ar: "متاح على مدار الساعة" },
    ],
    itinerary: [
      { title: { en: "Pickup", ar: "الاستلام" }, body: { en: "Arrivals hall of Muscat International Airport, or your hotel lobby for departures.", ar: "صالة الوصول في مطار مسقط الدولي، أو بهو فندقك عند المغادرة." } },
      { title: { en: "Drive", ar: "الرحلة" }, body: { en: "About 30 minutes to most Muscat hotels.", ar: "نحو 30 دقيقة إلى معظم فنادق مسقط." } },
      { title: { en: "Drop-off", ar: "التوصيل" }, body: { en: "At your hotel reception or the departures kerb.", ar: "عند استقبال الفندق أو رصيف المغادرة." } },
    ],
    inclusions: [
      { en: "Private sedan with fuel and professional driver", ar: "سيارة سيدان خاصة مع الوقود وسائق محترف" },
      { en: "Name board at arrivals and 60 minutes free waiting", ar: "لوحة اسم في صالة الوصول و60 دقيقة انتظار مجاني" },
      { en: "Bottled water", ar: "مياه معبأة" },
    ],
    exclusions: [{ en: "Supplement of about OMR 6 for hotels outside the city centre (Shangri-La, Jumeirah Muscat Bay)", ar: "رسم إضافي نحو 6 ر.ع. للفنادق خارج وسط المدينة (شانغريلا، جميرا خليج مسقط)" }, ...commonExclusions],
    faqs: serviceFaqs({
      question: { en: "What if my flight is delayed?", ar: "ماذا لو تأخرت رحلتي الجوية؟" },
      answer: { en: "Give us your flight number when booking; we track it and your driver adjusts automatically at no extra cost.", ar: "زوّدنا برقم رحلتك عند الحجز؛ نتابعها ويتكيّف سائقك تلقائيًا دون تكلفة إضافية." },
    }),
    category: "transfers",
    destinations: ["muscat"],
    durationLabel: { en: "30–45 minutes", ar: "30–45 دقيقة" },
    durationMinutes: 40,
    durationDays: 1,
    startTimes: times("00:00", "23:00", 60),
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 3,
    capacityPerSlot: 3,
    pricingModel: "per_group",
    priceGroupOmr: 14,
    usdReference: 35,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "muscat",
    isFeatured: false,
    tags: ["transfer", "airport", "sedan"],
    meetingPoint: airportMuscat,
  },
  {
    code: "OCT-005",
    viatorCode: "425555P16",
    kind: "service",
    title: { en: "Transfer: Muscat Airport ⇄ Jabal Akhdar (Alila, Anantara hotels)", ar: "نقل: مطار مسقط ⇄ الجبل الأخضر (فنادق أليلا وأنانتارا)" },
    slug: { en: "transfer-muscat-airport-jabal-akhdar", ar: "نقل-مطار-مسقط-الجبل-الأخضر" },
    summary: {
      en: "Door-to-door private 4WD transfer between Muscat International Airport (or any Muscat hotel) and the Jabal Akhdar resorts, with viewpoint stops on request.",
      ar: "نقل خاص من الباب إلى الباب بسيارة دفع رباعي بين مطار مسقط الدولي (أو أي فندق في مسقط) ومنتجعات الجبل الأخضر، مع توقفات عند الإطلالات عند الطلب.",
    },
    description: {
      en: "The road to Jabal Akhdar is one of the most scenic in Oman, and it is closed to anything but 4WD vehicles. Our professional Omani drivers meet you in the arrivals hall with a name board, help with luggage and drive you in a modern, air-conditioned 4WD to the Alila Jabal Akhdar, Anantara Al Jabal Al Akhdar, Sahab, dusitD2 Naseem or any other mountain resort, with stops at viewpoints along the way if you wish. Flight tracking means we adjust to delays at no extra charge. The price is per vehicle for up to four passengers with luggage; larger groups travel in a second vehicle or minibus.",
      ar: "الطريق إلى الجبل الأخضر من أجمل الطرق في عُمان، وهو مغلق أمام أي مركبة غير الدفع الرباعي. يستقبلك سائقونا العُمانيون المحترفون في صالة الوصول بلوحة تحمل اسمك، ويساعدونك في الأمتعة، وينقلونك بسيارة دفع رباعي حديثة ومكيّفة إلى أليلا الجبل الأخضر أو أنانتارا الجبل الأخضر أو سحاب أو دوسيت دي2 نسيم أو أي منتجع جبلي آخر، مع توقفات عند الإطلالات في الطريق إن رغبت. نتابع حالة الرحلة الجوية ونتكيّف مع التأخيرات دون رسوم إضافية. السعر لكل مركبة حتى أربعة ركاب مع الأمتعة؛ وتسافر المجموعات الأكبر في مركبة ثانية أو حافلة صغيرة.",
    },
    highlights: [
      { en: "Meet & greet at arrivals with name board", ar: "استقبال في صالة الوصول بلوحة اسم" },
      { en: "Modern private 4WD, up to 4 passengers", ar: "سيارة دفع رباعي خاصة حديثة تتسع لأربعة ركاب" },
      { en: "Flight tracking and free waiting time", ar: "متابعة الرحلة الجوية ووقت انتظار مجاني" },
      { en: "Scenic stops at Birkat Al Mouz and the viewpoints on request", ar: "توقفات خلابة في بركة الموز والإطلالات عند الطلب" },
    ],
    itinerary: [
      { title: { en: "Pickup", ar: "الاستلام" }, body: { en: "Airport arrivals hall or your Muscat hotel lobby.", ar: "صالة الوصول في المطار أو بهو فندقك في مسقط." } },
      { title: { en: "Drive", ar: "الرحلة" }, body: { en: "About 2 h 30 via the Nizwa road and the Jabal Akhdar checkpoint; comfort stops on request.", ar: "نحو ساعتين ونصف عبر طريق نزوى ونقطة تفتيش الجبل الأخضر؛ توقفات للراحة عند الطلب." } },
      { title: { en: "Drop-off", ar: "التوصيل" }, body: { en: "At your resort reception.", ar: "عند استقبال المنتجع." } },
    ],
    inclusions: [
      { en: "Private 4WD vehicle with professional Omani driver", ar: "سيارة دفع رباعي خاصة مع سائق عُماني محترف" },
      { en: "Fuel, tolls and parking", ar: "الوقود والرسوم ومواقف السيارات" },
      { en: "Bottled water", ar: "مياه معبأة" },
      { en: "60 minutes free waiting at the airport", ar: "60 دقيقة انتظار مجاني في المطار" },
    ],
    exclusions: [{ en: "Sightseeing stops longer than 20 minutes (bookable as a tour)", ar: "توقفات سياحية تتجاوز 20 دقيقة (يمكن حجزها كجولة)" }, ...commonExclusions],
    faqs: serviceFaqs({
      question: { en: "Can you do the return transfer too?", ar: "هل يمكنكم تنفيذ رحلة العودة أيضًا؟" },
      answer: { en: "Yes. Book two one-way transfers or ask us for a round-trip quote; we can also add a Nizwa stop on the way down.", ar: "نعم. احجز رحلتين باتجاه واحد أو اطلب عرض سعر ذهابًا وإيابًا؛ ويمكننا أيضًا إضافة توقف في نزوى في طريق النزول." },
    }),
    category: "transfers",
    destinations: ["muscat", "jebel_akhdar"],
    durationLabel: { en: "2–3 hours", ar: "2–3 ساعات" },
    durationMinutes: 150,
    durationDays: 1,
    startTimes: times("06:00", "20:00", 120),
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 4,
    capacityPerSlot: 4,
    pricingModel: "per_group",
    priceGroupOmr: 115,
    usdReference: 300,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "jebel-akhdar",
    isFeatured: false,
    tags: ["transfer", "airport", "4x4"],
    meetingPoint: airportMuscat,
  },
  {
    code: "OCT-023",
    viatorCode: "425555P28",
    kind: "service",
    title: { en: "Private Transfer from Dubai or Abu Dhabi to Muscat", ar: "نقل خاص من دبي أو أبوظبي إلى مسقط" },
    slug: { en: "private-transfer-uae-to-muscat", ar: "نقل-خاص-من-الإمارات-إلى-مسقط" },
    summary: {
      en: "Premium door-to-door transfer from anywhere in the UAE to Muscat in a luxury sedan or 4WD with a private driver; add a Nizwa tour on the way for groups.",
      ar: "نقل فاخر من الباب إلى الباب من أي مكان في الإمارات إلى مسقط بسيارة سيدان فاخرة أو دفع رباعي مع سائق خاص؛ ويمكن للمجموعات إضافة جولة في نزوى في الطريق.",
    },
    description: {
      en: "We specialise in premium private transfers from Dubai, Abu Dhabi and the northern Emirates to the Sultanate of Oman. Your driver collects you from your hotel, home or airport, handles the Hatta or Al Ain border formalities with you and continues to Muscat — about five hours from Dubai, longer from Abu Dhabi — with comfort stops along the way. Choose a luxury sedan for up to three passengers or a 4WD for four with extra luggage. Groups can combine the transfer with a stop in Nizwa for the souq and fort before reaching Muscat. Price is per vehicle, one way; visa fees and border charges are paid by the traveller.",
      ar: "نتخصّص في النقل الخاص الفاخر من دبي وأبوظبي والإمارات الشمالية إلى سلطنة عُمان. يستقبلك سائقك من فندقك أو منزلك أو المطار، ويرافقك في إجراءات منفذ حتا أو العين الحدودي، ويواصل إلى مسقط؛ نحو خمس ساعات من دبي وأطول من أبوظبي، مع توقفات للراحة في الطريق. اختر سيدان فاخرة حتى ثلاثة ركاب أو دفعًا رباعيًا لأربعة مع أمتعة إضافية. ويمكن للمجموعات دمج النقل مع توقف في نزوى لزيارة السوق والقلعة قبل الوصول إلى مسقط. السعر لكل مركبة باتجاه واحد؛ ورسوم التأشيرة والمنفذ يدفعها المسافر.",
    },
    highlights: [
      { en: "Pickup anywhere in Dubai, Abu Dhabi or the northern Emirates", ar: "الاستلام من أي مكان في دبي أو أبوظبي أو الإمارات الشمالية" },
      { en: "Luxury sedan or 4WD with a private driver", ar: "سيدان فاخرة أو دفع رباعي مع سائق خاص" },
      { en: "Assistance with border formalities", ar: "مساعدة في إجراءات المنفذ الحدودي" },
      { en: "Optional Nizwa souq and fort stop for groups", ar: "توقف اختياري في سوق نزوى وقلعتها للمجموعات" },
      { en: "Wheelchair-friendly vehicles on request", ar: "مركبات مناسبة للكراسي المتحركة عند الطلب" },
    ],
    itinerary: [
      { title: { en: "Pickup in the UAE", ar: "الاستلام في الإمارات" }, body: { en: "Hotel, residence or airport at the time you choose.", ar: "الفندق أو المنزل أو المطار في الوقت الذي تختاره." } },
      { title: { en: "Border crossing", ar: "عبور الحدود" }, body: { en: "Hatta–Al Wajajah or Al Ain–Buraimi; your driver guides you through exit and entry.", ar: "حتا–الوجاجة أو العين–البريمي؛ يرشدك سائقك في إجراءات الخروج والدخول." } },
      { title: { en: "Drive to Muscat", ar: "الطريق إلى مسقط" }, body: { en: "5–7 hours with comfort stops (optional Nizwa tour); drop-off at your Muscat hotel or the airport.", ar: "5–7 ساعات مع توقفات للراحة (جولة نزوى اختيارية)؛ التوصيل إلى فندقك في مسقط أو المطار." } },
    ],
    inclusions: [
      { en: "Private sedan or 4WD with fuel", ar: "سيدان خاصة أو دفع رباعي مع الوقود" },
      { en: "Professional private driver", ar: "سائق خاص محترف" },
      { en: "Water during the transfer", ar: "مياه خلال الرحلة" },
    ],
    exclusions: [{ en: "Oman visa, UAE exit fee and border charges", ar: "تأشيرة عُمان ورسوم الخروج من الإمارات ورسوم المنفذ" }, { en: "Nizwa tour entrance fees and meals", ar: "رسوم دخول جولة نزوى والوجبات" }, ...commonExclusions],
    faqs: serviceFaqs({
      question: { en: "Do I need a visa for Oman?", ar: "هل أحتاج إلى تأشيرة لدخول عُمان؟" },
      answer: { en: "Most nationalities can apply online at evisa.rop.gov.om before travel; GCC residents with eligible professions may obtain a visa at the border. We confirm the requirements for your passport when you book.", ar: "يمكن لمعظم الجنسيات التقديم إلكترونيًا عبر evisa.rop.gov.om قبل السفر؛ وقد يحصل المقيمون في دول الخليج من أصحاب المهن المؤهلة على تأشيرة عند المنفذ. نؤكد لك المتطلبات الخاصة بجواز سفرك عند الحجز." },
    }),
    category: "transfers",
    destinations: ["muscat"],
    durationLabel: { en: "5–12 hours", ar: "5–12 ساعة" },
    durationMinutes: 420,
    durationDays: 1,
    startTimes: times("04:00", "20:00", 120),
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 4,
    capacityPerSlot: 4,
    pricingModel: "per_group",
    priceGroupOmr: 150,
    priceIsPlaceholder: true,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "muscat",
    isFeatured: false,
    tags: ["transfer", "uae", "dubai", "abu-dhabi"],
    meetingPoint: { label: { en: "Your address in the UAE", ar: "عنوانك في الإمارات" } },
  },
  {
    code: "OCT-024",
    viatorCode: "425555P18",
    kind: "service",
    title: { en: "Self-Drive 4WD Rental in Muscat – Rooftop Tent Option (5 days)", ar: "تأجير دفع رباعي بقيادة ذاتية في مسقط مع خيمة سقف اختيارية (5 أيام)" },
    slug: { en: "self-drive-4wd-rental-muscat", ar: "تأجير-دفع-رباعي-قيادة-ذاتية" },
    summary: {
      en: "A Mitsubishi Pajero or similar 4WD delivered to your hotel or the airport for five days, with optional rooftop tent and camping kit for independent explorers.",
      ar: "سيارة ميتسوبيشي باجيرو أو دفع رباعي مماثل تُسلَّم إلى فندقك أو المطار لخمسة أيام، مع خيمة سقف ومعدات تخييم اختيارية للمستكشفين المستقلين.",
    },
    description: {
      en: "Explore Oman at your own pace. We deliver a well-maintained 4WD to your hotel or to Muscat International Airport, brief you on the routes, the mountain roads and the desert tracks, and collect the car again at the end. For travellers who want to sleep under the stars we fit a rooftop tent with mattresses and bedding and add a camping kit with chairs, table, stove, cool box and lights. The standard rental is five days; longer periods are available at a daily rate, and our team is on the phone throughout your trip for route advice. A valid driving licence (international licence recommended) and a credit card for the deposit are required.",
      ar: "استكشف عُمان بوتيرتك الخاصة. نسلّمك سيارة دفع رباعي مصانة جيدًا في فندقك أو في مطار مسقط الدولي، ونطلعك على الطرق والمسارات الجبلية والدروب الصحراوية، ثم نستلم السيارة في النهاية. وللمسافرين الراغبين في النوم تحت النجوم نركّب خيمة سقف مع فرشات وأغطية ونضيف عدّة تخييم من كراسٍ وطاولة وموقد وصندوق تبريد وإضاءة. مدة التأجير القياسية خمسة أيام؛ وتتوفر مدد أطول بسعر يومي، وفريقنا على الهاتف طوال رحلتك للنصح بالمسارات. يلزم رخصة قيادة سارية (يُنصح برخصة دولية) وبطاقة ائتمان للتأمين.",
    },
    highlights: [
      { en: "Mitsubishi Pajero or similar 4WD, delivered and collected", ar: "ميتسوبيشي باجيرو أو دفع رباعي مماثل، تسليم واستلام" },
      { en: "Optional rooftop tent and full camping kit", ar: "خيمة سقف وعدّة تخييم كاملة اختياريتان" },
      { en: "Route briefing and phone support throughout", ar: "إحاطة بالمسارات ودعم هاتفي طوال الرحلة" },
      { en: "Unlimited mileage within Oman", ar: "مسافة غير محدودة داخل عُمان" },
    ],
    itinerary: [
      { title: { en: "Delivery", ar: "التسليم" }, body: { en: "At your hotel or the airport at the agreed time, with a walk-through of the car and gear.", ar: "في فندقك أو المطار في الوقت المتفق عليه، مع شرح للسيارة والمعدات." } },
      { title: { en: "Your journey", ar: "رحلتك" }, body: { en: "Five days of self-drive; we suggest itineraries for coast, desert and mountains.", ar: "خمسة أيام قيادة ذاتية؛ ونقترح مسارات للساحل والصحراء والجبال." } },
      { title: { en: "Return", ar: "الإرجاع" }, body: { en: "We collect the car at your hotel or the airport.", ar: "نستلم السيارة من فندقك أو المطار." } },
    ],
    inclusions: [
      { en: "4WD Pajero or similar with comprehensive insurance", ar: "سيارة باجيرو أو مماثلة مع تأمين شامل" },
      { en: "Delivery to and collection from any location in Muscat", ar: "التسليم والاستلام في أي موقع في مسقط" },
      { en: "Route briefing and 24/7 phone support", ar: "إحاطة بالمسارات ودعم هاتفي على مدار الساعة" },
    ],
    exclusions: [{ en: "Fuel and the refundable security deposit", ar: "الوقود ومبلغ التأمين القابل للاسترداد" }, { en: "Rooftop tent and camping kit (supplement, on request)", ar: "خيمة السقف وعدّة التخييم (رسم إضافي عند الطلب)" }, ...commonExclusions],
    faqs: serviceFaqs({
      question: { en: "Can I take the car into the desert or up Jabal Akhdar?", ar: "هل يمكنني أخذ السيارة إلى الصحراء أو صعود الجبل الأخضر؟" },
      answer: { en: "Yes, that is what the 4WD is for. We show you how to deflate tyres for sand and recommend the graded routes; recovery in the dunes is at the driver's expense, so we suggest joining a local guide for deep desert driving.", ar: "نعم، هذا هو الغرض من الدفع الرباعي. نعلّمك كيفية تخفيف ضغط الإطارات للرمال ونوصي بالطرق المدرّجة؛ وسحب السيارة من الكثبان يكون على نفقة السائق، لذا نقترح مرافقة مرشد محلي للقيادة في عمق الصحراء." },
    }),
    category: "car_rental",
    secondaryCategories: ["desert_4x4", "hiking_camping"],
    destinations: ["muscat"],
    durationLabel: { en: "5 days (extendable)", ar: "5 أيام (قابلة للتمديد)" },
    durationMinutes: 5 * DAY,
    durationDays: 5,
    startTimes: ["09:00", "12:00", "15:00", "18:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 5,
    capacityPerSlot: 3,
    pricingModel: "per_group",
    priceGroupOmr: 229,
    usdReference: 595,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "hero",
    isFeatured: false,
    tags: ["car-rental", "self-drive", "4x4", "camping"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-025",
    viatorCode: "425555P34",
    kind: "service",
    title: { en: "The National Aquarium Abu Dhabi – Entry Ticket", ar: "الأكواريوم الوطني في أبوظبي: تذكرة دخول" },
    slug: { en: "abu-dhabi-national-aquarium-ticket", ar: "تذكرة-أكواريوم-أبوظبي" },
    summary: {
      en: "Admission to the largest aquarium in the Middle East at Al Qana, Abu Dhabi: ten themed zones, 46,000 animals and an underwater tunnel.",
      ar: "دخول إلى أكبر أكواريوم في الشرق الأوسط في القناة بأبوظبي: عشر مناطق ذات طابع خاص و46 ألف كائن ونفق تحت الماء.",
    },
    description: {
      en: "For guests combining Oman with the UAE, we also sell tickets to The National Aquarium Abu Dhabi at Al Qana. Home to more than 46,000 marine and terrestrial animals across ten immersive zones, it lets you see sharks, rays, tropical fish and reptiles while walking through the impressive underwater tunnel. An indoor attraction suited to families, couples and solo travellers of all ages; wheelchair accessible. Tickets are valid for the date you choose and sent by email.",
      ar: "للضيوف الذين يجمعون بين عُمان والإمارات، نبيع أيضًا تذاكر الأكواريوم الوطني في أبوظبي في القناة. يضم أكثر من 46 ألف كائن بحري وبرّي في عشر مناطق غامرة، ويتيح لك مشاهدة أسماك القرش والشفنين والأسماك الاستوائية والزواحف أثناء المشي عبر النفق المائي المذهل. معلم داخلي يناسب العائلات والأزواج والمسافرين المنفردين من جميع الأعمار؛ ومناسب للكراسي المتحركة. التذاكر صالحة للتاريخ الذي تختاره وتُرسل بالبريد الإلكتروني.",
    },
    highlights: [
      { en: "Ten themed zones and 46,000 animals", ar: "عشر مناطق ذات طابع خاص و46 ألف كائن" },
      { en: "Walk-through underwater tunnel", ar: "نفق مائي للمشي عبره" },
      { en: "Indoor, wheelchair-accessible attraction", ar: "معلم داخلي مناسب للكراسي المتحركة" },
      { en: "E-ticket delivered by email", ar: "تذكرة إلكترونية تُرسل بالبريد" },
    ],
    itinerary: [
      { title: { en: "Visit", ar: "الزيارة" }, body: { en: "Show your e-ticket at the entrance of The National Aquarium, Al Qana, Abu Dhabi; allow about two hours.", ar: "أبرز تذكرتك الإلكترونية عند مدخل الأكواريوم الوطني في القناة بأبوظبي؛ خصّص نحو ساعتين." } },
    ],
    inclusions: [
      { en: "Admission ticket to The National Aquarium Abu Dhabi", ar: "تذكرة دخول الأكواريوم الوطني في أبوظبي" },
      { en: "Access to the main themed zones", ar: "دخول المناطق الرئيسية" },
    ],
    exclusions: [{ en: "Transport to Al Qana", ar: "النقل إلى القناة" }, ...commonExclusions],
    faqs: serviceFaqs(),
    category: "tickets",
    destinations: [],
    durationLabel: { en: "About 2 hours", ar: "نحو ساعتين" },
    durationMinutes: 120,
    durationDays: 1,
    startTimes: ["10:00", "12:00", "14:00", "16:00", "18:00"],
    pickupIncluded: false,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 20,
    capacityPerSlot: 20,
    pricingModel: "per_person",
    priceAdultOmr: 15,
    priceChildOmr: 12,
    childAgeMax: 11,
    priceIsPlaceholder: true,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: false,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 2,
    image: "hero",
    isFeatured: false,
    tags: ["ticket", "abu-dhabi", "family"],
    meetingPoint: { label: { en: "The National Aquarium, Al Qana, Abu Dhabi", ar: "الأكواريوم الوطني، القناة، أبوظبي" }, lat: 24.4148, lng: 54.4948 },
  },
];
