import { DAY, airportMuscat, commonExclusions, hotelMuscat, multiDayFaqs, type TourSeed } from "./tourSeedTypes";

/** Five- to eight-day journeys (Viator catalogue, September 2026). */
export const longJourneys: TourSeed[] = [
  {
    code: "OCT-019",
    viatorCode: "425555P11",
    kind: "tour",
    title: { en: "5-Day Oman Nature & Culture with an Omani Guide – 4WD", ar: "5 أيام في طبيعة عُمان وثقافتها مع مرشد عُماني بالدفع الرباعي" },
    slug: { en: "oman-nature-culture-5-day", ar: "عمان-5-أيام-طبيعة-وثقافة" },
    summary: {
      en: "Airport to airport: Muscat's highlights, Wadi Shab, turtles at Ras Al Jinz, Sur, Wadi Bani Khalid, a Wahiba desert camp, Nizwa and Jabal Akhdar, with four nights in 4-star hotels and camps.",
      ar: "من المطار إلى المطار: معالم مسقط ووادي شاب وسلاحف رأس الجنز وصور ووادي بني خالد ومخيم صحراء وهيبة ونزوى والجبل الأخضر، مع أربع ليالٍ في فنادق أربع نجوم ومخيمات.",
    },
    description: {
      en: "Our most popular complete itinerary, rated 5.0 by every traveller who has taken it. Your guide meets you at Muscat International Airport with a name board and the journey begins with the capital: the Royal Opera House, Mutrah Souq and Qurum Beach. Day two follows the coast to the Bimmah Sinkhole and Wadi Shab, where you hike and swim to the waterfall cave, and ends after dark on the beach at Ras Al Jinz watching green turtles nest. Day three visits the dhow yard in Sur, the pools of Wadi Bani Khalid and the Wahiba Sands, where you sleep at a desert camp under the stars. Day four crosses to Nizwa for its souq and fort and climbs Jabal Akhdar for the terraced villages at 2,000 m before a final night in Muscat. On day five we visit the Sultan Qaboos Grand Mosque, Old Muscat and Bait Al Zubair and drive you to the airport. Four nights, four breakfasts and three dinners, all entrance fees and a private 4WD are included.",
      ar: "برنامجنا الكامل الأكثر شعبية، وقد منحه كل من خاضه تقييم 5.0. يستقبلك مرشدك في مطار مسقط الدولي بلوحة تحمل اسمك، وتبدأ الرحلة بالعاصمة: دار الأوبرا السلطانية وسوق مطرح وشاطئ القرم. يتبع اليوم الثاني الساحل إلى حفرة بمة ووادي شاب حيث تمشي وتسبح إلى كهف الشلال، وينتهي بعد الغروب على شاطئ رأس الجنز لمشاهدة تعشيش السلاحف الخضراء. يزور اليوم الثالث ورشة السفن في صور وبرك وادي بني خالد ورمال وهيبة حيث تنام في مخيم صحراوي تحت النجوم. ويعبر اليوم الرابع إلى نزوى لسوقها وقلعتها ويصعد الجبل الأخضر للقرى المدرّجة على ارتفاع 2000 متر قبل ليلة أخيرة في مسقط. وفي اليوم الخامس نزور جامع السلطان قابوس الأكبر ومسقط القديمة وبيت الزبير ثم نوصلك إلى المطار. يشمل السعر أربع ليالٍ وأربعة إفطارات وثلاثة عشاءات وجميع رسوم الدخول وسيارة دفع رباعي خاصة.",
    },
    highlights: [
      { en: "Airport welcome and Muscat city highlights", ar: "استقبال في المطار ومعالم مسقط" },
      { en: "Wadi Shab waterfall cave and turtles at Ras Al Jinz", ar: "كهف شلال وادي شاب وسلاحف رأس الجنز" },
      { en: "Sur dhow yard, Wadi Bani Khalid and a Wahiba desert camp", ar: "ورشة سفن صور ووادي بني خالد ومخيم في رمال وهيبة" },
      { en: "Nizwa Souq, Nizwa Fort and Jabal Akhdar", ar: "سوق نزوى وقلعة نزوى والجبل الأخضر" },
      { en: "Grand Mosque, Old Muscat and Bait Al Zubair before departure", ar: "الجامع الأكبر ومسقط القديمة وبيت الزبير قبل المغادرة" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Welcome to Oman – Muscat", ar: "أهلًا بك في عُمان – مسقط" }, body: { en: "Airport pickup, Royal Opera House, Mutrah Souq and Qurum Beach. Overnight at a 4-star hotel in Muscat.", ar: "الاستلام من المطار، دار الأوبرا السلطانية، سوق مطرح، شاطئ القرم. المبيت في فندق أربع نجوم في مسقط." } },
      { time: "Day 2", title: { en: "Wadi Shab, Bimmah Sinkhole and Ras Al Jinz", ar: "وادي شاب وحفرة بمة ورأس الجنز" }, body: { en: "Bimmah Sinkhole (40 min), Wadi Shab (3 h), evening turtle watching (2 h). Overnight at Turtle Beach Resort, Sama Ras Al Jinz or similar; breakfast and dinner.", ar: "حفرة بمة (40 دقيقة)، وادي شاب (3 ساعات)، مشاهدة السلاحف مساءً (ساعتان). المبيت في منتجع شاطئ السلاحف أو سما رأس الجنز أو مماثل؛ الإفطار والعشاء." } },
      { time: "Day 3", title: { en: "Sur, Wadi Bani Khalid and the Wahiba Sands", ar: "صور ووادي بني خالد ورمال وهيبة" }, body: { en: "Sur dhow yard (45 min), Wadi Bani Khalid (2 h), Wahiba Sands dune drive and sunset (2 h). Overnight at Sama Al Wasil desert camp or similar; breakfast and dinner.", ar: "ورشة سفن صور (45 دقيقة)، وادي بني خالد (ساعتان)، قيادة على كثبان وهيبة وغروب (ساعتان). المبيت في مخيم سما الواصل أو مماثل؛ الإفطار والعشاء." } },
      { time: "Day 4", title: { en: "Nizwa and Jabal Akhdar", ar: "نزوى والجبل الأخضر" }, body: { en: "Nizwa Souq (1 h), Nizwa Fort (1 h), Jabal Akhdar villages and viewpoints (1 h). Overnight at a 4-star hotel in Muscat; breakfast and dinner.", ar: "سوق نزوى (ساعة)، قلعة نزوى (ساعة)، قرى الجبل الأخضر وإطلالاته (ساعة). المبيت في فندق أربع نجوم في مسقط؛ الإفطار والعشاء." } },
      { time: "Day 5", title: { en: "Muscat and departure", ar: "مسقط والمغادرة" }, body: { en: "Sultan Qaboos Grand Mosque (1 h), Old Muscat (30 min), Bait Al Zubair (1 h), airport transfer; breakfast.", ar: "جامع السلطان قابوس الأكبر (ساعة)، مسقط القديمة (30 دقيقة)، بيت الزبير (ساعة)، التوصيل إلى المطار؛ الإفطار." } },
    ],
    inclusions: [
      { en: "Official English-speaking Omani guide throughout", ar: "مرشد عُماني رسمي يتحدث الإنجليزية طوال الرحلة" },
      { en: "Private 4WD (Mitsubishi Pajero or similar) with fuel", ar: "سيارة دفع رباعي خاصة (ميتسوبيشي باجيرو أو مماثلة) مع الوقود" },
      { en: "Four nights: 4-star hotels in Muscat, classic camps/resorts on the coast and in the desert (double room)", ar: "أربع ليالٍ: فنادق أربع نجوم في مسقط ومخيمات/منتجعات كلاسيكية على الساحل وفي الصحراء (غرفة مزدوجة)" },
      { en: "Four breakfasts and three dinners", ar: "أربعة إفطارات وثلاثة عشاءات" },
      { en: "Entrance fees: Nizwa Fort, Wadi Shab, Sur dhow factory, Ras Al Jinz turtle reserve, Bait Al Zubair", ar: "رسوم الدخول: قلعة نزوى ووادي شاب ومصنع سفن صور ومحمية سلاحف رأس الجنز وبيت الزبير" },
      { en: "Airport meet & greet and bottled water", ar: "الاستقبال في المطار ومياه معبأة" },
    ],
    exclusions: [{ en: "Lunches and international flights", ar: "وجبات الغداء وتذاكر الطيران الدولية" }, ...commonExclusions],
    faqs: multiDayFaqs({
      question: { en: "Is the confirmation immediate?", ar: "هل التأكيد فوري؟" },
      answer: { en: "We confirm within 48 hours once the hotels and camps have been reserved in your name; your deposit is refunded in full if any date cannot be secured.", ar: "نؤكد خلال 48 ساعة بعد حجز الفنادق والمخيمات باسمك؛ ويُرد عربونك كاملًا إن تعذّر تأمين أي تاريخ." },
    }),
    category: "multi_day",
    secondaryCategories: ["desert_4x4", "mountain_wadi", "cultural"],
    destinations: ["muscat", "wadi_shab", "sur", "wahiba", "nizwa", "jebel_akhdar"],
    durationLabel: { en: "5 days / 4 nights", ar: "5 أيام / 4 ليالٍ" },
    durationMinutes: 5 * DAY,
    durationDays: 5,
    startTimes: ["09:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 629,
    priceChildOmr: 440,
    childAgeMax: 11,
    usdReference: 3270,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    externalReviewCount: 10,
    image: "wahiba",
    isFeatured: true,
    featuredOrder: 6,
    tags: ["multi-day", "bestseller", "honeymoon", "4x4", "private"],
    meetingPoint: airportMuscat,
  },
  {
    code: "OCT-009",
    viatorCode: "425555P33",
    kind: "tour",
    title: { en: "6-Day Oman Nature, Culture & Traditions – Small-Group Trip", ar: "6 أيام في طبيعة عُمان وثقافتها وتقاليدها: رحلة جماعية صغيرة" },
    slug: { en: "oman-nature-culture-traditions-6-day", ar: "عمان-6-أيام-جولة-جماعية" },
    summary: {
      en: "Four fixed departures a year: Muscat and Daymaniyat snorkelling, Wadi Shab, turtles at Ras Al Jinz, the Wahiba Sands, Nizwa, Misfat and Al Hoota Cave, and a dhow cruise — hotels, camps and most meals included.",
      ar: "أربع انطلاقات ثابتة في السنة: مسقط وغطس الديمانيات ووادي شاب وسلاحف رأس الجنز ورمال وهيبة ونزوى ومسفاة وكهف الهوتة ورحلة بالسفينة التقليدية، مع الفنادق والمخيمات ومعظم الوجبات.",
    },
    description: {
      en: "A guided group journey for travellers who like good company and an all-inclusive price. We travel by comfortable coach, switching to 4WDs for the desert, with an experienced Omani guide throughout. Day one combines Muscat's Royal Opera House and Grand Mosque with a snorkelling trip to the Daymaniyat Islands to swim with turtles. Day two is Wadi Shab and its waterfall cave, the Bimmah Sinkhole and turtle nesting at Ras Al Jinz; day three the dhow yard in Sur, Wadi Bani Khalid and a night in the Wahiba Sands. Day four starts with camel riding in the dunes (quad bikes optional) and continues to Nizwa's souq and fort. Day five explores the western Hajar: Al Hoota Cave, the terraced village of Misfat Al Abriyeen, Al Hamra and Bahla. Day six ends with a traditional dhow cruise, Old Muscat and shopping in Mutrah Souq.\n\nDepartures: 19–24 October 2026 · 28 December 2026–2 January 2027 · 1–6 February 2027 · 27 March–1 April 2027. Maximum 26 travellers.",
      ar: "رحلة جماعية بإرشاد للمسافرين الذين يحبون الصحبة الطيبة والسعر الشامل. نسافر بحافلة مريحة وننتقل إلى سيارات الدفع الرباعي في الصحراء، مع مرشد عُماني متمرّس طوال الرحلة. يجمع اليوم الأول بين دار الأوبرا السلطانية والجامع الأكبر ورحلة غطس سطحي إلى جزر الديمانيات للسباحة مع السلاحف. اليوم الثاني وادي شاب وكهف شلاله وحفرة بمة وتعشيش السلاحف في رأس الجنز؛ واليوم الثالث ورشة السفن في صور ووادي بني خالد وليلة في رمال وهيبة. يبدأ اليوم الرابع بركوب الإبل بين الكثبان (الدراجات الرباعية اختيارية) ويواصل إلى سوق نزوى وقلعتها. ويستكشف اليوم الخامس غرب الحجر: كهف الهوتة وقرية مسفاة العبريين المدرّجة والحمراء وبهلا. وينتهي اليوم السادس برحلة على سفينة تقليدية ومسقط القديمة والتسوّق في سوق مطرح.\n\nمواعيد الانطلاق: 19–24 أكتوبر 2026 · 28 ديسمبر 2026–2 يناير 2027 · 1–6 فبراير 2027 · 27 مارس–1 أبريل 2027. الحد الأقصى 26 مسافرًا.",
    },
    highlights: [
      { en: "Snorkelling with turtles at the Daymaniyat Islands", ar: "غطس سطحي مع السلاحف في جزر الديمانيات" },
      { en: "Wadi Shab, Bimmah Sinkhole and turtle nesting at Ras Al Jinz", ar: "وادي شاب وحفرة بمة وتعشيش السلاحف في رأس الجنز" },
      { en: "Night in the Wahiba Sands with camel riding", ar: "ليلة في رمال وهيبة مع ركوب الإبل" },
      { en: "Nizwa, Al Hoota Cave, Misfat Al Abriyeen and Bahla", ar: "نزوى وكهف الهوتة ومسفاة العبريين وبهلا" },
      { en: "Traditional dhow cruise and Mutrah Souq", ar: "رحلة بالسفينة التقليدية وسوق مطرح" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Muscat and the Daymaniyat Islands", ar: "مسقط وجزر الديمانيات" }, body: { en: "08:00 pickup, Royal Opera House, Grand Mosque, Daymaniyat snorkelling trip (5 h), seafood dinner in Seeb. Overnight at a 4-star hotel in Muscat.", ar: "الاستلام 08:00، دار الأوبرا، الجامع الأكبر، رحلة غطس في الديمانيات (5 ساعات)، عشاء بحري في السيب. المبيت في فندق أربع نجوم في مسقط." } },
      { time: "Day 2", title: { en: "Wadi Shab and Ras Al Jinz", ar: "وادي شاب ورأس الجنز" }, body: { en: "Bimmah Sinkhole, Wadi Shab (3 h), turtle reserve after dark (3 h). Overnight at a camp or resort in Ras Al Hadd; breakfast and dinner.", ar: "حفرة بمة، وادي شاب (3 ساعات)، محمية السلاحف بعد الغروب (3 ساعات). المبيت في مخيم أو منتجع في رأس الحد؛ الإفطار والعشاء." } },
      { time: "Day 3", title: { en: "Sur, Wadi Bani Khalid and the desert", ar: "صور ووادي بني خالد والصحراء" }, body: { en: "Sur dhow yard, Wadi Bani Khalid swim, sunset in the Wahiba Sands. Overnight at a desert camp; breakfast and dinner.", ar: "ورشة سفن صور، سباحة في وادي بني خالد، غروب في رمال وهيبة. المبيت في مخيم صحراوي؛ الإفطار والعشاء." } },
      { time: "Day 4", title: { en: "Camels, dunes and Nizwa", ar: "الإبل والكثبان ونزوى" }, body: { en: "Morning camel ride (quad bikes optional), Nizwa Souq and Nizwa Fort. Overnight at a 4-star hotel in Nizwa; breakfast and dinner.", ar: "ركوب الإبل صباحًا (الدراجات الرباعية اختيارية)، سوق نزوى وقلعة نزوى. المبيت في فندق أربع نجوم في نزوى؛ الإفطار والعشاء." } },
      { time: "Day 5", title: { en: "Western Hajar mountains", ar: "جبال الحجر الغربي" }, body: { en: "Al Hoota Cave, Misfat Al Abriyeen, Al Hamra and Bahla. Overnight at a 4-star hotel in Muscat; breakfast and dinner.", ar: "كهف الهوتة، مسفاة العبريين، الحمراء، بهلا. المبيت في فندق أربع نجوم في مسقط؛ الإفطار والعشاء." } },
      { time: "Day 6", title: { en: "Dhow cruise and Old Muscat", ar: "رحلة السفينة ومسقط القديمة" }, body: { en: "Two-hour dhow cruise from Marina Bandar Al Rowdha, Al Alam Palace, Mutrah Souq, farewell lunch; breakfast and lunch.", ar: "رحلة سفينة لساعتين من مرسى بندر الروضة، قصر العلم، سوق مطرح، غداء الوداع؛ الإفطار والغداء." } },
    ],
    inclusions: [
      { en: "Experienced Omani guide for six days", ar: "مرشد عُماني متمرّس لستة أيام" },
      { en: "Comfortable coach, with 4WDs in the desert", ar: "حافلة مريحة وسيارات دفع رباعي في الصحراء" },
      { en: "Five nights at 4-star hotels and classic camps/resorts (two per room)", ar: "خمس ليالٍ في فنادق أربع نجوم ومخيمات/منتجعات كلاسيكية (شخصان في الغرفة)" },
      { en: "Five breakfasts, five dinners and two lunches", ar: "خمسة إفطارات وخمسة عشاءات وغداءان" },
      { en: "Daymaniyat snorkelling trip, dhow cruise, camel ride and all entrance fees", ar: "رحلة غطس الديمانيات ورحلة السفينة وركوب الإبل وجميع رسوم الدخول" },
      { en: "Pickup from anywhere in Muscat", ar: "الاستلام من أي مكان في مسقط" },
    ],
    exclusions: [{ en: "Quad biking and other optional activities", ar: "الدراجات الرباعية والأنشطة الاختيارية الأخرى" }, { en: "Single-room supplement (contact us for a quote)", ar: "فرق الغرفة المفردة (تواصل معنا لعرض سعر)" }, ...commonExclusions],
    faqs: multiDayFaqs({
      question: { en: "Which dates does this trip run?", ar: "في أي تواريخ تُنفَّذ هذه الرحلة؟" },
      answer: { en: "Four departures: 19 October 2026, 28 December 2026 (New Year), 1 February 2027 and 27 March 2027 (Easter). Please select the first day of a departure as your booking date; the trip needs a minimum number of travellers, and if a departure is cancelled you receive a full refund or an alternative date.", ar: "أربع انطلاقات: 19 أكتوبر 2026، و28 ديسمبر 2026 (رأس السنة)، و1 فبراير 2027، و27 مارس 2027 (عيد الفصح). يرجى اختيار اليوم الأول للانطلاقة تاريخًا للحجز؛ تحتاج الرحلة إلى حد أدنى من المسافرين، وإذا أُلغيت انطلاقة تحصل على استرداد كامل أو تاريخ بديل." },
    }),
    category: "multi_day",
    secondaryCategories: ["boat", "cultural", "desert_4x4"],
    destinations: ["muscat", "daymaniyat", "wadi_shab", "sur", "wahiba", "nizwa", "jabal_shams"],
    durationLabel: { en: "6 days / 5 nights", ar: "6 أيام / 5 ليالٍ" },
    durationMinutes: 6 * DAY,
    durationDays: 6,
    startTimes: ["08:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 26,
    capacityPerSlot: 26,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 663,
    priceChildOmr: 460,
    childAgeMax: 11,
    usdReference: 3450,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    externalReviewCount: 2,
    image: "sur",
    isFeatured: true,
    featuredOrder: 8,
    tags: ["group-trip", "fixed-dates", "snorkelling", "desert", "all-inclusive"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-020",
    viatorCode: "425555P14",
    kind: "tour",
    title: { en: "5-Star Muscat Stay: 4 Nights at W Muscat & 3 Private Guided Days", ar: "إقامة خمس نجوم في مسقط: 4 ليالٍ في فندق W مسقط و3 أيام خاصة بإرشاد" },
    slug: { en: "five-star-muscat-4-nights-journey", ar: "رحلة-فندق-5-نجوم-4-ليال" },
    summary: {
      en: "Four nights at the beachfront W Muscat with three full private days: Muscat's landmarks and a sunset cruise, Wadi Shab and the Bimmah Sinkhole, and Nizwa with Jabal Akhdar.",
      ar: "أربع ليالٍ في فندق W مسقط على الشاطئ مع ثلاثة أيام خاصة كاملة: معالم مسقط ورحلة الغروب، ووادي شاب وحفرة بمة، ونزوى مع الجبل الأخضر.",
    },
    description: {
      en: "Luxury without compromise on the excursions. You are met at the airport and settled into the W Muscat, a five-star beachfront hotel in Shatti Al Qurum with a standard room for two. Day two is Muscat with your Omani guide: the Sultan Qaboos Grand Mosque, the Royal Opera House, Mutrah Souq, Bait Al Zubair, Al Alam Palace and a two-hour sunset dhow cruise from Marina Bandar Al Rowdha. Day three heads down the coast for the Wadi Shab hike and swim to the waterfall cave, lunch in Tiwi and a dip in the Bimmah Sinkhole. Day four climbs inland to Nizwa's souq and fort and up Jabal Akhdar for the mountain villages. Day five is free until your airport transfer. Breakfast every day and lunch on the city day are included.",
      ar: "فخامة دون تنازل عن الرحلات. نستقبلك في المطار ونستقر بك في فندق W مسقط، فندق خمس نجوم على شاطئ شاطئ القرم بغرفة قياسية لشخصين. اليوم الثاني مسقط مع مرشدك العُماني: جامع السلطان قابوس الأكبر ودار الأوبرا السلطانية وسوق مطرح وبيت الزبير وقصر العلم ورحلة غروب لساعتين بالسفينة التقليدية من مرسى بندر الروضة. يتوجّه اليوم الثالث جنوبًا على الساحل لمسار وادي شاب والسباحة إلى كهف الشلال، والغداء في طيوي، وسباحة في حفرة بمة. ويصعد اليوم الرابع إلى الداخل لسوق نزوى وقلعتها ثم إلى الجبل الأخضر لقراه الجبلية. اليوم الخامس حر حتى موعد التوصيل إلى المطار. الإفطار يوميًا والغداء في يوم المدينة مشمولان.",
    },
    highlights: [
      { en: "Four nights at the 5-star W Muscat (beach view)", ar: "أربع ليالٍ في فندق W مسقط خمس نجوم (إطلالة على الشاطئ)" },
      { en: "Grand Mosque, Opera House, Mutrah Souq and a sunset dhow cruise", ar: "الجامع الأكبر ودار الأوبرا وسوق مطرح ورحلة غروب بالسفينة" },
      { en: "Wadi Shab waterfall cave and Bimmah Sinkhole", ar: "كهف شلال وادي شاب وحفرة بمة" },
      { en: "Nizwa Souq, Nizwa Fort and Jabal Akhdar", ar: "سوق نزوى وقلعة نزوى والجبل الأخضر" },
      { en: "Private 4WD and Omani guide on every excursion", ar: "سيارة دفع رباعي خاصة ومرشد عُماني في كل رحلة" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Arrival", ar: "الوصول" }, body: { en: "Airport meet & greet and transfer to the W Muscat.", ar: "الاستقبال في المطار والتوصيل إلى فندق W مسقط." } },
      { time: "Day 2", title: { en: "Muscat and sunset cruise (8 h)", ar: "مسقط ورحلة الغروب (8 ساعات)" }, body: { en: "Grand Mosque, Royal Opera House, Mutrah Souq, Bait Al Zubair, Al Alam Palace, lunch, two-hour dhow cruise; breakfast and lunch.", ar: "الجامع الأكبر، دار الأوبرا، سوق مطرح، بيت الزبير، قصر العلم، الغداء، رحلة سفينة لساعتين؛ الإفطار والغداء." } },
      { time: "Day 3", title: { en: "Wadi Shab and Bimmah Sinkhole (8 h)", ar: "وادي شاب وحفرة بمة (8 ساعات)" }, body: { en: "Wadi Shab hike and swim (3 h), Bimmah Sinkhole (40 min), lunch in Tiwi; breakfast.", ar: "مسار وسباحة في وادي شاب (3 ساعات)، حفرة بمة (40 دقيقة)، الغداء في طيوي؛ الإفطار." } },
      { time: "Day 4", title: { en: "Nizwa and Jabal Akhdar (8 h)", ar: "نزوى والجبل الأخضر (8 ساعات)" }, body: { en: "Nizwa Souq, Nizwa Fort (entrance included), Jabal Akhdar villages and viewpoints; breakfast.", ar: "سوق نزوى، قلعة نزوى (الدخول مشمول)، قرى الجبل الأخضر وإطلالاته؛ الإفطار." } },
      { time: "Day 5", title: { en: "Departure", ar: "المغادرة" }, body: { en: "Breakfast, free time and airport transfer.", ar: "الإفطار ووقت حر والتوصيل إلى المطار." } },
    ],
    inclusions: [
      { en: "Four nights at W Muscat, 5-star (one standard room for two, breakfast included)", ar: "أربع ليالٍ في فندق W مسقط خمس نجوم (غرفة قياسية لشخصين مع الإفطار)" },
      { en: "Experienced English-speaking Omani guide on three excursion days", ar: "مرشد عُماني متمرّس يتحدث الإنجليزية في أيام الرحلات الثلاثة" },
      { en: "Private 4WD with fuel and all airport transfers", ar: "سيارة دفع رباعي خاصة مع الوقود وجميع التنقلات من وإلى المطار" },
      { en: "Lunch on the Muscat day, sunset dhow cruise, entrance fees", ar: "غداء يوم مسقط ورحلة الغروب بالسفينة ورسوم الدخول" },
      { en: "Bottled water", ar: "مياه معبأة" },
    ],
    exclusions: [{ en: "Dinners and lunches not listed above", ar: "وجبات العشاء والغداء غير المذكورة أعلاه" }, ...commonExclusions],
    faqs: multiDayFaqs({
      question: { en: "Can we choose another hotel?", ar: "هل يمكننا اختيار فندق آخر؟" },
      answer: { en: "Yes. Tell us your preferred property (Shangri-La, Kempinski, Jumeirah Muscat Bay and others) and we re-quote the package for your dates.", ar: "نعم. أخبرنا بالفندق الذي تفضّله (شانغريلا، كمبينسكي، جميرا خليج مسقط وغيرها) ونعيد تسعير الباقة لتواريخك." },
    }),
    category: "multi_day",
    secondaryCategories: ["city_tours", "mountain_wadi"],
    destinations: ["muscat", "wadi_shab", "nizwa", "jebel_akhdar"],
    durationLabel: { en: "5 days / 4 nights", ar: "5 أيام / 4 ليالٍ" },
    durationMinutes: 5 * DAY,
    durationDays: 5,
    startTimes: ["08:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 423,
    priceChildOmr: 300,
    childAgeMax: 11,
    usdReference: 2200,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    externalReviewCount: 2,
    image: "muscat",
    isFeatured: false,
    tags: ["luxury", "hotel", "multi-day", "private"],
    meetingPoint: airportMuscat,
  },
  {
    code: "OCT-021",
    viatorCode: "425555P21",
    kind: "tour",
    title: { en: "7-Day Guided 4WD Rooftop-Tent Round Trip of Oman", ar: "7 أيام جولة عُمان الكاملة بالدفع الرباعي وخيمة السقف مع مرشد" },
    slug: { en: "oman-roof-tent-4wd-7-day-adventure", ar: "عمان-7-أيام-خيمة-سقف-السيارة" },
    summary: {
      en: "For nature lovers: four nights camping on beaches, in the desert and on Jabal Shams with a rooftop-tent 4WD and a guide who cooks, plus two hotel nights in Muscat and a Daymaniyat snorkelling day.",
      ar: "لعشّاق الطبيعة: أربع ليالٍ تخييم على الشواطئ وفي الصحراء وعلى جبل شمس بسيارة دفع رباعي مزوّدة بخيمة سقف ومرشد يطهو، مع ليلتين في فندق في مسقط ويوم غطس في الديمانيات.",
    },
    description: {
      en: "The adventure of a lifetime, designed for travellers who want to sleep under the stars every night the landscape allows. After a hotel night in Muscat we hike and swim Wadi Shab and camp on Fins beach with a barbecue. We visit Sur and Wadi Bani Khalid, then watch sunset and sunrise over the Wahiba dunes from our desert camp. A three-hour off-road drive leads through the sands to the remote coast of Barr Al Hikman, where we camp again by the sea, before climbing to Jabal Shams to pitch the tent on the rim of the Grand Canyon. The mountain day explores Misfat Al Abriyeen, Al Hoota Cave and Nizwa's souq and fort before a hotel night in Muscat, and the last full day is spent snorkelling at the Daymaniyat Islands with a seafood lunch. Your guide sets up the rooftop tents, cooks dinner and breakfast on every camping night and drives the 4WD throughout.",
      ar: "مغامرة العمر، مصمّمة للمسافرين الذين يريدون النوم تحت النجوم في كل ليلة تسمح بها الطبيعة. بعد ليلة في فندق في مسقط نمشي ونسبح في وادي شاب ونخيّم على شاطئ فنس مع الشواء. نزور صور ووادي بني خالد، ثم نشاهد الغروب والشروق فوق كثبان وهيبة من مخيمنا الصحراوي. تقودنا رحلة وعرة لثلاث ساعات عبر الرمال إلى ساحل بر الحكمان النائي حيث نخيّم مجددًا بجوار البحر، قبل الصعود إلى جبل شمس لننصب الخيمة على حافة الأخدود الكبير. يستكشف يوم الجبل مسفاة العبريين وكهف الهوتة وسوق نزوى وقلعتها قبل ليلة في فندق في مسقط، ويُقضى اليوم الأخير في الغطس السطحي عند جزر الديمانيات مع غداء بحري. ينصب مرشدك خيام السقف ويطهو العشاء والإفطار في كل ليلة تخييم ويقود سيارة الدفع الرباعي طوال الرحلة.",
    },
    highlights: [
      { en: "Rooftop-tent 4WD with a guide who cooks and drives", ar: "سيارة دفع رباعي بخيمة سقف مع مرشد يطهو ويقود" },
      { en: "Beach camps at Fins and Barr Al Hikman", ar: "مخيمات شاطئية في فنس وبر الحكمان" },
      { en: "Sunset and sunrise in the Wahiba Sands", ar: "غروب وشروق في رمال وهيبة" },
      { en: "A night on the rim of the Grand Canyon at Jabal Shams", ar: "ليلة على حافة الأخدود الكبير في جبل شمس" },
      { en: "Daymaniyat Islands snorkelling and seafood lunch", ar: "غطس سطحي في جزر الديمانيات وغداء بحري" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Welcome to Oman", ar: "أهلًا بك في عُمان" }, body: { en: "Airport pickup, free time in Muscat, briefing and dinner. Overnight at a 4-star hotel.", ar: "الاستلام من المطار، وقت حر في مسقط، إحاطة وعشاء. المبيت في فندق أربع نجوم." } },
      { time: "Day 2", title: { en: "Wadi Shab and Fins beach", ar: "وادي شاب وشاطئ فنس" }, body: { en: "Bimmah Sinkhole, Wadi Shab hike and swim (3 h), beach camp at Fins with barbecue; breakfast and dinner.", ar: "حفرة بمة، مسار وسباحة في وادي شاب (3 ساعات)، مخيم على شاطئ فنس مع شواء؛ الإفطار والعشاء." } },
      { time: "Day 3", title: { en: "Sur, Wadi Bani Khalid and the desert", ar: "صور ووادي بني خالد والصحراء" }, body: { en: "Sur, Wadi Bani Khalid (2 h), Wahiba Sands sunset, desert camp; breakfast and dinner.", ar: "صور، وادي بني خالد (ساعتان)، غروب في رمال وهيبة، مخيم صحراوي؛ الإفطار والعشاء." } },
      { time: "Day 4", title: { en: "Across the sands to Barr Al Hikman", ar: "عبر الرمال إلى بر الحكمان" }, body: { en: "Three-hour off-road desert crossing, drive to the coast, beach camp; breakfast and dinner.", ar: "عبور صحراوي وعر لثلاث ساعات، الطريق إلى الساحل، مخيم شاطئي؛ الإفطار والعشاء." } },
      { time: "Day 5", title: { en: "Barr Al Hikman to Jabal Shams", ar: "من بر الحكمان إلى جبل شمس" }, body: { en: "Coastal morning, mountain drive (5 h), camp on the canyon rim; breakfast and dinner.", ar: "صباح ساحلي، قيادة جبلية (5 ساعات)، مخيم على حافة الأخدود؛ الإفطار والعشاء." } },
      { time: "Day 6", title: { en: "Misfat, Al Hoota Cave and Nizwa", ar: "مسفاة وكهف الهوتة ونزوى" }, body: { en: "Misfat Al Abriyeen, Al Hoota Cave, Nizwa Souq and Fort, hotel in Muscat; breakfast and lunch.", ar: "مسفاة العبريين، كهف الهوتة، سوق نزوى وقلعتها، فندق في مسقط؛ الإفطار والغداء." } },
      { time: "Day 7", title: { en: "Daymaniyat Islands and departure", ar: "جزر الديمانيات والمغادرة" }, body: { en: "Five hours of snorkelling, seafood lunch, airport transfer; breakfast and lunch.", ar: "خمس ساعات غطس سطحي، غداء بحري، التوصيل إلى المطار؛ الإفطار والغداء." } },
    ],
    inclusions: [
      { en: "4WD Mitsubishi Pajero (or similar) with rooftop tents and camping gear", ar: "سيارة ميتسوبيشي باجيرو (أو مماثلة) بخيام سقف ومعدات تخييم" },
      { en: "Official Omani guide who drives, sets up camp and cooks", ar: "مرشد عُماني رسمي يقود وينصب المخيم ويطهو" },
      { en: "Four nights camping (beach, desert, mountain) and two nights at a 4-star hotel in Muscat", ar: "أربع ليالٍ تخييم (شاطئ وصحراء وجبل) وليلتان في فندق أربع نجوم في مسقط" },
      { en: "Breakfast and dinner on camping days, lunches on days 6 and 7", ar: "الإفطار والعشاء في أيام التخييم والغداء في اليومين السادس والسابع" },
      { en: "Daymaniyat snorkelling trip, entrance fees, bottled water and airport transfers", ar: "رحلة غطس الديمانيات ورسوم الدخول ومياه معبأة والتنقلات من وإلى المطار" },
    ],
    exclusions: [{ en: "Lunches on days 2–5 and dinner on day 6", ar: "وجبات الغداء في الأيام 2–5 وعشاء اليوم السادس" }, ...commonExclusions],
    faqs: multiDayFaqs({
      question: { en: "How comfortable is the camping?", ar: "ما مدى راحة التخييم؟" },
      answer: { en: "Rooftop tents have thick mattresses, bedding and mosquito nets; camps have no showers except in the desert camp, so we plan swims and a hotel night in the middle of the trip. Best from October to April.", ar: "خيام السقف مزوّدة بفرشات سميكة وأغطية وناموسيات؛ ولا تتوفر مرافق استحمام إلا في مخيم الصحراء، لذا نخطط للسباحة وليلة فندقية في منتصف الرحلة. الأفضل من أكتوبر إلى أبريل." },
    }),
    category: "multi_day",
    secondaryCategories: ["hiking_camping", "desert_4x4", "boat"],
    destinations: ["muscat", "wadi_shab", "sur", "wahiba", "jabal_shams", "nizwa", "daymaniyat"],
    durationLabel: { en: "7 days / 6 nights", ar: "7 أيام / 6 ليالٍ" },
    durationMinutes: 7 * DAY,
    durationDays: 7,
    startTimes: ["09:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "challenging",
    pricingModel: "per_person",
    priceAdultOmr: 1029,
    priceChildOmr: 720,
    childAgeMax: 11,
    usdReference: 5350,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    image: "wahiba",
    isFeatured: false,
    tags: ["camping", "adventure", "4x4", "snorkelling", "private"],
    meetingPoint: airportMuscat,
  },
  {
    code: "OCT-010",
    viatorCode: "425555P12",
    kind: "tour",
    title: { en: "8-Day Oman Nature & Culture with an Omani Guide – 4WD", ar: "8 أيام في طبيعة عُمان وثقافتها مع مرشد عُماني بالدفع الرباعي" },
    slug: { en: "complete-oman-experience-8-day", ar: "تجربة-عمان-الكاملة-8-أيام" },
    summary: {
      en: "The complete circuit at an unhurried pace: Wadi Shab, turtles, Sur, Wadi Bani Khalid, the Wahiba Sands, Jabal Akhdar, Nizwa, Al Hoota Cave, Misfat, Muscat and a Daymaniyat snorkelling day.",
      ar: "المسار الكامل بوتيرة هادئة: وادي شاب والسلاحف وصور ووادي بني خالد ورمال وهيبة والجبل الأخضر ونزوى وكهف الهوتة ومسفاة ومسقط ويوم غطس في الديمانيات.",
    },
    description: {
      en: "Everything the five-day journey offers with three extra days for the mountains, the sea and the capital. After an airport welcome and a first night in Muscat, days two and three follow the coast to Wadi Shab, Ras Al Jinz turtles, the Sur dhow yard and Wadi Bani Khalid, then into the Wahiba Sands for a night in the desert. Day four climbs from the dunes via Birkat Al Mouz to a night at a four-star hotel on Jabal Akhdar. Day five explores Nizwa, Al Hoota Cave and Misfat Al Abriyeen; day six is Muscat with the Grand Mosque, Mutrah Souq, Bait Al Zubair and a dhow cruise. Day seven is a boat trip to the Daymaniyat Islands to snorkel with turtles and reef fish, and day eight ends at the airport. Seven nights in four-star hotels and classic camps with breakfast and dinner, a private 4WD, an official Omani guide and all entrance fees are included.",
      ar: "كل ما تقدّمه رحلة الخمسة أيام مع ثلاثة أيام إضافية للجبال والبحر والعاصمة. بعد الاستقبال في المطار وليلة أولى في مسقط، يتبع اليومان الثاني والثالث الساحل إلى وادي شاب وسلاحف رأس الجنز وورشة سفن صور ووادي بني خالد، ثم إلى رمال وهيبة لليلة في الصحراء. يصعد اليوم الرابع من الكثبان عبر بركة الموز إلى ليلة في فندق أربع نجوم في الجبل الأخضر. ويستكشف اليوم الخامس نزوى وكهف الهوتة ومسفاة العبريين؛ واليوم السادس مسقط مع الجامع الأكبر وسوق مطرح وبيت الزبير ورحلة بالسفينة. اليوم السابع رحلة بحرية إلى جزر الديمانيات للغطس مع السلاحف وأسماك الشعاب، وينتهي اليوم الثامن في المطار. يشمل السعر سبع ليالٍ في فنادق أربع نجوم ومخيمات كلاسيكية مع الإفطار والعشاء وسيارة دفع رباعي خاصة ومرشدًا عُمانيًا رسميًا وجميع رسوم الدخول.",
    },
    highlights: [
      { en: "Wadi Shab, Bimmah Sinkhole and turtles at Ras Al Jinz", ar: "وادي شاب وحفرة بمة وسلاحف رأس الجنز" },
      { en: "Sur dhow yard, Wadi Bani Khalid and a Wahiba desert night", ar: "ورشة سفن صور ووادي بني خالد وليلة في صحراء وهيبة" },
      { en: "A night on Jabal Akhdar and the villages of the Green Mountain", ar: "ليلة في الجبل الأخضر وقرى الجبل" },
      { en: "Nizwa, Al Hoota Cave and Misfat Al Abriyeen", ar: "نزوى وكهف الهوتة ومسفاة العبريين" },
      { en: "Muscat city day with dhow cruise, plus Daymaniyat snorkelling", ar: "يوم مسقط مع رحلة السفينة، وغطس في الديمانيات" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Welcome to Oman", ar: "أهلًا بك في عُمان" }, body: { en: "Airport pickup, free time, dinner. Overnight at a 4-star hotel in Muscat.", ar: "الاستلام من المطار، وقت حر، العشاء. المبيت في فندق أربع نجوم في مسقط." } },
      { time: "Day 2", title: { en: "Wadi Shab and Ras Al Jinz", ar: "وادي شاب ورأس الجنز" }, body: { en: "Bimmah Sinkhole (45 min), Wadi Shab (3 h), turtle reserve after dark (2 h). Overnight at a camp/resort in Ras Al Jinz; breakfast and dinner.", ar: "حفرة بمة (45 دقيقة)، وادي شاب (3 ساعات)، محمية السلاحف بعد الغروب (ساعتان). المبيت في مخيم/منتجع في رأس الجنز؛ الإفطار والعشاء." } },
      { time: "Day 3", title: { en: "Sur, Wadi Bani Khalid and the Wahiba Sands", ar: "صور ووادي بني خالد ورمال وهيبة" }, body: { en: "Sur dhow yard (1 h), Wadi Bani Khalid (1 h 30), desert sunset. Overnight at a desert camp; breakfast and dinner.", ar: "ورشة سفن صور (ساعة)، وادي بني خالد (ساعة ونصف)، غروب صحراوي. المبيت في مخيم صحراوي؛ الإفطار والعشاء." } },
      { time: "Day 4", title: { en: "Desert to the Green Mountain", ar: "من الصحراء إلى الجبل الأخضر" }, body: { en: "Dune morning (1 h), Birkat Al Mouz (1 h), Jabal Akhdar villages (2 h). Overnight at a 4-star hotel on Jabal Akhdar; breakfast and dinner.", ar: "صباح على الكثبان (ساعة)، بركة الموز (ساعة)، قرى الجبل الأخضر (ساعتان). المبيت في فندق أربع نجوم في الجبل الأخضر؛ الإفطار والعشاء." } },
      { time: "Day 5", title: { en: "Nizwa, Al Hoota Cave and Misfat", ar: "نزوى وكهف الهوتة ومسفاة" }, body: { en: "Nizwa Souq and Fort, Al Hoota Cave, Misfat Al Abriyeen. Overnight in Muscat; breakfast and dinner.", ar: "سوق نزوى وقلعتها، كهف الهوتة، مسفاة العبريين. المبيت في مسقط؛ الإفطار والعشاء." } },
      { time: "Day 6", title: { en: "Muscat and dhow cruise", ar: "مسقط ورحلة السفينة" }, body: { en: "Grand Mosque, Royal Opera House, Mutrah Souq, Bait Al Zubair, Al Alam Palace, two-hour dhow cruise. Overnight in Muscat; breakfast and lunch.", ar: "الجامع الأكبر، دار الأوبرا، سوق مطرح، بيت الزبير، قصر العلم، رحلة سفينة لساعتين. المبيت في مسقط؛ الإفطار والغداء." } },
      { time: "Day 7", title: { en: "Daymaniyat Islands", ar: "جزر الديمانيات" }, body: { en: "Snorkelling trip (5 h) and seafood lunch. Overnight in Muscat; breakfast and lunch.", ar: "رحلة غطس سطحي (5 ساعات) وغداء بحري. المبيت في مسقط؛ الإفطار والغداء." } },
      { time: "Day 8", title: { en: "Departure", ar: "المغادرة" }, body: { en: "Breakfast and airport transfer.", ar: "الإفطار والتوصيل إلى المطار." } },
    ],
    inclusions: [
      { en: "Official English-speaking Omani guide throughout", ar: "مرشد عُماني رسمي يتحدث الإنجليزية طوال الرحلة" },
      { en: "Private 4WD (Mitsubishi Pajero or similar) with fuel; sedan in Muscat", ar: "سيارة دفع رباعي خاصة (ميتسوبيشي باجيرو أو مماثلة) مع الوقود؛ وسيدان في مسقط" },
      { en: "Seven nights at 4-star hotels and classic camps/resorts (double room)", ar: "سبع ليالٍ في فنادق أربع نجوم ومخيمات/منتجعات كلاسيكية (غرفة مزدوجة)" },
      { en: "Seven breakfasts, five dinners and two lunches", ar: "سبعة إفطارات وخمسة عشاءات وغداءان" },
      { en: "Daymaniyat snorkelling trip, dhow cruise and all entrance fees", ar: "رحلة غطس الديمانيات ورحلة السفينة وجميع رسوم الدخول" },
      { en: "Airport meet & greet and bottled water", ar: "الاستقبال في المطار ومياه معبأة" },
    ],
    exclusions: [{ en: "Lunches not listed above and international flights", ar: "وجبات الغداء غير المذكورة وتذاكر الطيران الدولية" }, ...commonExclusions],
    faqs: multiDayFaqs(),
    category: "multi_day",
    secondaryCategories: ["desert_4x4", "boat", "mountain_wadi"],
    destinations: ["muscat", "wadi_shab", "sur", "wahiba", "jebel_akhdar", "nizwa", "jabal_shams", "daymaniyat"],
    durationLabel: { en: "8 days / 7 nights", ar: "8 أيام / 7 ليالٍ" },
    durationMinutes: 8 * DAY,
    durationDays: 8,
    startTimes: ["09:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 792,
    priceChildOmr: 550,
    childAgeMax: 11,
    usdReference: 4120,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    externalReviewCount: 10,
    image: "wahiba",
    isFeatured: false,
    tags: ["multi-day", "complete", "snorkelling", "4x4", "private"],
    meetingPoint: airportMuscat,
  },
];
