import type { CategoryKey } from "./categories";
import type { DestinationKey } from "./destinations";

type L = { en: string; ar: string };

export type TourSeed = {
  code: string;
  kind: "tour" | "service";
  title: L;
  slug: L;
  summary: L;
  description: L;
  highlights: L[];
  itinerary: { time?: string; title: L; body: L }[];
  inclusions: L[];
  exclusions: L[];
  faqs: { question: L; answer: L }[];
  category: CategoryKey;
  secondaryCategories?: CategoryKey[];
  destinations: DestinationKey[];
  durationLabel: L;
  durationMinutes: number;
  durationDays: number;
  startTimes: string[];
  pickupIncluded: boolean;
  guideLanguages: string[];
  minGroup: number;
  maxGroup: number;
  capacityPerSlot: number;
  difficulty?: "easy" | "moderate" | "challenging";
  pricingModel: "per_group" | "per_person";
  /** OMR (major units) */
  priceGroupOmr?: number;
  priceAdultOmr?: number;
  priceChildOmr?: number;
  childAgeMax?: number;
  /** USD reference from Tripadvisor/Viator, if any */
  usdReference?: number;
  depositPercent: number;
  freeCancellationHours: number;
  allowReserveNowPayLater: boolean;
  holdHours: number;
  ratingAverage: number;
  externalReviewCount?: number;
  image: string; // placeholder key under /media/placeholders
  isFeatured: boolean;
  featuredOrder?: number;
  tags: string[];
  meetingPoint?: { label: L; address?: string; lat?: number; lng?: number };
  priceIsPlaceholder?: boolean;
};

const commonExclusions: L[] = [
  { en: "Personal expenses and gratuities", ar: "المصاريف الشخصية والإكراميات" },
  { en: "Travel insurance", ar: "تأمين السفر" },
  { en: "Anything not mentioned under inclusions", ar: "أي شيء غير مذكور ضمن ما يشمله السعر" },
];

const commonFaqs = (cancelHours: number): { question: L; answer: L }[] => [
  {
    question: { en: "Is hotel pickup included?", ar: "هل يشمل السعر الاستلام من الفندق؟" },
    answer: {
      en: "Yes. We collect you from any hotel or address in Muscat in a private, air-conditioned vehicle and drop you back at the end of the tour.",
      ar: "نعم. نستقبلك من أي فندق أو عنوان في مسقط بسيارة خاصة مكيّفة ونعيدك في نهاية الجولة.",
    },
  },
  {
    question: { en: "What is the cancellation policy?", ar: "ما هي سياسة الإلغاء؟" },
    answer: {
      en: `Free cancellation up to ${cancelHours} hours before the start time for a full refund. Later cancellations and no-shows are non-refundable.`,
      ar: `إلغاء مجاني حتى ${cancelHours} ساعة قبل موعد البدء مع استرداد كامل المبلغ. الإلغاء بعد ذلك أو عدم الحضور غير قابل للاسترداد.`,
    },
  },
  {
    question: { en: "Is this a private tour?", ar: "هل هذه جولة خاصة؟" },
    answer: {
      en: "Yes. Every departure is private to your party, with your own Omani guide and vehicle, so the pace and stops adapt to you.",
      ar: "نعم. كل انطلاقة خاصة بمجموعتك مع مرشد عُماني وسيارة خاصة، بحيث تتكيّف الوتيرة والمحطات مع رغباتك.",
    },
  },
  {
    question: { en: "What should I wear?", ar: "ماذا أرتدي؟" },
    answer: {
      en: "Light, modest clothing that covers shoulders and knees is recommended, especially at mosques and in villages. Bring a hat, sunscreen and comfortable shoes.",
      ar: "ننصح بملابس خفيفة ومحتشمة تغطي الكتفين والركبتين، خاصة في المساجد والقرى. أحضر قبعة وواقي شمس وحذاءً مريحًا.",
    },
  },
];

export const toursSeed: TourSeed[] = [
  {
    code: "OCT-001",
    kind: "tour",
    title: {
      en: "Experience Muscat City Tour – Omani Guide & Traditional Food",
      ar: "جولة مسقط مع مرشد عُماني وطعام تقليدي",
    },
    slug: { en: "experience-muscat-city-tour", ar: "جولة-مسقط-مع-مرشد-عماني" },
    summary: {
      en: "The essential Muscat: Grand Mosque, Mutrah Souq, the Corniche and Old Muscat, finished with authentic Omani food and kahwa.",
      ar: "خلاصة مسقط: الجامع الأكبر وسوق مطرح والكورنيش ومسقط القديمة، مع ختام بطعام عُماني أصيل وقهوة.",
    },
    description: {
      en: "Spend half a day discovering the capital with a licensed Omani guide who grew up here. We begin at the Sultan Qaboos Grand Mosque, one of the largest in the world, where you will learn the stories behind its chandelier and its hand-knotted Persian carpet. From there we drive along the Corniche to Mutrah, wander the frankincense-scented lanes of the souq and watch the fishermen at the harbour. In Old Muscat we photograph Al Alam Palace and the twin Portuguese forts of Mirani and Jalali before sitting down to a traditional Omani meal — shuwa or maqbous, fresh bread, dates, halwa and Omani coffee — served the way local families enjoy it.\n\nThe tour is private, unhurried and fully customisable: tell your guide what interests you most and the route adapts.",
      ar: "اقضِ نصف يوم في اكتشاف العاصمة برفقة مرشد عُماني مرخّص نشأ فيها. نبدأ من جامع السلطان قابوس الأكبر، أحد أكبر المساجد في العالم، حيث تتعرّف على قصة ثريّاه وسجادته الفارسية المنسوجة يدويًا. ثم نتوجّه عبر الكورنيش إلى مطرح لنتجوّل في أزقة السوق العابقة برائحة اللبان ونشاهد الصيادين في الميناء. وفي مسقط القديمة نلتقط الصور لقصر العلم وقلعتَي الميراني والجلالي البرتغاليتين، قبل أن نجلس لوجبة عُمانية تقليدية؛ شواء أو مقبوس مع الخبز الطازج والتمر والحلوى والقهوة العُمانية، تُقدَّم كما تستمتع بها العائلات المحلية.\n\nالجولة خاصة وهادئة وقابلة للتخصيص بالكامل: أخبر مرشدك بما يهمّك أكثر وسيتكيّف المسار معك.",
    },
    highlights: [
      { en: "Guided visit to the Sultan Qaboos Grand Mosque", ar: "زيارة بإرشاد لجامع السلطان قابوس الأكبر" },
      { en: "Mutrah Souq, Corniche and fish market", ar: "سوق مطرح والكورنيش وسوق السمك" },
      { en: "Al Alam Palace and the Mirani & Jalali forts", ar: "قصر العلم وقلعتا الميراني والجلالي" },
      { en: "Traditional Omani meal with kahwa and halwa", ar: "وجبة عُمانية تقليدية مع القهوة والحلوى" },
      { en: "Private 4WD with a licensed Omani guide", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني مرخّص" },
    ],
    itinerary: [
      { time: "08:00", title: { en: "Hotel pickup", ar: "الاستلام من الفندق" }, body: { en: "Your guide meets you in the lobby with cold water and a plan for the morning.", ar: "يلتقيك مرشدك في بهو الفندق مع الماء البارد وخطة الصباح." } },
      { time: "08:30", title: { en: "Sultan Qaboos Grand Mosque", ar: "جامع السلطان قابوس الأكبر" }, body: { en: "One hour inside the prayer hall and gardens (open to visitors Sat–Thu 8:00–11:00).", ar: "ساعة داخل قاعة الصلاة والحدائق (مفتوح للزوار السبت–الخميس 8:00–11:00)." } },
      { time: "10:00", title: { en: "Mutrah Corniche & Souq", ar: "كورنيش مطرح والسوق" }, body: { en: "Frankincense, silver and textiles in the oldest market in Muscat.", ar: "اللبان والفضة والمنسوجات في أقدم أسواق مسقط." } },
      { time: "11:15", title: { en: "Old Muscat", ar: "مسقط القديمة" }, body: { en: "Photo stops at Al Alam Palace and the harbour forts; optional Bait Al Zubair museum.", ar: "توقّف للتصوير عند قصر العلم وقلاع الميناء؛ متحف بيت الزبير اختياري." } },
      { time: "12:15", title: { en: "Traditional Omani lunch", ar: "غداء عُماني تقليدي" }, body: { en: "A relaxed meal at a local restaurant, then return to your hotel by about 13:00.", ar: "وجبة هادئة في مطعم محلي، ثم العودة إلى الفندق نحو الساعة 13:00." } },
    ],
    inclusions: [
      { en: "Private air-conditioned 4WD vehicle", ar: "سيارة دفع رباعي خاصة مكيّفة" },
      { en: "Licensed English/Arabic-speaking Omani guide", ar: "مرشد عُماني مرخّص يتحدث الإنجليزية والعربية" },
      { en: "Hotel pickup and drop-off in Muscat", ar: "الاستلام والتوصيل من وإلى الفندق في مسقط" },
      { en: "Traditional Omani meal, coffee and dates", ar: "وجبة عُمانية تقليدية مع القهوة والتمر" },
      { en: "Bottled water", ar: "مياه معبأة" },
      { en: "All entrance fees", ar: "جميع رسوم الدخول" },
    ],
    exclusions: commonExclusions,
    faqs: commonFaqs(24),
    category: "city_tours",
    secondaryCategories: ["food_family", "cultural"],
    destinations: ["muscat"],
    durationLabel: { en: "4–5 hours", ar: "4–5 ساعات" },
    durationMinutes: 270,
    durationDays: 1,
    startTimes: ["08:00", "14:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 3,
    difficulty: "easy",
    pricingModel: "per_group",
    priceGroupOmr: 88,
    usdReference: 230,
    depositPercent: 100,
    freeCancellationHours: 24,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 23,
    image: "muscat",
    isFeatured: true,
    featuredOrder: 1,
    tags: ["bestseller", "food", "mosque", "souq"],
    meetingPoint: { label: { en: "Your hotel in Muscat", ar: "فندقك في مسقط" }, lat: 23.588, lng: 58.3829 },
  },
  {
    code: "OCT-002",
    kind: "tour",
    title: {
      en: "Private Wadi Shab Hike & Swim Adventure with Bimmah Sinkhole",
      ar: "مغامرة وادي شاب الخاصة: مشي وسباحة مع حفرة بمة",
    },
    slug: { en: "wadi-shab-bimmah-sinkhole-private", ar: "وادي-شاب-وحفرة-بمة" },
    summary: {
      en: "Boat across, hike the canyon, swim turquoise pools and slip through the keyhole into a waterfall cave — plus the Bimmah Sinkhole.",
      ar: "عبور بالقارب، مشي في الوادي، سباحة في البرك الفيروزية، والمرور عبر الفتحة الضيقة إلى كهف الشلال؛ مع حفرة بمة.",
    },
    description: {
      en: "Wadi Shab is the wadi that appears on every Oman postcard, and this private day makes the most of it. After an early pickup we drive the coastal highway south, stopping first at the Bimmah Sinkhole — a limestone crater filled with clear blue-green water where you can take a first dip. At Wadi Shab a small boat carries us across the mouth of the wadi and the walk begins: 45 minutes along terraced plantations and boulder paths, with your guide pointing out the falaj channels and the best photo angles. The reward is a chain of three emerald pools; swim through them and, if you are comfortable, through a narrow gap in the rock into a hidden cave with a waterfall inside. We picnic in the shade before an easy return and stop for fresh juice on the way back to Muscat.",
      ar: "وادي شاب هو الوادي الذي يظهر على كل بطاقة بريدية من عُمان، وهذا اليوم الخاص يستثمره على أكمل وجه. بعد استلام مبكر نسلك الطريق الساحلي جنوبًا، ونتوقف أولًا عند حفرة بمة؛ فوهة جيرية مليئة بمياه زرقاء مخضرّة صافية يمكنك السباحة فيها. وفي وادي شاب يعبر بنا قارب صغير فوهة الوادي ليبدأ المسار: 45 دقيقة بين المزارع المدرّجة والصخور، بينما يشير مرشدك إلى قنوات الأفلاج وأفضل زوايا التصوير. المكافأة سلسلة من ثلاث برك زمردية؛ اسبح عبرها، وإن كنت مرتاحًا، مرّ عبر فجوة ضيقة في الصخر إلى كهف مخفي بداخله شلال. نتناول وجبة خفيفة في الظل قبل عودة سهلة مع توقف لعصير طازج في طريق العودة إلى مسقط.",
    },
    highlights: [
      { en: "Swim in the Bimmah Sinkhole", ar: "السباحة في حفرة بمة" },
      { en: "Boat crossing and guided canyon hike", ar: "عبور بالقارب ومسار جبلي بإرشاد" },
      { en: "Three turquoise pools and the waterfall cave", ar: "ثلاث برك فيروزية وكهف الشلال" },
      { en: "Picnic lunch and fresh juice stop", ar: "غداء خفيف وتوقف لعصير طازج" },
      { en: "Private 4WD and Omani guide", ar: "سيارة دفع رباعي خاصة ومرشد عُماني" },
    ],
    itinerary: [
      { time: "07:30", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "Scenic drive along the Gulf of Oman coast (about 1 h 30).", ar: "رحلة خلابة على ساحل خليج عُمان (نحو ساعة ونصف)." } },
      { time: "09:00", title: { en: "Bimmah Sinkhole", ar: "حفرة بمة" }, body: { en: "Swim in Hawiyat Najm park's crystal-clear sinkhole.", ar: "سباحة في حفرة هوية نجم الصافية." } },
      { time: "10:00", title: { en: "Wadi Shab hike & swim", ar: "مشي وسباحة في وادي شاب" }, body: { en: "Boat crossing, 45-minute hike, swimming through the pools to the cave.", ar: "عبور بالقارب، مسار 45 دقيقة، وسباحة عبر البرك إلى الكهف." } },
      { time: "13:00", title: { en: "Picnic lunch", ar: "غداء خفيف" }, body: { en: "Sandwiches, fruit and water in the shade of the wadi.", ar: "شطائر وفواكه وماء في ظل الوادي." } },
      { time: "14:30", title: { en: "Return to Muscat", ar: "العودة إلى مسقط" }, body: { en: "Optional stop at Fins white beach; hotel drop-off around 16:00.", ar: "توقف اختياري في شاطئ فنس الأبيض؛ التوصيل إلى الفندق نحو 16:00." } },
    ],
    inclusions: [
      { en: "Private 4WD with Omani driver-guide", ar: "سيارة دفع رباعي خاصة مع سائق مرشد عُماني" },
      { en: "Hotel pickup and drop-off", ar: "الاستلام والتوصيل من وإلى الفندق" },
      { en: "Boat crossing fee", ar: "رسوم عبور القارب" },
      { en: "Picnic lunch, snacks and bottled water", ar: "غداء خفيف ووجبات خفيفة ومياه معبأة" },
      { en: "Dry bag for your belongings", ar: "حقيبة مقاومة للماء لأغراضك" },
    ],
    exclusions: [{ en: "Water shoes (recommended; can be rented on site)", ar: "أحذية مائية (يُنصح بها؛ متوفرة للإيجار في الموقع)" }, ...commonExclusions],
    faqs: [
      {
        question: { en: "Do I need to be a strong swimmer?", ar: "هل يجب أن أكون سبّاحًا ماهرًا؟" },
        answer: { en: "You should be comfortable swimming about 50 m in calm water to reach the cave. Life jackets are available, and the hike and first pools can be enjoyed without swimming.", ar: "يجب أن تكون مرتاحًا للسباحة نحو 50 مترًا في مياه هادئة للوصول إلى الكهف. تتوفر سترات النجاة، ويمكن الاستمتاع بالمسار والبرك الأولى دون سباحة." },
      },
      ...commonFaqs(24),
    ],
    category: "mountain_wadi",
    secondaryCategories: ["day_trips", "hiking_camping"],
    destinations: ["wadi_shab", "sur"],
    durationLabel: { en: "6+ hours", ar: "أكثر من 6 ساعات" },
    durationMinutes: 480,
    durationDays: 1,
    startTimes: ["07:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 69,
    priceChildOmr: 35,
    childAgeMax: 11,
    usdReference: 179,
    depositPercent: 100,
    freeCancellationHours: 24,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 7,
    image: "wadi-shab",
    isFeatured: true,
    featuredOrder: 2,
    tags: ["swimming", "hiking", "nature", "bestseller"],
    meetingPoint: { label: { en: "Your hotel in Muscat", ar: "فندقك في مسقط" } },
  },
  {
    code: "OCT-003",
    kind: "tour",
    title: {
      en: "Private Wahiba Sands & Wadi Bani Khalid 4x4 Adventure",
      ar: "مغامرة رمال وهيبة ووادي بني خالد بالدفع الرباعي",
    },
    slug: { en: "wahiba-sands-wadi-bani-khalid-4x4", ar: "رمال-وهيبة-ووادي-بني-خالد" },
    summary: {
      en: "Emerald pools in Wadi Bani Khalid, then dune bashing, camel encounters and sunset over the red dunes of Wahiba Sands.",
      ar: "برك زمردية في وادي بني خالد، ثم تسلّق الكثبان ولقاء الإبل وغروب الشمس فوق رمال وهيبة الحمراء.",
    },
    description: {
      en: "Two of Oman's most contrasting landscapes in one private day. We leave Muscat early and cross the Hajar foothills to Wadi Bani Khalid, where spring-fed pools stay a deep, swimmable green all year round; there is time for a swim and a walk to the upper pools. After lunch the tarmac ends and your driver deflates the tyres for Wahiba (Sharqiya) Sands. Expect exhilarating dune driving, a stop at a Bedouin family home for coffee and dates, a chance to meet their camels, and — if you wish — sandboarding down the slopes. We climb the highest dune for sunset, then drive back to Muscat under the stars.",
      ar: "اثنان من أكثر المناظر الطبيعية تباينًا في عُمان في يوم خاص واحد. نغادر مسقط مبكرًا ونعبر سفوح جبال الحجر إلى وادي بني خالد، حيث تبقى البرك المتدفقة من الينابيع خضراء عميقة وصالحة للسباحة على مدار العام؛ وهناك وقت للسباحة والمشي إلى البرك العليا. بعد الغداء ينتهي الأسفلت ويخفّض سائقك ضغط الإطارات استعدادًا لرمال وهيبة (الشرقية). توقّع قيادة مثيرة على الكثبان، وتوقفًا عند بيت عائلة بدوية لتناول القهوة والتمر، وفرصة للقاء الإبل، وإن رغبت، التزلج على الرمال. نصعد أعلى كثيب لمشاهدة الغروب، ثم نعود إلى مسقط تحت النجوم.",
    },
    highlights: [
      { en: "Swim in the emerald pools of Wadi Bani Khalid", ar: "السباحة في برك وادي بني خالد الزمردية" },
      { en: "Dune bashing in a private 4WD", ar: "قيادة على الكثبان بسيارة دفع رباعي خاصة" },
      { en: "Coffee and dates with a Bedouin family", ar: "قهوة وتمر مع عائلة بدوية" },
      { en: "Sandboarding and camel encounter", ar: "التزلج على الرمال ولقاء الإبل" },
      { en: "Sunset from the top of the dunes", ar: "غروب الشمس من قمة الكثبان" },
    ],
    itinerary: [
      { time: "07:00", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "Drive south-east via Ibra (about 2 h 30) with a coffee stop.", ar: "رحلة جنوب شرق عبر إبراء (نحو ساعتين ونصف) مع توقف للقهوة." } },
      { time: "09:45", title: { en: "Wadi Bani Khalid", ar: "وادي بني خالد" }, body: { en: "Swim and walk to the upper pools; lunch at a local restaurant.", ar: "سباحة ومشي إلى البرك العليا؛ غداء في مطعم محلي." } },
      { time: "13:30", title: { en: "Wahiba Sands", ar: "رمال وهيبة" }, body: { en: "Dune driving, Bedouin family visit, camels and sandboarding.", ar: "قيادة على الكثبان، زيارة عائلة بدوية، الإبل والتزلج على الرمال." } },
      { time: "17:15", title: { en: "Sunset on the dunes", ar: "الغروب فوق الكثبان" }, body: { en: "Tea on the highest dune as the sand turns red.", ar: "شاي على أعلى كثيب بينما تتحوّل الرمال إلى اللون الأحمر." } },
      { time: "18:00", title: { en: "Return to Muscat", ar: "العودة إلى مسقط" }, body: { en: "Hotel drop-off around 20:30.", ar: "التوصيل إلى الفندق نحو 20:30." } },
    ],
    inclusions: [
      { en: "Private 4WD with experienced desert driver-guide", ar: "سيارة دفع رباعي خاصة مع سائق مرشد خبير بالصحراء" },
      { en: "Hotel pickup and drop-off", ar: "الاستلام والتوصيل من وإلى الفندق" },
      { en: "Lunch, snacks and bottled water", ar: "غداء ووجبات خفيفة ومياه معبأة" },
      { en: "Bedouin coffee & dates hospitality", ar: "ضيافة بدوية بالقهوة والتمر" },
      { en: "Sandboard", ar: "لوح التزلج على الرمال" },
    ],
    exclusions: [{ en: "Camel ride (optional, payable locally)", ar: "ركوب الجمال (اختياري، يُدفع في الموقع)" }, ...commonExclusions],
    faqs: [
      {
        question: { en: "Can we stay overnight in the desert instead?", ar: "هل يمكننا المبيت في الصحراء بدلًا من العودة؟" },
        answer: { en: "Yes — ask us to extend the tour with a night in a Bedouin-style desert camp; we will quote it as a custom itinerary.", ar: "نعم؛ اطلب منا تمديد الجولة بليلة في مخيم صحراوي على الطراز البدوي وسنقدّم عرض سعر كبرنامج مخصّص." },
      },
      ...commonFaqs(24),
    ],
    category: "desert_4x4",
    secondaryCategories: ["day_trips", "mountain_wadi"],
    destinations: ["wahiba"],
    durationLabel: { en: "6+ hours", ar: "أكثر من 6 ساعات" },
    durationMinutes: 780,
    durationDays: 1,
    startTimes: ["07:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 72,
    priceChildOmr: 36,
    childAgeMax: 11,
    usdReference: 188,
    depositPercent: 100,
    freeCancellationHours: 24,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 4,
    image: "wahiba",
    isFeatured: true,
    featuredOrder: 3,
    tags: ["desert", "4x4", "sunset", "swimming"],
  },
  {
    code: "OCT-004",
    kind: "tour",
    title: {
      en: "Private Nizwa Fort, Souq & Jebel Akhdar 4WD Tour",
      ar: "جولة خاصة: قلعة نزوى والسوق والجبل الأخضر بالدفع الرباعي",
    },
    slug: { en: "nizwa-fort-souq-jebel-akhdar", ar: "قلعة-نزوى-والجبل-الأخضر" },
    summary: {
      en: "Oman's ancient capital and its 17th-century fort, then a 4WD climb to the rose terraces and cliff-edge villages of the Green Mountain.",
      ar: "عاصمة عُمان القديمة وقلعتها من القرن السابع عشر، ثم صعود بالدفع الرباعي إلى مدرجات الورد وقرى الجبل الأخضر المعلّقة.",
    },
    description: {
      en: "History in the morning, mountains in the afternoon. In Nizwa your guide walks you through the round tower of the fort — built to withstand cannon fire — and the souq famous for silverwork, pottery and, on Fridays, the livestock auction. We continue to the checkpoint at Birkat Al Mouz where only 4WDs may climb to Jebel Akhdar. On the Saiq Plateau, 2,000 m up, the air is cool and the terraces of Al Ayn and Wadi Bani Habib are layered with pomegranate, walnut and, in April, damask roses distilled into rosewater. Lunch is at a mountain restaurant with views across the canyon, and there is an easy walk between the abandoned mud villages before we descend to Muscat.",
      ar: "التاريخ في الصباح والجبال بعد الظهر. في نزوى يصطحبك مرشدك عبر البرج الدائري للقلعة، الذي بُني ليصمد أمام نيران المدافع، وعبر السوق الشهير بالمصنوعات الفضية والفخار، وفي أيام الجمعة بمزاد الماشية. نواصل إلى نقطة التفتيش في بركة الموز حيث لا يُسمح إلا لسيارات الدفع الرباعي بالصعود إلى الجبل الأخضر. وعلى هضبة سيق، على ارتفاع 2000 متر، يكون الهواء عليلًا وتتدرّج مدرجات العين ووادي بني حبيب بالرمان والجوز، وفي أبريل بالورد الدمشقي الذي يُقطّر ماء ورد. الغداء في مطعم جبلي بإطلالة على الأخدود، ثم مسار سهل بين القرى الطينية المهجورة قبل النزول إلى مسقط.",
    },
    highlights: [
      { en: "Nizwa Fort and its famous round tower", ar: "قلعة نزوى وبرجها الدائري الشهير" },
      { en: "Nizwa Souq (Friday goat market optional)", ar: "سوق نزوى (سوق الماشية يوم الجمعة اختياري)" },
      { en: "4WD ascent to the Saiq Plateau (2,000 m)", ar: "الصعود بالدفع الرباعي إلى هضبة سيق (2000 م)" },
      { en: "Rose terraces and abandoned villages of Wadi Bani Habib", ar: "مدرجات الورد وقرى وادي بني حبيب المهجورة" },
      { en: "Lunch with canyon views", ar: "غداء بإطلالة على الأخدود" },
    ],
    itinerary: [
      { time: "07:30", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "Drive inland along the Hajar range (about 1 h 45).", ar: "رحلة داخلية بمحاذاة سلسلة جبال الحجر (نحو ساعة و45 دقيقة)." } },
      { time: "09:15", title: { en: "Nizwa Fort & Souq", ar: "قلعة نزوى والسوق" }, body: { en: "Guided visit to the fort, then free time in the souq.", ar: "زيارة بإرشاد للقلعة ثم وقت حر في السوق." } },
      { time: "11:30", title: { en: "Birkat Al Mouz & ascent", ar: "بركة الموز والصعود" }, body: { en: "Falaj-fed plantations, then the switchbacks up to Jebel Akhdar.", ar: "مزارع تسقيها الأفلاج، ثم المنعطفات صعودًا إلى الجبل الأخضر." } },
      { time: "13:00", title: { en: "Lunch on the plateau", ar: "الغداء على الهضبة" }, body: { en: "Mountain restaurant with canyon views.", ar: "مطعم جبلي بإطلالة على الأخدود." } },
      { time: "14:00", title: { en: "Terraces & villages walk", ar: "مسار المدرجات والقرى" }, body: { en: "Al Ayn, Al Aqr and Wadi Bani Habib; Diana's Point viewpoint.", ar: "العين والعقر ووادي بني حبيب؛ نقطة ديانا للمشاهدة." } },
      { time: "16:00", title: { en: "Return to Muscat", ar: "العودة إلى مسقط" }, body: { en: "Hotel drop-off around 18:30.", ar: "التوصيل إلى الفندق نحو 18:30." } },
    ],
    inclusions: [
      { en: "Private 4WD with licensed Omani guide", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني مرخّص" },
      { en: "Hotel pickup and drop-off", ar: "الاستلام والتوصيل من وإلى الفندق" },
      { en: "Nizwa Fort entrance fee", ar: "رسوم دخول قلعة نزوى" },
      { en: "Lunch and bottled water", ar: "غداء ومياه معبأة" },
    ],
    exclusions: commonExclusions,
    faqs: [
      {
        question: { en: "When do the roses bloom?", ar: "متى يتفتّح الورد؟" },
        answer: { en: "The damask rose season runs from late March to mid-April. The terraces are beautiful year-round, and pomegranates ripen in September.", ar: "موسم الورد الدمشقي من أواخر مارس إلى منتصف أبريل. المدرجات جميلة على مدار العام، وينضج الرمان في سبتمبر." },
      },
      ...commonFaqs(24),
    ],
    category: "cultural",
    secondaryCategories: ["mountain_wadi", "day_trips"],
    destinations: ["nizwa", "jebel_akhdar"],
    durationLabel: { en: "6+ hours", ar: "أكثر من 6 ساعات" },
    durationMinutes: 660,
    durationDays: 1,
    startTimes: ["07:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 76,
    priceChildOmr: 38,
    childAgeMax: 11,
    usdReference: 197,
    depositPercent: 100,
    freeCancellationHours: 24,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 3,
    image: "nizwa",
    isFeatured: true,
    featuredOrder: 4,
    tags: ["heritage", "fort", "mountains", "unesco"],
  },
  {
    code: "OCT-005",
    kind: "service",
    title: {
      en: "Transfer: Muscat Airport ⇄ Jabal Akhdar (Alila, Anantara hotels)",
      ar: "نقل: مطار مسقط ⇄ الجبل الأخضر (فنادق أليلا وأنانتارا)",
    },
    slug: { en: "transfer-muscat-airport-jabal-akhdar", ar: "نقل-مطار-مسقط-الجبل-الأخضر" },
    summary: {
      en: "Door-to-door private 4WD transfer between Muscat International Airport (or any Muscat hotel) and the Jabal Akhdar resorts.",
      ar: "نقل خاص من الباب إلى الباب بسيارة دفع رباعي بين مطار مسقط الدولي (أو أي فندق في مسقط) ومنتجعات الجبل الأخضر.",
    },
    description: {
      en: "The road to Jabal Akhdar is one of the most scenic in Oman — and it is closed to anything but 4WD vehicles. Our professional Omani drivers meet you in the arrivals hall with a name board, help with luggage and drive you in a modern, air-conditioned 4WD to the Alila Jabal Akhdar, Anantara Al Jabal Al Akhdar, Sahab or any other mountain resort. Flight tracking means we adjust to delays at no extra charge. The price is per vehicle (up to 4 passengers with luggage); larger groups travel in a second vehicle or minibus.",
      ar: "الطريق إلى الجبل الأخضر من أجمل الطرق في عُمان، وهو مغلق أمام أي مركبة غير الدفع الرباعي. يستقبلك سائقونا العُمانيون المحترفون في صالة الوصول بلوحة تحمل اسمك، ويساعدونك في الأمتعة، وينقلونك بسيارة دفع رباعي حديثة ومكيّفة إلى أليلا الجبل الأخضر أو أنانتارا الجبل الأخضر أو سحاب أو أي منتجع جبلي آخر. نتابع حالة الرحلة الجوية ونتكيّف مع التأخيرات دون رسوم إضافية. السعر لكل مركبة (حتى 4 ركاب مع الأمتعة)؛ وتسافر المجموعات الأكبر في مركبة ثانية أو حافلة صغيرة.",
    },
    highlights: [
      { en: "Meet & greet at arrivals with name board", ar: "استقبال في صالة الوصول بلوحة اسم" },
      { en: "Modern private 4WD, up to 4 passengers", ar: "سيارة دفع رباعي خاصة حديثة تتسع لأربعة ركاب" },
      { en: "Flight tracking and free waiting time", ar: "متابعة الرحلة الجوية ووقت انتظار مجاني" },
      { en: "Scenic stop at Birkat Al Mouz on request", ar: "توقف خلاب في بركة الموز عند الطلب" },
    ],
    itinerary: [
      { title: { en: "Pickup", ar: "الاستلام" }, body: { en: "Airport arrivals hall or your Muscat hotel lobby.", ar: "صالة الوصول في المطار أو بهو فندقك في مسقط." } },
      { title: { en: "Drive", ar: "الرحلة" }, body: { en: "About 2 h 15 via Nizwa road and the Jabal Akhdar checkpoint; comfort stops on request.", ar: "نحو ساعتين و15 دقيقة عبر طريق نزوى ونقطة تفتيش الجبل الأخضر؛ توقفات للراحة عند الطلب." } },
      { title: { en: "Drop-off", ar: "التوصيل" }, body: { en: "At your resort reception.", ar: "عند استقبال المنتجع." } },
    ],
    inclusions: [
      { en: "Private 4WD vehicle with professional Omani driver", ar: "سيارة دفع رباعي خاصة مع سائق عُماني محترف" },
      { en: "Fuel, tolls and parking", ar: "الوقود والرسوم ومواقف السيارات" },
      { en: "Bottled water", ar: "مياه معبأة" },
      { en: "60 minutes free waiting at the airport", ar: "60 دقيقة انتظار مجاني في المطار" },
    ],
    exclusions: [{ en: "Sightseeing stops longer than 20 minutes (bookable as a tour)", ar: "توقفات سياحية تتجاوز 20 دقيقة (يمكن حجزها كجولة)" }, ...commonExclusions],
    faqs: [
      {
        question: { en: "Can you do the return transfer too?", ar: "هل يمكنكم تنفيذ رحلة العودة أيضًا؟" },
        answer: { en: "Yes. Book two one-way transfers or ask us for a round-trip quote; we can also add a Nizwa stop on the way down.", ar: "نعم. احجز رحلتين باتجاه واحد أو اطلب عرض سعر ذهابًا وإيابًا؛ ويمكننا أيضًا إضافة توقف في نزوى في طريق النزول." },
      },
      ...commonFaqs(24),
    ],
    category: "transfers",
    destinations: ["muscat", "jebel_akhdar"],
    durationLabel: { en: "2–3 hours", ar: "2–3 ساعات" },
    durationMinutes: 150,
    durationDays: 1,
    startTimes: ["06:00", "09:00", "12:00", "15:00", "18:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 4,
    capacityPerSlot: 4,
    pricingModel: "per_group",
    priceGroupOmr: 115,
    usdReference: 300,
    depositPercent: 100,
    freeCancellationHours: 24,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "jebel-akhdar",
    isFeatured: false,
    tags: ["transfer", "airport", "4x4"],
    meetingPoint: { label: { en: "Muscat International Airport – Arrivals", ar: "مطار مسقط الدولي – صالة الوصول" }, lat: 23.5933, lng: 58.2844 },
  },
  {
    code: "OCT-006",
    kind: "tour",
    title: { en: "Traditional Dinner with an Omani Family", ar: "عشاء تقليدي مع عائلة عُمانية" },
    slug: { en: "traditional-omani-family-dinner", ar: "عشاء-تقليدي-مع-عائلة-عمانية" },
    summary: {
      en: "An evening in an Omani home: kahwa and dates on the majlis floor, a home-cooked feast, and conversation about life in the Sultanate.",
      ar: "أمسية في بيت عُماني: قهوة وتمر في المجلس، وليمة منزلية، وحديث عن الحياة في السلطنة.",
    },
    description: {
      en: "Hospitality is at the heart of Omani culture, and there is no better way to experience it than as a guest in a family home. Your guide collects you in the early evening and introduces you to a family in a village near Muscat. You are welcomed in the majlis with Omani coffee, dates and halwa, then invited to share a dinner cooked in the family kitchen — dishes like shuwa (marinated lamb slow-cooked underground), mashuai, harees and fresh rukhal bread, followed by fruit and sweet tea. Your host will happily talk about traditions, dress, weddings and daily life, and your guide translates where needed. Dress modestly; shoes are removed at the door.",
      ar: "الضيافة في قلب الثقافة العُمانية، وليس هناك طريقة أفضل لتجربتها من أن تكون ضيفًا في بيت عائلة. يصطحبك مرشدك في المساء الباكر ويعرّفك على عائلة في قرية قريبة من مسقط. تُستقبل في المجلس بالقهوة العُمانية والتمر والحلوى، ثم تُدعى لمشاركة عشاء طُهي في مطبخ العائلة؛ أطباق مثل الشواء (لحم متبّل يُطهى ببطء تحت الأرض) والمشوي والهريس وخبز الرخال الطازج، تليها الفواكه والشاي. يسعد مضيفك بالحديث عن التقاليد واللباس والأعراس والحياة اليومية، ويترجم مرشدك عند الحاجة. يُرجى ارتداء ملابس محتشمة؛ وتُخلع الأحذية عند الباب.",
    },
    highlights: [
      { en: "Welcome in a real family majlis", ar: "استقبال في مجلس عائلي حقيقي" },
      { en: "Home-cooked Omani feast (shuwa, harees, rukhal bread)", ar: "وليمة عُمانية منزلية (شواء، هريس، خبز رخال)" },
      { en: "Omani coffee, dates and halwa ritual", ar: "طقوس القهوة العُمانية والتمر والحلوى" },
      { en: "Conversation about traditions and daily life", ar: "حديث عن التقاليد والحياة اليومية" },
    ],
    itinerary: [
      { time: "18:00", title: { en: "Pickup", ar: "الاستلام" }, body: { en: "From your Muscat hotel; short drive to the family village.", ar: "من فندقك في مسقط؛ رحلة قصيرة إلى قرية العائلة." } },
      { time: "18:45", title: { en: "Majlis welcome", ar: "الاستقبال في المجلس" }, body: { en: "Kahwa, dates and halwa; introduction to the family.", ar: "قهوة وتمر وحلوى؛ التعرّف على العائلة." } },
      { time: "19:30", title: { en: "Dinner", ar: "العشاء" }, body: { en: "Traditional dishes served on the floor mat, Omani style.", ar: "أطباق تقليدية تُقدَّم على السفرة الأرضية على الطريقة العُمانية." } },
      { time: "21:00", title: { en: "Return", ar: "العودة" }, body: { en: "Drop-off at your hotel by about 21:30.", ar: "التوصيل إلى الفندق نحو 21:30." } },
    ],
    inclusions: [
      { en: "Private transport with Omani guide", ar: "نقل خاص مع مرشد عُماني" },
      { en: "Full dinner, coffee, dates, halwa and soft drinks", ar: "عشاء كامل مع القهوة والتمر والحلوى والمشروبات الغازية" },
    ],
    exclusions: commonExclusions,
    faqs: [
      {
        question: { en: "Can dietary requirements be accommodated?", ar: "هل يمكن مراعاة المتطلبات الغذائية؟" },
        answer: { en: "Yes — vegetarian, vegan and allergy-aware menus are available with 24 hours' notice.", ar: "نعم؛ تتوفر قوائم نباتية وخالية من مسببات الحساسية بإشعار مسبق قبل 24 ساعة." },
      },
      ...commonFaqs(24),
    ],
    category: "food_family",
    secondaryCategories: ["cultural"],
    destinations: ["muscat"],
    durationLabel: { en: "Evening (3–4 hours)", ar: "مسائية (3–4 ساعات)" },
    durationMinutes: 210,
    durationDays: 1,
    startTimes: ["18:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 8,
    capacityPerSlot: 8,
    difficulty: "easy",
    pricingModel: "per_group",
    priceGroupOmr: 45,
    priceIsPlaceholder: true,
    depositPercent: 100,
    freeCancellationHours: 24,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 0,
    image: "dinner",
    isFeatured: true,
    featuredOrder: 5,
    tags: ["food", "family", "evening", "culture"],
  },
  {
    code: "OCT-007",
    kind: "tour",
    title: { en: "2-Day Jabal Akhdar Mountain Overnight Experience", ar: "تجربة الجبل الأخضر ليومين مع مبيت" },
    slug: { en: "jabal-akhdar-2-day-overnight", ar: "الجبل-الأخضر-يومان" },
    summary: {
      en: "Nizwa's fort and souq, a night at a mountain resort 2,000 m up, and a sunrise walk through rose terraces and abandoned villages.",
      ar: "قلعة نزوى وسوقها، ليلة في منتجع جبلي على ارتفاع 2000 متر، ومسار عند الشروق عبر مدرجات الورد والقرى المهجورة.",
    },
    description: {
      en: "Give the Green Mountain the time it deserves. Day one follows our classic route through Nizwa Fort and souq before climbing to the Saiq Plateau, where you check in to a mountain hotel and watch the sunset paint the canyon. Day two begins with a sunrise walk along the village trail from Al Aqr to Al Ayn, breakfast with a view, and a visit to a rosewater distillery (in season) or the Wadi Bani Habib walnut groves. On the way down we stop at Birkat Al Mouz and the 400-year-old Bait Al Redaidah castle before returning to Muscat in the afternoon. Hotel category (3★ to 5★, including Alila and Anantara) is chosen at booking.",
      ar: "امنح الجبل الأخضر الوقت الذي يستحقه. يتبع اليوم الأول مسارنا الكلاسيكي عبر قلعة نزوى وسوقها قبل الصعود إلى هضبة سيق، حيث تسجّل الوصول في فندق جبلي وتشاهد الغروب وهو يلوّن الأخدود. يبدأ اليوم الثاني بمسار عند الشروق على درب القرى من العقر إلى العين، وإفطار بإطلالة، وزيارة لمعمل تقطير ماء الورد (في الموسم) أو بساتين الجوز في وادي بني حبيب. وفي طريق النزول نتوقف عند بركة الموز وحصن بيت الرديدة الذي يعود عمره إلى 400 عام قبل العودة إلى مسقط بعد الظهر. تُختار فئة الفندق (من 3 إلى 5 نجوم، بما فيها أليلا وأنانتارا) عند الحجز.",
    },
    highlights: [
      { en: "Nizwa Fort and souq with a local guide", ar: "قلعة نزوى والسوق مع مرشد محلي" },
      { en: "Overnight at a Jabal Akhdar mountain resort", ar: "مبيت في منتجع جبلي في الجبل الأخضر" },
      { en: "Sunset and sunrise over the canyon", ar: "الغروب والشروق فوق الأخدود" },
      { en: "Village trail walk and rose terraces", ar: "مسار القرى ومدرجات الورد" },
      { en: "Bait Al Redaidah castle and Birkat Al Mouz", ar: "حصن بيت الرديدة وبركة الموز" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Muscat → Nizwa → Jabal Akhdar", ar: "مسقط ← نزوى ← الجبل الأخضر" }, body: { en: "Pickup 08:00. Nizwa Fort and souq, lunch, 4WD ascent, hotel check-in, sunset at Diana's Point. Dinner at the hotel.", ar: "الاستلام 08:00. قلعة نزوى والسوق، الغداء، الصعود بالدفع الرباعي، تسجيل الوصول، الغروب عند نقطة ديانا. العشاء في الفندق." } },
      { time: "Day 2", title: { en: "Sunrise walk → Muscat", ar: "مسار الشروق ← مسقط" }, body: { en: "Village trail Al Aqr–Al Ayn, breakfast, rosewater distillery or walnut groves, Bait Al Redaidah, return to Muscat by about 16:00.", ar: "درب القرى من العقر إلى العين، الإفطار، معمل ماء الورد أو بساتين الجوز، بيت الرديدة، العودة إلى مسقط نحو 16:00." } },
    ],
    inclusions: [
      { en: "Private 4WD with licensed Omani guide for both days", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني مرخّص لليومين" },
      { en: "One night at a mountain hotel with breakfast (category of your choice)", ar: "ليلة واحدة في فندق جبلي مع الإفطار (الفئة من اختيارك)" },
      { en: "Lunch on day 1, bottled water", ar: "غداء اليوم الأول ومياه معبأة" },
      { en: "All entrance fees", ar: "جميع رسوم الدخول" },
    ],
    exclusions: [{ en: "Dinner on day 1 and lunch on day 2", ar: "عشاء اليوم الأول وغداء اليوم الثاني" }, ...commonExclusions],
    faqs: [
      {
        question: { en: "Which hotels can we choose from?", ar: "ما الفنادق التي يمكننا الاختيار منها؟" },
        answer: { en: "Sahab Resort (4★), Jabal Akhdar Hotel (3★), dusitD2 Naseem (4★), Anantara Al Jabal Al Akhdar (5★) and Alila Jabal Akhdar (5★). Prices shown are based on the 4★ option; we confirm the supplement for 5★ before payment.", ar: "منتجع سحاب (4 نجوم)، فندق الجبل الأخضر (3 نجوم)، دوسيت دي2 نسيم (4 نجوم)، أنانتارا الجبل الأخضر (5 نجوم) وأليلا الجبل الأخضر (5 نجوم). الأسعار المعروضة مبنية على خيار 4 نجوم؛ ونؤكد فرق السعر لفئة 5 نجوم قبل الدفع." },
      },
      ...commonFaqs(72),
    ],
    category: "multi_day",
    secondaryCategories: ["mountain_wadi", "cultural"],
    destinations: ["nizwa", "jebel_akhdar"],
    durationLabel: { en: "2 days / 1 night", ar: "يومان / ليلة واحدة" },
    durationMinutes: 1920,
    durationDays: 2,
    startTimes: ["08:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 185,
    priceChildOmr: 95,
    childAgeMax: 11,
    priceIsPlaceholder: true,
    depositPercent: 30,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 0,
    image: "jebel-akhdar",
    isFeatured: true,
    featuredOrder: 6,
    tags: ["overnight", "mountains", "luxury"],
  },
  {
    code: "OCT-008",
    kind: "tour",
    title: { en: "3-Day Oman Nature & Culture Experience", ar: "تجربة عُمان الطبيعة والثقافة في 3 أيام" },
    slug: { en: "oman-nature-culture-3-day", ar: "عمان-3-أيام-طبيعة-وثقافة" },
    summary: {
      en: "Muscat, Nizwa and Jabal Akhdar, then Wahiba Sands and Wadi Bani Khalid — the classic Oman loop in three private days.",
      ar: "مسقط ونزوى والجبل الأخضر، ثم رمال وهيبة ووادي بني خالد؛ الحلقة العُمانية الكلاسيكية في ثلاثة أيام خاصة.",
    },
    description: {
      en: "Three days is enough to see why travellers fall for Oman. We start in the capital with the Grand Mosque and Mutrah, then head inland to Nizwa and the cool heights of Jabal Akhdar for the first night. Day two crosses to the Sharqiya region: a swim at Wadi Bani Khalid, then dune driving into Wahiba Sands for sunset, dinner and a night in a comfortable desert camp under a sky full of stars. On the final day we follow the coast back north via the dhow yards of Sur, Wadi Shab (optional hike and swim) and the Bimmah Sinkhole before returning to Muscat. One vehicle, one guide, your pace throughout.",
      ar: "ثلاثة أيام كافية لتعرف لماذا يقع المسافرون في حب عُمان. نبدأ في العاصمة بالجامع الأكبر ومطرح، ثم نتجه إلى الداخل نحو نزوى ومرتفعات الجبل الأخضر الباردة لقضاء الليلة الأولى. في اليوم الثاني نعبر إلى منطقة الشرقية: سباحة في وادي بني خالد، ثم قيادة على الكثبان في رمال وهيبة لمشاهدة الغروب والعشاء والمبيت في مخيم صحراوي مريح تحت سماء مليئة بالنجوم. وفي اليوم الأخير نتبع الساحل شمالًا عبر أحواض بناء السفن في صور، ووادي شاب (مشي وسباحة اختياريان)، وحفرة بمة قبل العودة إلى مسقط. سيارة واحدة ومرشد واحد ووتيرتك الخاصة طوال الرحلة.",
    },
    highlights: [
      { en: "Grand Mosque, Mutrah Souq and Old Muscat", ar: "الجامع الأكبر وسوق مطرح ومسقط القديمة" },
      { en: "Nizwa Fort and a night on Jabal Akhdar", ar: "قلعة نزوى وليلة في الجبل الأخضر" },
      { en: "Wadi Bani Khalid swim and Wahiba Sands desert camp", ar: "سباحة في وادي بني خالد ومخيم صحراوي في رمال وهيبة" },
      { en: "Sur dhow yard, Wadi Shab and Bimmah Sinkhole", ar: "حوض سفن صور ووادي شاب وحفرة بمة" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Muscat → Nizwa → Jabal Akhdar", ar: "مسقط ← نزوى ← الجبل الأخضر" }, body: { en: "Grand Mosque, Mutrah, drive to Nizwa Fort and souq, ascent to the plateau. Overnight mountain hotel.", ar: "الجامع الأكبر، مطرح، الانتقال إلى قلعة نزوى والسوق، الصعود إلى الهضبة. المبيت في فندق جبلي." } },
      { time: "Day 2", title: { en: "Jabal Akhdar → Wadi Bani Khalid → Wahiba Sands", ar: "الجبل الأخضر ← وادي بني خالد ← رمال وهيبة" }, body: { en: "Sunrise walk, descent, swim in the wadi, dune bashing, sunset, dinner and overnight in a desert camp.", ar: "مسار الشروق، النزول، سباحة في الوادي، قيادة على الكثبان، الغروب، العشاء والمبيت في مخيم صحراوي." } },
      { time: "Day 3", title: { en: "Wahiba → Sur → Wadi Shab → Muscat", ar: "وهيبة ← صور ← وادي شاب ← مسقط" }, body: { en: "Desert sunrise, Sur dhow yard, Wadi Shab hike and swim, Bimmah Sinkhole, return to Muscat by evening.", ar: "شروق الصحراء، حوض سفن صور، مشي وسباحة في وادي شاب، حفرة بمة، العودة إلى مسقط مساءً." } },
    ],
    inclusions: [
      { en: "Private 4WD with licensed Omani guide for 3 days", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني مرخّص لمدة 3 أيام" },
      { en: "1 night mountain hotel + 1 night desert camp, with breakfast", ar: "ليلة في فندق جبلي وليلة في مخيم صحراوي مع الإفطار" },
      { en: "Dinner in the desert camp", ar: "العشاء في المخيم الصحراوي" },
      { en: "All entrance fees and boat crossing at Wadi Shab", ar: "جميع رسوم الدخول وعبور القارب في وادي شاب" },
      { en: "Bottled water throughout", ar: "مياه معبأة طوال الرحلة" },
    ],
    exclusions: [{ en: "Lunches and dinner on day 1", ar: "وجبات الغداء وعشاء اليوم الأول" }, ...commonExclusions],
    faqs: commonFaqs(72),
    category: "multi_day",
    secondaryCategories: ["desert_4x4", "cultural"],
    destinations: ["muscat", "nizwa", "jebel_akhdar", "wahiba", "sur", "wadi_shab"],
    durationLabel: { en: "3 days / 2 nights", ar: "3 أيام / ليلتان" },
    durationMinutes: 4320,
    durationDays: 3,
    startTimes: ["08:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 295,
    priceChildOmr: 150,
    childAgeMax: 11,
    priceIsPlaceholder: true,
    depositPercent: 30,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 0,
    image: "wahiba",
    isFeatured: false,
    tags: ["multi-day", "desert", "mountains", "wadi"],
  },
  {
    code: "OCT-009",
    kind: "tour",
    title: { en: "6-Day Oman Nature, Culture & Traditions Group Trip", ar: "رحلة جماعية 6 أيام: طبيعة عُمان وثقافتها وتقاليدها" },
    slug: { en: "oman-nature-culture-traditions-6-day", ar: "عمان-6-أيام-جولة-جماعية" },
    summary: {
      en: "A small-group journey through Muscat, the Hajar Mountains, the desert, the turtle beaches of Ras Al Jinz and the wadis of the east.",
      ar: "رحلة لمجموعة صغيرة عبر مسقط وجبال الحجر والصحراء وشواطئ السلاحف في رأس الجنز وأودية الشرق.",
    },
    description: {
      en: "Our six-day group trip is designed for travellers who want depth without the price of a fully private itinerary — groups are capped at 12 guests in comfortable 4WDs and a small bus. We combine the highlights (Grand Mosque, Nizwa, Jabal Akhdar, Wahiba Sands, Wadi Shab) with slower moments: a cooking demonstration in a village kitchen, a frankincense talk in the souq, a night watching green turtles nest at Ras Al Jinz, and a boat trip to spot dolphins off the Muscat coast. Fixed departure dates are published each season; private departures are available on request.",
      ar: "صُمِّمت رحلتنا الجماعية لستة أيام للمسافرين الراغبين في العمق دون تكلفة برنامج خاص بالكامل؛ تقتصر المجموعات على 12 ضيفًا في سيارات دفع رباعي مريحة وحافلة صغيرة. نجمع بين المعالم البارزة (الجامع الأكبر، نزوى، الجبل الأخضر، رمال وهيبة، وادي شاب) ولحظات أهدأ: عرض طهي في مطبخ قروي، حديث عن اللبان في السوق، ليلة لمشاهدة السلاحف الخضراء تضع بيضها في رأس الجنز، ورحلة بحرية لرصد الدلافين قبالة ساحل مسقط. تُنشر مواعيد الانطلاق الثابتة كل موسم، وتتوفر انطلاقات خاصة عند الطلب.",
    },
    highlights: [
      { en: "Small group, maximum 12 guests", ar: "مجموعة صغيرة بحد أقصى 12 ضيفًا" },
      { en: "Muscat, Nizwa, Jabal Akhdar and Wahiba Sands", ar: "مسقط ونزوى والجبل الأخضر ورمال وهيبة" },
      { en: "Turtle watching at Ras Al Jinz", ar: "مشاهدة السلاحف في رأس الجنز" },
      { en: "Dolphin-watching boat trip", ar: "رحلة بحرية لمشاهدة الدلافين" },
      { en: "Cooking demonstration and village visits", ar: "عرض طهي وزيارات للقرى" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Arrival & Muscat", ar: "الوصول ومسقط" }, body: { en: "Airport meet & greet, Grand Mosque, Mutrah Souq, welcome dinner.", ar: "الاستقبال في المطار، الجامع الأكبر، سوق مطرح، عشاء ترحيبي." } },
      { time: "Day 2", title: { en: "Nizwa & Jabal Akhdar", ar: "نزوى والجبل الأخضر" }, body: { en: "Fort, souq, cooking demonstration, ascent to the plateau. Overnight mountain hotel.", ar: "القلعة، السوق، عرض طهي، الصعود إلى الهضبة. المبيت في فندق جبلي." } },
      { time: "Day 3", title: { en: "Jabal Akhdar → Wahiba Sands", ar: "الجبل الأخضر ← رمال وهيبة" }, body: { en: "Village walk, Wadi Bani Khalid, sunset on the dunes. Overnight desert camp.", ar: "مسار القرى، وادي بني خالد، الغروب فوق الكثبان. المبيت في مخيم صحراوي." } },
      { time: "Day 4", title: { en: "Wahiba → Sur → Ras Al Jinz", ar: "وهيبة ← صور ← رأس الجنز" }, body: { en: "Dhow yard in Sur, evening turtle watching. Overnight Ras Al Jinz.", ar: "حوض السفن في صور، مشاهدة السلاحف مساءً. المبيت في رأس الجنز." } },
      { time: "Day 5", title: { en: "Wadi Shab → Muscat", ar: "وادي شاب ← مسقط" }, body: { en: "Hike and swim, Bimmah Sinkhole, return to Muscat. Farewell dinner.", ar: "مشي وسباحة، حفرة بمة، العودة إلى مسقط. عشاء وداعي." } },
      { time: "Day 6", title: { en: "Dolphins & departure", ar: "الدلافين والمغادرة" }, body: { en: "Morning dolphin-watching cruise, airport transfer.", ar: "رحلة بحرية صباحية لمشاهدة الدلافين، النقل إلى المطار." } },
    ],
    inclusions: [
      { en: "5 nights accommodation (hotels + desert camp) with breakfast", ar: "5 ليالٍ إقامة (فنادق ومخيم صحراوي) مع الإفطار" },
      { en: "Licensed Omani guide throughout; 4WD vehicles and bus", ar: "مرشد عُماني مرخّص طوال الرحلة؛ سيارات دفع رباعي وحافلة" },
      { en: "Welcome and farewell dinners, desert camp dinner", ar: "عشاء ترحيبي ووداعي وعشاء المخيم الصحراوي" },
      { en: "Turtle reserve entry, dolphin cruise, all entrance fees", ar: "دخول محمية السلاحف، رحلة الدلافين، وجميع رسوم الدخول" },
      { en: "Airport transfers", ar: "النقل من وإلى المطار" },
    ],
    exclusions: [{ en: "International flights, visa, lunches", ar: "الرحلات الدولية، التأشيرة، وجبات الغداء" }, ...commonExclusions],
    faqs: commonFaqs(168),
    category: "multi_day",
    secondaryCategories: ["cultural", "boat"],
    destinations: ["muscat", "nizwa", "jebel_akhdar", "wahiba", "sur", "wadi_shab"],
    durationLabel: { en: "6 days / 5 nights", ar: "6 أيام / 5 ليالٍ" },
    durationMinutes: 8640,
    durationDays: 6,
    startTimes: ["09:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 4,
    maxGroup: 12,
    capacityPerSlot: 12,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 590,
    priceChildOmr: 350,
    childAgeMax: 11,
    priceIsPlaceholder: true,
    depositPercent: 30,
    freeCancellationHours: 168,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 0,
    image: "sur",
    isFeatured: false,
    tags: ["group", "multi-day", "turtles", "dolphins"],
  },
  {
    code: "OCT-010",
    kind: "tour",
    title: { en: "8-Day Complete Oman Experience", ar: "تجربة عُمان الكاملة في 8 أيام" },
    slug: { en: "complete-oman-experience-8-day", ar: "تجربة-عمان-الكاملة-8-أيام" },
    summary: {
      en: "The grand private tour: Muscat, mountains, desert, the eastern coast and a flight south to the frankincense land of Salalah.",
      ar: "الجولة الخاصة الكبرى: مسقط والجبال والصحراء والساحل الشرقي ورحلة جوية جنوبًا إلى أرض اللبان في صلالة.",
    },
    description: {
      en: "Everything Oman is known for, in eight unhurried private days. After Muscat, Nizwa and Jabal Akhdar we head to Jebel Shams — the Grand Canyon of Arabia — and the mud-brick village of Misfat Al Abriyeen, then to Wahiba Sands for a night with the Bedouin and on to the turtle beaches of Ras Al Jinz and Wadi Shab. A short domestic flight takes you to Salalah, where the Land of Frankincense UNESCO sites, the beaches of Mughsail and the tomb of Job fill the final two days before you fly home from Salalah or return to Muscat. Accommodation ranges from boutique to five-star and is tailored to your preferences.",
      ar: "كل ما تشتهر به عُمان في ثمانية أيام خاصة بلا عجلة. بعد مسقط ونزوى والجبل الأخضر نتوجه إلى جبل شمس، الأخدود الكبير في الجزيرة العربية، وقرية مسفاة العبريين الطينية، ثم إلى رمال وهيبة لقضاء ليلة مع البدو، فإلى شواطئ السلاحف في رأس الجنز ووادي شاب. وتنقلك رحلة داخلية قصيرة إلى صلالة، حيث تملأ مواقع أرض اللبان المسجّلة لدى اليونسكو وشواطئ المغسيل وضريح النبي أيوب اليومين الأخيرين قبل أن تعود إلى بلدك من صلالة أو إلى مسقط. تتراوح الإقامة بين البوتيك والخمس نجوم وتُصمَّم وفق تفضيلاتك.",
    },
    highlights: [
      { en: "Jebel Shams canyon rim walk and Misfat Al Abriyeen", ar: "مسار حافة أخدود جبل شمس ومسفاة العبريين" },
      { en: "Night with the Bedouin in Wahiba Sands", ar: "ليلة مع البدو في رمال وهيبة" },
      { en: "Turtle nesting at Ras Al Jinz and Wadi Shab swim", ar: "تعشيش السلاحف في رأس الجنز وسباحة في وادي شاب" },
      { en: "Domestic flight to Salalah and the Land of Frankincense", ar: "رحلة داخلية إلى صلالة وأرض اللبان" },
      { en: "Private guide and 4WD for the whole journey", ar: "مرشد خاص وسيارة دفع رباعي طوال الرحلة" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Muscat", ar: "مسقط" }, body: { en: "Arrival, Grand Mosque, Mutrah Souq, Old Muscat.", ar: "الوصول، الجامع الأكبر، سوق مطرح، مسقط القديمة." } },
      { time: "Day 2", title: { en: "Nizwa & Jabal Akhdar", ar: "نزوى والجبل الأخضر" }, body: { en: "Fort, souq, rose terraces. Overnight on the plateau.", ar: "القلعة، السوق، مدرجات الورد. المبيت على الهضبة." } },
      { time: "Day 3", title: { en: "Jebel Shams & Misfat", ar: "جبل شمس ومسفاة" }, body: { en: "Balcony walk on the canyon rim, Misfat Al Abriyeen, Bahla Fort. Overnight Nizwa area.", ar: "مسار الشرفة على حافة الأخدود، مسفاة العبريين، حصن بهلاء. المبيت في منطقة نزوى." } },
      { time: "Day 4", title: { en: "Wahiba Sands", ar: "رمال وهيبة" }, body: { en: "Wadi Bani Khalid, dune driving, Bedouin camp under the stars.", ar: "وادي بني خالد، قيادة على الكثبان، مخيم بدوي تحت النجوم." } },
      { time: "Day 5", title: { en: "Sur & Ras Al Jinz", ar: "صور ورأس الجنز" }, body: { en: "Dhow yard, Wadi Shab hike and swim, evening turtle watching.", ar: "حوض السفن، مشي وسباحة في وادي شاب، مشاهدة السلاحف مساءً." } },
      { time: "Day 6", title: { en: "Fly to Salalah", ar: "الطيران إلى صلالة" }, body: { en: "Return to Muscat, afternoon flight south, Al Haffa souq at sunset.", ar: "العودة إلى مسقط، رحلة جوية بعد الظهر جنوبًا، سوق الحافة عند الغروب." } },
      { time: "Day 7", title: { en: "Land of Frankincense", ar: "أرض اللبان" }, body: { en: "Sumhuram, Wadi Dawkah frankincense trees, Mughsail beach and blowholes.", ar: "سمهرم، أشجار اللبان في وادي دوكة، شاطئ المغسيل والنوافير البحرية." } },
      { time: "Day 8", title: { en: "Departure", ar: "المغادرة" }, body: { en: "Tomb of Job, Al Baleed archaeological park, airport transfer.", ar: "ضريح النبي أيوب، منتزه البليد الأثري، النقل إلى المطار." } },
    ],
    inclusions: [
      { en: "7 nights accommodation with breakfast (category of your choice)", ar: "7 ليالٍ إقامة مع الإفطار (الفئة من اختيارك)" },
      { en: "Private 4WD and licensed Omani guide throughout", ar: "سيارة دفع رباعي خاصة ومرشد عُماني مرخّص طوال الرحلة" },
      { en: "Domestic flight Muscat–Salalah (economy)", ar: "رحلة داخلية مسقط–صلالة (درجة سياحية)" },
      { en: "Desert camp dinner, all entrance fees, airport transfers", ar: "عشاء المخيم الصحراوي، جميع رسوم الدخول، النقل من وإلى المطار" },
    ],
    exclusions: [{ en: "International flights, visa, lunches and most dinners", ar: "الرحلات الدولية، التأشيرة، وجبات الغداء ومعظم وجبات العشاء" }, ...commonExclusions],
    faqs: commonFaqs(168),
    category: "multi_day",
    secondaryCategories: ["cultural", "desert_4x4"],
    destinations: ["muscat", "nizwa", "jebel_akhdar", "wahiba", "sur", "wadi_shab", "salalah"],
    durationLabel: { en: "8 days / 7 nights", ar: "8 أيام / 7 ليالٍ" },
    durationMinutes: 11520,
    durationDays: 8,
    startTimes: ["09:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 790,
    priceChildOmr: 450,
    childAgeMax: 11,
    priceIsPlaceholder: true,
    depositPercent: 30,
    freeCancellationHours: 168,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 0,
    image: "salalah",
    isFeatured: false,
    tags: ["multi-day", "salalah", "luxury", "complete"],
  },
];
