import { commonExclusions, dayFaqs, hotelMuscat, times, type TourSeed } from "./tourSeedTypes";

/** Half-day and full-day tours from Muscat (Viator catalogue, September 2026). */
export const dayTours: TourSeed[] = [
  {
    code: "OCT-001",
    viatorCode: "425555P4",
    kind: "tour",
    title: {
      en: "Experience Muscat City Tour – Omani Guide & Traditional Food (5 h)",
      ar: "جولة مسقط مع مرشد عُماني وطعام تقليدي (5 ساعات)",
    },
    slug: { en: "experience-muscat-city-tour", ar: "جولة-مسقط-مع-مرشد-عماني" },
    summary: {
      en: "The essential Muscat in a private car: Grand Mosque, Royal Opera House, Qurum Beach, Mutrah Souq, Bait Al Zubair and Old Muscat, finished with lunch at Bait Al Luban.",
      ar: "خلاصة مسقط بسيارة خاصة: الجامع الأكبر ودار الأوبرا وشاطئ القرم وسوق مطرح وبيت الزبير ومسقط القديمة، مع غداء في مطعم بيت اللبان.",
    },
    description: {
      en: "Our most-booked experience and the number-one rated Muscat tour on Tripadvisor. A licensed Omani guide collects you in a private, air-conditioned sedan (or a 4WD on request) and begins at the Sultan Qaboos Grand Mosque, an architectural masterpiece opened in 2001, where you learn the stories behind its chandelier and hand-knotted carpet. We continue to the Royal Opera House Muscat, pause at Qurum Beach, then wander the frankincense-scented lanes of Mutrah Souq. At Bait Al Zubair Museum you meet Oman's heritage up close before a photo stop in Old Muscat overlooking Al Alam Palace and the Portuguese forts of Mirani and Jalali. The tour ends with authentic Omani cuisine at Bait Al Luban, the restaurant locals recommend to their guests.\n\nOn Fridays the mosque is closed to visitors; we replace it with the Muscat viewpoint and adjust the route. Choose the 15:00 start if you prefer an evening city tour.",
      ar: "تجربتنا الأكثر حجزًا وجولة مسقط الأعلى تقييمًا على تريب أدفايزر. يستقبلك مرشد عُماني مرخّص بسيارة سيدان خاصة مكيّفة (أو دفع رباعي عند الطلب)، ويبدأ من جامع السلطان قابوس الأكبر، التحفة المعمارية التي افتُتحت عام 2001، حيث تتعرّف على قصة ثريّاه وسجادته المنسوجة يدويًا. نواصل إلى دار الأوبرا السلطانية، ونتوقف عند شاطئ القرم، ثم نتجوّل في أزقة سوق مطرح العابقة برائحة اللبان. وفي متحف بيت الزبير تلتقي التراث العُماني عن قرب، قبل توقف للتصوير في مسقط القديمة المطلّة على قصر العلم وقلعتَي الميراني والجلالي البرتغاليتين. تُختتم الجولة بمأكولات عُمانية أصيلة في مطعم بيت اللبان الذي يوصي به أهل مسقط لضيوفهم.\n\nيوم الجمعة يُغلق الجامع أمام الزوار، فنستبدله بإطلالة مسقط ونعدّل المسار. اختر الانطلاق في الساعة 15:00 إن كنت تفضّل جولة مسائية.",
    },
    highlights: [
      { en: "Guided visit to the Sultan Qaboos Grand Mosque", ar: "زيارة بإرشاد لجامع السلطان قابوس الأكبر" },
      { en: "Royal Opera House and Qurum Beach", ar: "دار الأوبرا السلطانية وشاطئ القرم" },
      { en: "Mutrah Souq and Bait Al Zubair Museum", ar: "سوق مطرح ومتحف بيت الزبير" },
      { en: "Al Alam Palace and the Mirani & Jalali forts", ar: "قصر العلم وقلعتا الميراني والجلالي" },
      { en: "Traditional Omani lunch at Bait Al Luban", ar: "غداء عُماني تقليدي في بيت اللبان" },
    ],
    itinerary: [
      { time: "08:30", title: { en: "Hotel pickup", ar: "الاستلام من الفندق" }, body: { en: "Your guide meets you in the lobby (or at the cruise port gate) in a private car.", ar: "يلتقيك مرشدك في بهو الفندق (أو عند بوابة ميناء السفن) بسيارة خاصة." } },
      { time: "09:00", title: { en: "Sultan Qaboos Grand Mosque", ar: "جامع السلطان قابوس الأكبر" }, body: { en: "One hour inside the prayer hall and gardens (visitors 8:00–11:00, closed Fridays).", ar: "ساعة داخل قاعة الصلاة والحدائق (للزوار 8:00–11:00، مغلق الجمعة)." } },
      { time: "10:15", title: { en: "Royal Opera House & Qurum Beach", ar: "دار الأوبرا وشاطئ القرم" }, body: { en: "The region's most elegant cultural landmark, then a breath of sea air on the beach.", ar: "أرقى معلم ثقافي في المنطقة، ثم نسمة بحر على الشاطئ." } },
      { time: "11:00", title: { en: "Mutrah Souq & Bait Al Zubair", ar: "سوق مطرح وبيت الزبير" }, body: { en: "Frankincense, silver and textiles in the oldest market in Muscat; Omani heritage at the museum.", ar: "اللبان والفضة والمنسوجات في أقدم أسواق مسقط؛ والتراث العُماني في المتحف." } },
      { time: "12:15", title: { en: "Old Muscat", ar: "مسقط القديمة" }, body: { en: "Photo stop at Al Alam Palace and the harbour forts.", ar: "توقف للتصوير عند قصر العلم وقلاع الميناء." } },
      { time: "12:45", title: { en: "Lunch at Bait Al Luban", ar: "الغداء في بيت اللبان" }, body: { en: "Shuwa, maqbous, fresh bread, halwa and kahwa, then return to your hotel by about 13:30.", ar: "شواء ومقبوس وخبز طازج وحلوى وقهوة، ثم العودة إلى الفندق نحو 13:30." } },
    ],
    inclusions: [
      { en: "Private luxury sedan (3–4 guests) or 4WD on request", ar: "سيارة سيدان فاخرة خاصة (3–4 ضيوف) أو دفع رباعي عند الطلب" },
      { en: "Official English/Arabic-speaking Omani guide", ar: "مرشد عُماني رسمي يتحدث الإنجليزية والعربية" },
      { en: "Hotel or cruise-port pickup and drop-off in Muscat", ar: "الاستلام والتوصيل من الفندق أو ميناء السفن في مسقط" },
      { en: "Lunch at Bait Al Luban restaurant", ar: "الغداء في مطعم بيت اللبان" },
      { en: "Car parking fees and bottled water", ar: "رسوم المواقف ومياه معبأة" },
    ],
    exclusions: [
      { en: "Royal Opera House entrance (about OMR 3 per person, optional)", ar: "رسوم دخول دار الأوبرا (نحو 3 ر.ع. للشخص، اختياري)" },
      { en: "Bait Al Zubair Museum entrance (about OMR 3 per person)", ar: "رسوم دخول متحف بيت الزبير (نحو 3 ر.ع. للشخص)" },
      ...commonExclusions,
    ],
    faqs: dayFaqs({
      question: { en: "What should I wear for the mosque?", ar: "ماذا أرتدي لزيارة الجامع؟" },
      answer: { en: "Women need a headscarf and clothing covering arms and legs; men should avoid shorts. Abayas can be borrowed at the entrance if needed.", ar: "تحتاج النساء إلى غطاء رأس وملابس تغطي الذراعين والساقين، ويُنصح الرجال بتجنب السراويل القصيرة. يمكن استعارة العباءات عند المدخل عند الحاجة." },
    }),
    category: "city_tours",
    secondaryCategories: ["food_family", "cultural"],
    destinations: ["muscat"],
    durationLabel: { en: "4–5 hours", ar: "4–5 ساعات" },
    durationMinutes: 300,
    durationDays: 1,
    startTimes: ["08:30", "09:00", "09:30", "10:00", "11:00", "13:00", "14:00", "15:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 3,
    difficulty: "easy",
    pricingModel: "per_group",
    priceGroupOmr: 88,
    usdReference: 230,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 24,
    image: "muscat",
    isFeatured: true,
    featuredOrder: 1,
    tags: ["bestseller", "food", "mosque", "souq", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-002",
    viatorCode: "425555P2",
    kind: "tour",
    title: {
      en: "Private Wadi Shab Hike & Swim Adventure with Bimmah Sinkhole",
      ar: "مغامرة وادي شاب الخاصة: مشي وسباحة مع حفرة بمة",
    },
    slug: { en: "wadi-shab-bimmah-sinkhole-private", ar: "وادي-شاب-وحفرة-بمة" },
    summary: {
      en: "Swim the Bimmah Sinkhole, boat across and hike Wadi Shab to its hidden waterfall cave, then lunch, Fins white beach and Omani tea before returning to Muscat.",
      ar: "سباحة في حفرة بمة، عبور بالقارب ومسار في وادي شاب حتى كهف الشلال المخفي، ثم غداء وشاطئ فنس الأبيض وشاي عُماني قبل العودة إلى مسقط.",
    },
    description: {
      en: "Wadi Shab is the wadi on every Oman postcard, and this private day makes the most of it. After pickup we drive the coastal highway south to the Bimmah Sinkhole, a limestone crater filled with turquoise water where you take a first swim. At Wadi Shab a small boat carries us across the mouth of the wadi and the walk begins: about 45 minutes past terraced plantations and boulder paths, with your guide pointing out the falaj channels and the best photo angles. The reward is a chain of emerald pools; swim through them and, if you are comfortable, through a narrow gap in the rock into a cave with a waterfall inside. Lunch at a local Omani restaurant follows, then we relax at Fins white beach with tea, coffee and dates before an easy drive back to Muscat.\n\nThe standard private vehicle is ideal for up to four or five adults; groups of six or more travel in our private minibus.",
      ar: "وادي شاب هو الوادي الذي يظهر على كل بطاقة بريدية من عُمان، وهذا اليوم الخاص يستثمره على أكمل وجه. بعد الاستلام نسلك الطريق الساحلي جنوبًا إلى حفرة بمة، فوهة جيرية مليئة بمياه فيروزية تسبح فيها أولًا. وفي وادي شاب يعبر بنا قارب صغير فوهة الوادي ليبدأ المسار: نحو 45 دقيقة بين المزارع المدرّجة والصخور، بينما يشير مرشدك إلى قنوات الأفلاج وأفضل زوايا التصوير. المكافأة سلسلة من البرك الزمردية؛ اسبح عبرها، وإن كنت مرتاحًا، مرّ عبر فجوة ضيقة في الصخر إلى كهف بداخله شلال. يلي ذلك غداء في مطعم عُماني محلي، ثم نسترخي على شاطئ فنس الأبيض مع الشاي والقهوة والتمر قبل عودة هادئة إلى مسقط.\n\nالسيارة الخاصة القياسية مثالية حتى أربعة أو خمسة بالغين؛ وتسافر المجموعات من ستة فأكثر في حافلتنا الصغيرة الخاصة.",
    },
    highlights: [
      { en: "Swim in the Bimmah Sinkhole", ar: "السباحة في حفرة بمة" },
      { en: "Boat crossing and guided canyon hike", ar: "عبور بالقارب ومسار جبلي بإرشاد" },
      { en: "Turquoise pools and the waterfall cave", ar: "برك فيروزية وكهف الشلال" },
      { en: "Lunch at a local restaurant, tea break at Fins white beach", ar: "غداء في مطعم محلي واستراحة شاي على شاطئ فنس الأبيض" },
      { en: "Private vehicle and English-speaking Omani guide", ar: "سيارة خاصة ومرشد عُماني يتحدث الإنجليزية" },
    ],
    itinerary: [
      { time: "07:30", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "Scenic drive along the Gulf of Oman coast (about 1 h 30).", ar: "رحلة خلابة على ساحل خليج عُمان (نحو ساعة ونصف)." } },
      { time: "09:00", title: { en: "Bimmah Sinkhole", ar: "حفرة بمة" }, body: { en: "About 40 minutes to swim in the crystal-clear sinkhole.", ar: "نحو 40 دقيقة للسباحة في الحفرة الصافية." } },
      { time: "10:00", title: { en: "Wadi Shab hike & swim", ar: "مشي وسباحة في وادي شاب" }, body: { en: "Boat crossing, 45-minute hike and three hours in the wadi, swimming through the pools to the cave.", ar: "عبور بالقارب ومسار 45 دقيقة وثلاث ساعات في الوادي، مع سباحة عبر البرك إلى الكهف." } },
      { time: "13:15", title: { en: "Lunch", ar: "الغداء" }, body: { en: "Fresh fish or Omani dishes at a local restaurant in Tiwi.", ar: "سمك طازج أو أطباق عُمانية في مطعم محلي في طيوي." } },
      { time: "14:00", title: { en: "Fins white beach", ar: "شاطئ فنس الأبيض" }, body: { en: "Swim or relax with tea, coffee and dates; hotel drop-off around 16:00.", ar: "سباحة أو استرخاء مع الشاي والقهوة والتمر؛ التوصيل إلى الفندق نحو 16:00." } },
    ],
    inclusions: [
      { en: "Private transportation with hotel pickup and drop-off", ar: "نقل خاص مع الاستلام والتوصيل من وإلى الفندق" },
      { en: "Official English-speaking Omani guide", ar: "مرشد عُماني رسمي يتحدث الإنجليزية" },
      { en: "Boat crossing at Wadi Shab", ar: "عبور القارب في وادي شاب" },
      { en: "Lunch at a local Omani restaurant", ar: "غداء في مطعم عُماني محلي" },
      { en: "Tea, coffee, dates and bottled water", ar: "شاي وقهوة وتمر ومياه معبأة" },
    ],
    exclusions: [{ en: "Water shoes (recommended; can be rented on site)", ar: "أحذية مائية (يُنصح بها؛ متوفرة للإيجار في الموقع)" }, ...commonExclusions],
    faqs: dayFaqs({
      question: { en: "Do I need to be a strong swimmer?", ar: "هل يجب أن أكون سبّاحًا ماهرًا؟" },
      answer: { en: "You should be comfortable swimming about 50 m in calm water to reach the cave. Life jackets are available, and the hike and first pools can be enjoyed without swimming. Bring swimwear, a towel, sunscreen, a change of clothes and a waterproof phone case.", ar: "يجب أن تكون مرتاحًا للسباحة نحو 50 مترًا في مياه هادئة للوصول إلى الكهف. تتوفر سترات النجاة، ويمكن الاستمتاع بالمسار والبرك الأولى دون سباحة. أحضر ملابس السباحة ومنشفة وواقي شمس وملابس للتبديل وحافظة هاتف مقاومة للماء." },
    }),
    category: "mountain_wadi",
    secondaryCategories: ["day_trips", "hiking_camping"],
    destinations: ["wadi_shab", "sur"],
    durationLabel: { en: "8 hours", ar: "8 ساعات" },
    durationMinutes: 480,
    durationDays: 1,
    startTimes: times("07:30", "11:00"),
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 10,
    capacityPerSlot: 10,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 69,
    priceChildOmr: 35,
    childAgeMax: 11,
    usdReference: 179,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 8,
    image: "wadi-shab",
    isFeatured: true,
    featuredOrder: 2,
    tags: ["swimming", "hiking", "nature", "bestseller", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-003",
    viatorCode: "425555P1",
    kind: "tour",
    title: {
      en: "Private Wahiba Sands & Wadi Bani Khalid 4x4 Adventure from Muscat",
      ar: "مغامرة رمال وهيبة ووادي بني خالد بالدفع الرباعي من مسقط",
    },
    slug: { en: "wahiba-sands-wadi-bani-khalid-4x4", ar: "رمال-وهيبة-ووادي-بني-خالد" },
    summary: {
      en: "Off-road into the golden dunes of Wahiba Sands, coffee with a Bedouin family, then a swim in the emerald pools of Wadi Bani Khalid — all in a private 4x4.",
      ar: "قيادة على الرمال بين كثبان وهيبة الذهبية، قهوة مع عائلة بدوية، ثم سباحة في برك وادي بني خالد الزمردية؛ كل ذلك بسيارة دفع رباعي خاصة.",
    },
    description: {
      en: "Discover two of Oman's most impressive landscapes on one private full-day adventure. We leave Muscat early and travel by 4x4 into the Wahiba Sands, where your guide lets the tyres down for an exciting off-road drive over the dunes before we visit a Bedouin family for coffee, dates and a taste of traditional hospitality (camel rides can be added on the spot). From the desert we continue to Wadi Bani Khalid, one of the most beautiful oases in the country, framed by mountains and palm groves; there is time to swim, relax or walk deeper into the wadi with your guide. Lunch is at a local Omani restaurant, and we stop in the old village of Fanja on the way home. Private transport, hotel pickup and an English-speaking Omani guide are included.",
      ar: "اكتشف اثنين من أروع مناظر عُمان الطبيعية في مغامرة خاصة ليوم كامل. نغادر مسقط باكرًا ونتوجّه بسيارة الدفع الرباعي إلى رمال وهيبة، حيث يخفّف مرشدك ضغط الإطارات لقيادة مثيرة فوق الكثبان قبل أن نزور عائلة بدوية لتناول القهوة والتمر وتذوّق الضيافة التقليدية (يمكن إضافة ركوب الإبل في الموقع). من الصحراء نواصل إلى وادي بني خالد، أحد أجمل الواحات في البلاد، تحيط به الجبال وبساتين النخيل؛ وهناك متسع للسباحة أو الاسترخاء أو التوغّل في الوادي مع مرشدك. الغداء في مطعم عُماني محلي، مع توقف في قرية فنجاء القديمة في طريق العودة. يشمل السعر النقل الخاص والاستلام من الفندق ومرشدًا عُمانيًا يتحدث الإنجليزية.",
    },
    highlights: [
      { en: "Dune driving in a private 4x4", ar: "قيادة على الكثبان بسيارة دفع رباعي خاصة" },
      { en: "Coffee and dates with a Bedouin family", ar: "قهوة وتمر مع عائلة بدوية" },
      { en: "Swim in the pools of Wadi Bani Khalid", ar: "سباحة في برك وادي بني خالد" },
      { en: "Lunch at a local Omani restaurant", ar: "غداء في مطعم عُماني محلي" },
      { en: "Stop at the old village of Fanja", ar: "توقف في قرية فنجاء القديمة" },
    ],
    itinerary: [
      { time: "07:00", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "About two hours' drive inland via the Sharqiyah road.", ar: "نحو ساعتين بالسيارة إلى الداخل عبر طريق الشرقية." } },
      { time: "09:30", title: { en: "Wahiba Sands", ar: "رمال وهيبة" }, body: { en: "Off-road dune drive and a visit to a Bedouin family (about one hour).", ar: "قيادة على الكثبان وزيارة عائلة بدوية (نحو ساعة)." } },
      { time: "11:15", title: { en: "Wadi Bani Khalid", ar: "وادي بني خالد" }, body: { en: "About 1 h 30 to swim and explore the pools.", ar: "نحو ساعة ونصف للسباحة واستكشاف البرك." } },
      { time: "13:00", title: { en: "Lunch", ar: "الغداء" }, body: { en: "Omani dishes at a local restaurant.", ar: "أطباق عُمانية في مطعم محلي." } },
      { time: "14:00", title: { en: "Fanja & return", ar: "فنجاء والعودة" }, body: { en: "Short stop at Fanja; hotel drop-off around 15:30.", ar: "توقف قصير في فنجاء؛ التوصيل إلى الفندق نحو 15:30." } },
    ],
    inclusions: [
      { en: "Private 4x4 transportation with fuel", ar: "نقل خاص بسيارة دفع رباعي مع الوقود" },
      { en: "Official English-speaking Omani guide", ar: "مرشد عُماني رسمي يتحدث الإنجليزية" },
      { en: "Hotel or cruise-port pickup and drop-off in Muscat", ar: "الاستلام والتوصيل من الفندق أو ميناء السفن في مسقط" },
      { en: "Lunch at a local Omani restaurant", ar: "غداء في مطعم عُماني محلي" },
      { en: "Coffee and dates with a Bedouin family, bottled water", ar: "قهوة وتمر مع عائلة بدوية ومياه معبأة" },
    ],
    exclusions: [{ en: "Camel ride (about OMR 3 per person, payable on site)", ar: "ركوب الإبل (نحو 3 ر.ع. للشخص، يُدفع في الموقع)" }, ...commonExclusions],
    faqs: dayFaqs({
      question: { en: "How many people fit in one 4x4?", ar: "كم شخصًا يتسع لهم سيارة الدفع الرباعي؟" },
      answer: { en: "Up to four or five adults travel comfortably; a group of six suits four adults and two children. If all six are adults we recommend a second vehicle, which we arrange on request.", ar: "يسافر حتى أربعة أو خمسة بالغين براحة؛ ومجموعة الستة تناسب أربعة بالغين وطفلين. إذا كان الستة بالغين نوصي بسيارة ثانية نرتّبها عند الطلب." },
    }),
    category: "desert_4x4",
    secondaryCategories: ["day_trips", "mountain_wadi"],
    destinations: ["wahiba"],
    durationLabel: { en: "8 hours", ar: "8 ساعات" },
    durationMinutes: 480,
    durationDays: 1,
    startTimes: times("07:00", "12:30"),
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 72,
    priceChildOmr: 36,
    childAgeMax: 11,
    usdReference: 188,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 4,
    image: "wahiba",
    isFeatured: true,
    featuredOrder: 3,
    tags: ["desert", "4x4", "swimming", "bedouin", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-004",
    viatorCode: "425555P3",
    kind: "tour",
    title: {
      en: "Private Nizwa Fort, Souq & Jebel Akhdar Mountain 4WD Tour",
      ar: "جولة خاصة: قلعة نزوى والسوق والجبل الأخضر بالدفع الرباعي",
    },
    slug: { en: "nizwa-fort-souq-jebel-akhdar", ar: "قلعة-نزوى-والجبل-الأخضر" },
    summary: {
      en: "Nizwa's souq and fort, the terraces and villages of Jebel Akhdar at 2,300 m, and the ancient falaj of Birkat Al Mouz on a private 4WD day from Muscat.",
      ar: "سوق نزوى وقلعتها، ومدرجات الجبل الأخضر وقراه على ارتفاع 2300 متر، وفلج بركة الموز القديم في يوم خاص بالدفع الرباعي من مسقط.",
    },
    description: {
      en: "History, culture and mountain scenery in one full day. We begin in Nizwa, the ancient capital, exploring a souq known for dates, halwa, pottery, silver and spices before climbing the round tower of Nizwa Fort to hear how one of Oman's most important cities defended itself. A 4WD is compulsory for the road up Jebel Akhdar, the Green Mountain: at about 2,300 m the air is cool and the views take in agricultural terraces, traditional villages and, in season, the rose gardens that supply Oman's famous rosewater. On the way down we walk through Birkat Al Mouz, where the UNESCO-listed Falaj Al Khatmeen has irrigated the plantations for centuries. Your English-speaking Omani guide and a private 4WD are with you throughout.",
      ar: "تاريخ وثقافة ومناظر جبلية في يوم واحد. نبدأ في نزوى، العاصمة القديمة، لنستكشف سوقًا يشتهر بالتمور والحلوى والفخار والفضة والتوابل، قبل أن نصعد البرج الدائري لقلعة نزوى ونسمع كيف دافعت إحدى أهم مدن عُمان عن نفسها. سيارة الدفع الرباعي إلزامية للصعود إلى الجبل الأخضر: على ارتفاع نحو 2300 متر يعتدل الهواء وتمتد الإطلالة على المدرجات الزراعية والقرى التقليدية، وفي الموسم حدائق الورد التي يُصنع منها ماء الورد العُماني الشهير. وفي طريق النزول نتمشّى في بركة الموز حيث يروي فلج الخطمين المدرج في اليونسكو المزارع منذ قرون. يرافقك مرشد عُماني يتحدث الإنجليزية وسيارة دفع رباعي خاصة طوال اليوم.",
    },
    highlights: [
      { en: "Nizwa Souq and the 17th-century Nizwa Fort", ar: "سوق نزوى وقلعة نزوى من القرن السابع عشر" },
      { en: "4WD ascent to Jebel Akhdar (2,300 m)", ar: "الصعود بالدفع الرباعي إلى الجبل الأخضر (2300 م)" },
      { en: "Terraced villages and rose gardens in season", ar: "قرى مدرّجة وحدائق ورد في الموسم" },
      { en: "UNESCO falaj at Birkat Al Mouz", ar: "فلج مدرج في اليونسكو في بركة الموز" },
      { en: "Private 4WD with an Omani guide", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني" },
    ],
    itinerary: [
      { time: "08:00", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "About 1 h 45 on the highway to Nizwa.", ar: "نحو ساعة و45 دقيقة على الطريق السريع إلى نزوى." } },
      { time: "09:45", title: { en: "Nizwa Souq", ar: "سوق نزوى" }, body: { en: "Dates, halwa, pottery and silver (about 40 minutes).", ar: "تمور وحلوى وفخار وفضة (نحو 40 دقيقة)." } },
      { time: "10:30", title: { en: "Nizwa Fort", ar: "قلعة نزوى" }, body: { en: "The round tower and its ingenious defences (entrance payable on site).", ar: "البرج الدائري ودفاعاته البارعة (رسوم الدخول تُدفع في الموقع)." } },
      { time: "11:30", title: { en: "Jebel Akhdar", ar: "الجبل الأخضر" }, body: { en: "4WD ascent to the Saiq Plateau, viewpoints, villages and lunch with a view.", ar: "الصعود بالدفع الرباعي إلى هضبة سيق، إطلالات وقرى وغداء بإطلالة." } },
      { time: "14:30", title: { en: "Birkat Al Mouz", ar: "بركة الموز" }, body: { en: "Walk through the old village and along Falaj Al Khatmeen; back in Muscat around 16:30.", ar: "تمشٍّ في القرية القديمة وعلى امتداد فلج الخطمين؛ العودة إلى مسقط نحو 16:30." } },
    ],
    inclusions: [
      { en: "Private 4WD transportation with fuel", ar: "نقل خاص بسيارة دفع رباعي مع الوقود" },
      { en: "Official English-speaking Omani guide", ar: "مرشد عُماني رسمي يتحدث الإنجليزية" },
      { en: "Hotel or cruise-port pickup and drop-off in Muscat", ar: "الاستلام والتوصيل من الفندق أو ميناء السفن في مسقط" },
      { en: "Bottled water", ar: "مياه معبأة" },
    ],
    exclusions: [
      { en: "Nizwa Fort entrance (about OMR 5 per person, payable on site)", ar: "رسوم دخول قلعة نزوى (نحو 5 ر.ع. للشخص، تُدفع في الموقع)" },
      { en: "Lunch (your guide recommends a local restaurant)", ar: "الغداء (يوصي مرشدك بمطعم محلي)" },
      ...commonExclusions,
    ],
    faqs: dayFaqs({
      question: { en: "Is it cold on the mountain?", ar: "هل الطقس بارد على الجبل؟" },
      answer: { en: "Jebel Akhdar is 10–15 °C cooler than Muscat; bring a light jacket from November to March.", ar: "الجبل الأخضر أبرد من مسقط بـ10–15 درجة؛ أحضر سترة خفيفة من نوفمبر إلى مارس." },
    }),
    category: "cultural",
    secondaryCategories: ["day_trips", "mountain_wadi"],
    destinations: ["nizwa", "jebel_akhdar"],
    durationLabel: { en: "8–9 hours", ar: "8–9 ساعات" },
    durationMinutes: 510,
    durationDays: 1,
    startTimes: ["08:00", "08:30", "09:00", "09:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 76,
    priceChildOmr: 38,
    childAgeMax: 11,
    usdReference: 197,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    externalReviewCount: 3,
    image: "jebel-akhdar",
    isFeatured: true,
    featuredOrder: 4,
    tags: ["culture", "fort", "mountains", "4x4", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-011",
    viatorCode: "425555P5",
    kind: "tour",
    title: {
      en: "Wakan Mountain Village & Nakhal Fort – Omani Guide, 4WD (8 h)",
      ar: "قرية وكان الجبلية وقلعة نخل مع مرشد عُماني بالدفع الرباعي (8 ساعات)",
    },
    slug: { en: "wakan-village-nakhal-fort-4wd", ar: "قرية-وكان-وقلعة-نخل" },
    summary: {
      en: "A 4WD climb to the terraced village of Wakan at 2,000 m, Nakhal Fort on its rock and the Al Thowarah hot spring, with lunch at a local restaurant.",
      ar: "صعود بالدفع الرباعي إلى قرية وكان المدرّجة على ارتفاع 2000 متر، وقلعة نخل فوق صخرتها، وعين الثوارة الحارة، مع غداء في مطعم محلي.",
    },
    description: {
      en: "West of Muscat the Hajar Mountains hide one of Oman's prettiest villages. After an off-road drive up Wadi Mistal we reach Wakan, perched at 2,000 m, where stone houses and terraces of apricot, pomegranate and grape trees cling to the slope; a short guided walk up the village steps ends at a viewpoint over the wadi. Back in the valley we visit Nakhal Fort, built on a rocky outcrop to guard the oasis, and climb its towers for views over the palm plantations. A stop at the Al Thowarah hot spring, where warm water flows through the date gardens, completes the circuit before lunch at a local restaurant and the return to Muscat. The fort is closed on Fridays.",
      ar: "غرب مسقط تخفي جبال الحجر إحدى أجمل قرى عُمان. بعد قيادة على الطرق الوعرة عبر وادي مستل نصل إلى وكان المعلّقة على ارتفاع 2000 متر، حيث تتشبّث البيوت الحجرية ومدرجات المشمش والرمان والعنب بالمنحدر؛ ويختتم مسار قصير بإرشاد على درجات القرية عند إطلالة على الوادي. وفي الوادي نزور قلعة نخل المبنية فوق نتوء صخري لحراسة الواحة، ونصعد أبراجها لنطل على مزارع النخيل. ويكتمل المسار بتوقف عند عين الثوارة الحارة حيث تجري المياه الدافئة بين بساتين النخيل، قبل الغداء في مطعم محلي والعودة إلى مسقط. القلعة مغلقة يوم الجمعة.",
    },
    highlights: [
      { en: "Off-road 4WD drive up Wadi Mistal to Wakan (2,000 m)", ar: "قيادة وعرة بالدفع الرباعي عبر وادي مستل إلى وكان (2000 م)" },
      { en: "Terraced orchards and a village viewpoint walk", ar: "بساتين مدرّجة ومسار إلى إطلالة القرية" },
      { en: "Nakhal Fort and its towers", ar: "قلعة نخل وأبراجها" },
      { en: "Al Thowarah hot spring among the date gardens", ar: "عين الثوارة الحارة بين بساتين النخيل" },
      { en: "Lunch at a local restaurant", ar: "غداء في مطعم محلي" },
    ],
    itinerary: [
      { time: "08:00", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "About 1 h 15 to the foot of Wadi Mistal.", ar: "نحو ساعة وربع إلى مدخل وادي مستل." } },
      { time: "09:30", title: { en: "Wakan village", ar: "قرية وكان" }, body: { en: "Off-road ascent, village walk and viewpoint (about two hours).", ar: "صعود وعر، تمشٍّ في القرية وإطلالة (نحو ساعتين)." } },
      { time: "12:00", title: { en: "Nakhal Fort", ar: "قلعة نخل" }, body: { en: "Guided visit of the fort (entrance included).", ar: "زيارة بإرشاد للقلعة (رسوم الدخول مشمولة)." } },
      { time: "13:15", title: { en: "Al Thowarah hot spring & lunch", ar: "عين الثوارة والغداء" }, body: { en: "Walk along the warm falaj, then lunch at a local restaurant; back in Muscat around 16:00.", ar: "تمشٍّ على امتداد الفلج الدافئ ثم الغداء في مطعم محلي؛ العودة إلى مسقط نحو 16:00." } },
    ],
    inclusions: [
      { en: "Private 4x4 with fuel", ar: "سيارة دفع رباعي خاصة مع الوقود" },
      { en: "Official Omani guide", ar: "مرشد عُماني رسمي" },
      { en: "Entrance fees for Nakhal Fort", ar: "رسوم دخول قلعة نخل" },
      { en: "Lunch and bottled water", ar: "الغداء ومياه معبأة" },
      { en: "Pickup from any hotel in Muscat, the airport or the cruise port", ar: "الاستلام من أي فندق في مسقط أو المطار أو ميناء السفن" },
    ],
    exclusions: commonExclusions,
    faqs: dayFaqs({
      question: { en: "Is the drive to Wakan safe?", ar: "هل الطريق إلى وكان آمن؟" },
      answer: { en: "Yes. The last stretch is a steep graded track that requires a 4WD and an experienced driver; our guides drive it every week. Wear closed shoes for the village steps.", ar: "نعم. المقطع الأخير طريق ترابي شديد الانحدار يتطلّب دفعًا رباعيًا وسائقًا خبيرًا؛ ومرشدونا يقودونه كل أسبوع. ارتدِ حذاءً مغلقًا لدرجات القرية." },
    }),
    category: "mountain_wadi",
    secondaryCategories: ["day_trips", "cultural", "photography"],
    destinations: ["nakhal"],
    durationLabel: { en: "8 hours", ar: "8 ساعات" },
    durationMinutes: 480,
    durationDays: 1,
    startTimes: ["08:00", "08:30", "09:00", "09:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 4,
    capacityPerSlot: 3,
    difficulty: "moderate",
    pricingModel: "per_group",
    priceGroupOmr: 154,
    usdReference: 400,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "nizwa",
    isFeatured: false,
    tags: ["mountains", "village", "fort", "4x4", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-012",
    viatorCode: "425555P6",
    kind: "tour",
    title: {
      en: "Explore Muscat – Seafood Lunch, Amouage Factory & Date Shop (7 h)",
      ar: "اكتشف مسقط: غداء بحري ومصنع أمواج ومتجر التمور (7 ساعات)",
    },
    slug: { en: "muscat-seafood-amouage-dates", ar: "مسقط-مأكولات-بحرية-وأمواج" },
    summary: {
      en: "A longer Muscat day for food and craft lovers: Old Muscat, Bait Al Zubair, Mutrah Souq, the Amouage perfume factory, a date shop in Seeb and fresh seafood at a local favourite.",
      ar: "يوم أطول في مسقط لعشّاق الطعام والحِرف: مسقط القديمة وبيت الزبير وسوق مطرح ومصنع عطور أمواج ومتجر تمور في السيب ومأكولات بحرية طازجة في مطعم محبوب محليًا.",
    },
    description: {
      en: "Unveil Muscat with a local Omani guide on a seven-hour route that goes beyond the classic landmarks. We photograph the Royal Opera House and the Grand Mosque, discover Old Muscat with Al Alam Palace and the Portuguese forts, and step into Bait Al Zubair to understand Omani traditions. In Mutrah Souq you pick up frankincense, the country's most cherished product. Then comes the part visitors rarely see: a guided visit to the Amouage perfume factory and visitor centre, the home of Oman's luxury fragrance house, and a stop at a date shop in Seeb to taste the varieties locals prize. Lunch is authentic Arabian seafood at a restaurant loved by residents, far from the tourist trail.",
      ar: "اكتشف مسقط مع مرشد عُماني محلي في مسار من سبع ساعات يتجاوز المعالم الكلاسيكية. نلتقط الصور عند دار الأوبرا السلطانية والجامع الأكبر، ونكتشف مسقط القديمة بقصر العلم والقلاع البرتغالية، وندخل بيت الزبير لفهم التقاليد العُمانية. وفي سوق مطرح تقتني اللبان، أعزّ منتجات البلاد. ثم يأتي الجزء الذي نادرًا ما يراه الزوار: زيارة بإرشاد لمصنع عطور أمواج ومركز الزوار، موطن دار العطور العُمانية الفاخرة، وتوقف في متجر تمور في السيب لتذوّق الأصناف التي يعتزّ بها أهل البلد. الغداء مأكولات بحرية عربية أصيلة في مطعم يحبه السكان بعيدًا عن المسار السياحي.",
    },
    highlights: [
      { en: "Old Muscat, Al Alam Palace and Bait Al Zubair", ar: "مسقط القديمة وقصر العلم وبيت الزبير" },
      { en: "Frankincense shopping in Mutrah Souq", ar: "شراء اللبان في سوق مطرح" },
      { en: "Amouage perfume factory and visitor centre", ar: "مصنع عطور أمواج ومركز الزوار" },
      { en: "Omani dates tasting in Seeb", ar: "تذوّق التمور العُمانية في السيب" },
      { en: "Seafood lunch at a local favourite", ar: "غداء بحري في مطعم محبوب محليًا" },
    ],
    itinerary: [
      { time: "08:30", title: { en: "Pickup & Royal Opera House", ar: "الاستلام ودار الأوبرا" }, body: { en: "Photo stop at the Opera House, then the Grand Mosque exterior.", ar: "توقف للتصوير عند دار الأوبرا ثم واجهة الجامع الأكبر." } },
      { time: "09:45", title: { en: "Old Muscat & Bait Al Zubair", ar: "مسقط القديمة وبيت الزبير" }, body: { en: "Palace, forts and the museum of Omani traditions.", ar: "القصر والقلاع ومتحف التقاليد العُمانية." } },
      { time: "11:00", title: { en: "Mutrah Souq", ar: "سوق مطرح" }, body: { en: "Frankincense, silver and a walk along the Corniche.", ar: "اللبان والفضة وتمشٍّ على الكورنيش." } },
      { time: "12:15", title: { en: "Amouage factory", ar: "مصنع أمواج" }, body: { en: "One hour at the perfume house's visitor centre.", ar: "ساعة في مركز زوار دار العطور." } },
      { time: "13:30", title: { en: "Seeb: dates & seafood lunch", ar: "السيب: التمور والغداء البحري" }, body: { en: "Date shop tasting, then a fresh seafood lunch; hotel drop-off around 15:30.", ar: "تذوّق في متجر التمور ثم غداء بحري طازج؛ التوصيل إلى الفندق نحو 15:30." } },
    ],
    inclusions: [
      { en: "Private car with Omani guide", ar: "سيارة خاصة مع مرشد عُماني" },
      { en: "Seafood lunch at an Arabian restaurant", ar: "غداء بحري في مطعم عربي" },
      { en: "Entrance fees and car parking", ar: "رسوم الدخول ومواقف السيارات" },
      { en: "Bottled water", ar: "مياه معبأة" },
    ],
    exclusions: commonExclusions,
    faqs: dayFaqs(),
    category: "city_tours",
    secondaryCategories: ["food_family", "cultural"],
    destinations: ["muscat"],
    durationLabel: { en: "7 hours", ar: "7 ساعات" },
    durationMinutes: 420,
    durationDays: 1,
    startTimes: ["08:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 4,
    capacityPerSlot: 3,
    difficulty: "easy",
    pricingModel: "per_group",
    priceGroupOmr: 115,
    priceIsPlaceholder: true,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "muscat",
    isFeatured: false,
    tags: ["food", "seafood", "perfume", "souq", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-013",
    viatorCode: "425555P7",
    kind: "tour",
    title: {
      en: "Jabal Shams Grand Canyon, Nizwa & Misfat Al Abriyeen – 4WD Day",
      ar: "أخدود جبل شمس ونزوى ومسفاة العبريين: يوم بالدفع الرباعي",
    },
    slug: { en: "jabal-shams-grand-canyon-nizwa-misfat", ar: "جبل-شمس-ونزوى-ومسفاة" },
    summary: {
      en: "Nizwa's souq and fort, an off-road climb to the rim of Wadi Ghul (the Grand Canyon of Arabia) and the terraced village of Misfat Al Abriyeen with its 2,000-year-old falaj.",
      ar: "سوق نزوى وقلعتها، وصعود وعر إلى حافة وادي غول (أخدود الجزيرة العربية الكبير)، وقرية مسفاة العبريين المدرّجة بفلجها العريق.",
    },
    description: {
      en: "A private full-day journey with a skilled Omani guide to the most dramatic landscape in the Hajar Mountains. We start in old Nizwa Souq, hunting for dates, pottery and silver, then walk to Nizwa Fort to hear how the imams defended the interior. The 4WD then climbs the graded mountain road to Jabal Shams, Oman's highest peak, where a viewpoint on the rim of Wadi Ghul looks a thousand metres down into the Grand Canyon of Arabia. On the way back we stop in Misfat Al Abriyeen, a village of stone houses stacked above banana and date terraces watered by a falaj that has flowed for two thousand years. Lunch at a local restaurant is included; total duration includes about five hours of scenic driving.",
      ar: "رحلة خاصة ليوم كامل مع مرشد عُماني متمرّس إلى أكثر مناظر جبال الحجر إبهارًا. نبدأ في سوق نزوى القديم بحثًا عن التمور والفخار والفضة، ثم نمشي إلى قلعة نزوى لنسمع كيف دافع الأئمة عن الداخل. بعدها تصعد سيارة الدفع الرباعي الطريق الجبلي المدرّج إلى جبل شمس، أعلى قمم عُمان، حيث تطل نقطة مشاهدة على حافة وادي غول من ارتفاع ألف متر على أخدود الجزيرة العربية الكبير. وفي طريق العودة نتوقف في مسفاة العبريين، قرية من البيوت الحجرية المتراصّة فوق مدرجات الموز والنخيل التي يرويها فلج يجري منذ ألفي عام. الغداء في مطعم محلي مشمول؛ وتشمل المدة الإجمالية نحو خمس ساعات من القيادة الخلابة.",
    },
    highlights: [
      { en: "Nizwa Souq and Nizwa Fort", ar: "سوق نزوى وقلعة نزوى" },
      { en: "Off-road ascent to Jabal Shams", ar: "صعود وعر إلى جبل شمس" },
      { en: "Rim viewpoint over Wadi Ghul, the Grand Canyon of Arabia", ar: "إطلالة على حافة وادي غول، أخدود الجزيرة العربية الكبير" },
      { en: "Misfat Al Abriyeen terraces and ancient falaj", ar: "مدرجات مسفاة العبريين والفلج العريق" },
      { en: "Lunch included", ar: "الغداء مشمول" },
    ],
    itinerary: [
      { time: "07:30", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "Highway to Nizwa (about 1 h 45).", ar: "الطريق السريع إلى نزوى (نحو ساعة و45 دقيقة)." } },
      { time: "09:15", title: { en: "Nizwa Souq & Fort", ar: "سوق نزوى والقلعة" }, body: { en: "45 minutes in the souq and 45 minutes in the fort (entrance payable on site).", ar: "45 دقيقة في السوق و45 دقيقة في القلعة (رسوم الدخول تُدفع في الموقع)." } },
      { time: "11:00", title: { en: "Jabal Shams", ar: "جبل شمس" }, body: { en: "Mountain drive and the Wadi Ghul canyon viewpoint; lunch en route.", ar: "قيادة جبلية وإطلالة أخدود وادي غول؛ الغداء في الطريق." } },
      { time: "14:30", title: { en: "Misfat Al Abriyeen", ar: "مسفاة العبريين" }, body: { en: "Walk through the terraced village and along the falaj; back in Muscat around 17:00.", ar: "تمشٍّ في القرية المدرّجة وعلى امتداد الفلج؛ العودة إلى مسقط نحو 17:00." } },
    ],
    inclusions: [
      { en: "Private 4x4 with fuel", ar: "سيارة دفع رباعي خاصة مع الوقود" },
      { en: "Official Omani guide", ar: "مرشد عُماني رسمي" },
      { en: "Lunch and bottled water", ar: "الغداء ومياه معبأة" },
      { en: "Pickup from hotels in and around Muscat", ar: "الاستلام من الفنادق في مسقط وضواحيها" },
    ],
    exclusions: [{ en: "Nizwa Fort entrance (about OMR 5 per person, payable on site)", ar: "رسوم دخول قلعة نزوى (نحو 5 ر.ع. للشخص، تُدفع في الموقع)" }, ...commonExclusions],
    faqs: dayFaqs({
      question: { en: "Is there much walking?", ar: "هل هناك مشي كثير؟" },
      answer: { en: "Short, easy walks at each stop; the village of Misfat has uneven steps. The mountain road is winding, so travellers prone to motion sickness should sit in front.", ar: "مسارات قصيرة وسهلة في كل محطة؛ ودرجات قرية مسفاة غير مستوية. الطريق الجبلي متعرّج، فليجلس من يتأثّر بدوار الحركة في المقعد الأمامي." },
    }),
    category: "mountain_wadi",
    secondaryCategories: ["day_trips", "cultural"],
    destinations: ["nizwa", "jabal_shams"],
    durationLabel: { en: "8–9 hours", ar: "8–9 ساعات" },
    durationMinutes: 540,
    durationDays: 1,
    startTimes: ["07:30", "08:00", "08:30", "09:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 4,
    capacityPerSlot: 3,
    difficulty: "easy",
    pricingModel: "per_group",
    priceGroupOmr: 154,
    usdReference: 400,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "nizwa",
    isFeatured: true,
    featuredOrder: 5,
    tags: ["canyon", "mountains", "culture", "4x4", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-014",
    viatorCode: "425555P8",
    kind: "tour",
    title: {
      en: "Friday Goat Market & Souq in Nizwa with an Omani Guide",
      ar: "سوق الجمعة وسوق الماشية في نزوى مع مرشد عُماني",
    },
    slug: { en: "nizwa-friday-market-tour", ar: "سوق-الجمعة-في-نزوى" },
    summary: {
      en: "An early start for Nizwa's famous Friday livestock auction and souq, the fort, Birkat Al Mouz's ancient falaj and an old mud house, with lunch in Fanja.",
      ar: "انطلاق مبكر لحضور مزاد الماشية الشهير وسوق الجمعة في نزوى، والقلعة، وفلج بركة الموز القديم، وبيت طيني عريق، مع غداء في فنجاء.",
    },
    description: {
      en: "Every Friday morning Nizwa turns into the liveliest market in Oman. Traders lead goats, sheep and cattle around a ring while buyers bid, and the souq fills with dates, honey, spices, halwa, fruit, vegetables and hand-made silver. We leave Muscat before dawn so that you see the auction at its peak with a guide who explains what is happening. Afterwards we visit Nizwa Fort and its ingenious defences, take a coffee break, then continue to Birkat Al Mouz to walk beside Falaj Al Khatmeen, an irrigation channel two thousand years old, and step inside Al Seebani old house of mud, stone and wood. On the way back we stop for a relaxed lunch at a local restaurant in Fanja. This trip runs with a small group in a comfortable bus; contact us if you prefer a private vehicle.",
      ar: "كل صباح جمعة تتحوّل نزوى إلى أكثر أسواق عُمان حيوية. يقود التجار الماعز والأغنام والأبقار حول حلقة المزاد بينما يزايد المشترون، ويمتلئ السوق بالتمور والعسل والتوابل والحلوى والفواكه والخضروات والفضة اليدوية. نغادر مسقط قبل الفجر لتشهد المزاد في ذروته مع مرشد يشرح لك ما يجري. بعد ذلك نزور قلعة نزوى ودفاعاتها البارعة، ونأخذ استراحة قهوة، ثم نواصل إلى بركة الموز لنتمشى بجوار فلج الخطمين، قناة ري عمرها ألفا عام، وندخل بيت السيباني القديم المبني من الطين والحجر والخشب. وفي طريق العودة نتوقف لغداء هادئ في مطعم محلي في فنجاء. تُنفَّذ هذه الرحلة بمجموعة صغيرة في حافلة مريحة؛ تواصل معنا إن كنت تفضّل سيارة خاصة.",
    },
    highlights: [
      { en: "Friday livestock auction and Nizwa Souq at their liveliest", ar: "مزاد الماشية وسوق نزوى في أوج حيويتهما يوم الجمعة" },
      { en: "Nizwa Fort with entrance included", ar: "قلعة نزوى مع رسوم الدخول" },
      { en: "Falaj Al Khatmeen and Al Seebani old house at Birkat Al Mouz", ar: "فلج الخطمين وبيت السيباني القديم في بركة الموز" },
      { en: "Lunch at a local restaurant in Fanja", ar: "غداء في مطعم محلي في فنجاء" },
      { en: "Small-group trip in a comfortable bus", ar: "رحلة بمجموعة صغيرة في حافلة مريحة" },
    ],
    itinerary: [
      { time: "05:30", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "Early departure so we reach the market as the auction begins.", ar: "انطلاق مبكر لنصل إلى السوق مع بداية المزاد." } },
      { time: "07:30", title: { en: "Friday market & souq", ar: "سوق الجمعة والسوق" }, body: { en: "About two hours among the livestock ring and the souq stalls.", ar: "نحو ساعتين بين حلقة الماشية وأكشاك السوق." } },
      { time: "09:45", title: { en: "Nizwa Fort", ar: "قلعة نزوى" }, body: { en: "Guided visit, then a coffee break in the fort's shadow.", ar: "زيارة بإرشاد ثم استراحة قهوة في ظل القلعة." } },
      { time: "11:15", title: { en: "Birkat Al Mouz", ar: "بركة الموز" }, body: { en: "Falaj Al Khatmeen and the old mud village.", ar: "فلج الخطمين والقرية الطينية القديمة." } },
      { time: "12:30", title: { en: "Lunch in Fanja", ar: "الغداء في فنجاء" }, body: { en: "Local restaurant, then return to Muscat by about 14:30.", ar: "مطعم محلي ثم العودة إلى مسقط نحو 14:30." } },
    ],
    inclusions: [
      { en: "Transportation in a comfortable bus (small group)", ar: "النقل في حافلة مريحة (مجموعة صغيرة)" },
      { en: "Omani guide", ar: "مرشد عُماني" },
      { en: "Nizwa Fort entrance", ar: "رسوم دخول قلعة نزوى" },
      { en: "Lunch at a local restaurant and bottled water", ar: "غداء في مطعم محلي ومياه معبأة" },
      { en: "Hotel pickup and drop-off in Muscat", ar: "الاستلام والتوصيل من وإلى الفندق في مسقط" },
    ],
    exclusions: commonExclusions,
    faqs: dayFaqs({
      question: { en: "Does this tour run every day?", ar: "هل تُنفَّذ هذه الجولة كل يوم؟" },
      answer: { en: "The livestock market takes place on Fridays only, so please book a Friday date. On other days we recommend our private Nizwa & Jebel Akhdar tour.", ar: "يُقام سوق الماشية يوم الجمعة فقط، لذا يرجى اختيار تاريخ يوافق يوم جمعة. في الأيام الأخرى ننصح بجولتنا الخاصة إلى نزوى والجبل الأخضر." },
    }),
    category: "cultural",
    secondaryCategories: ["day_trips"],
    destinations: ["nizwa"],
    durationLabel: { en: "9 hours", ar: "9 ساعات" },
    durationMinutes: 540,
    durationDays: 1,
    startTimes: ["05:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 12,
    capacityPerSlot: 12,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 50,
    priceChildOmr: 25,
    childAgeMax: 11,
    usdReference: 130,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "nizwa",
    isFeatured: false,
    tags: ["market", "culture", "friday", "small-group"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-015",
    viatorCode: "425555P39",
    kind: "tour",
    title: {
      en: "Muscat Heritage & Sunset Dhow Cruise – Private Afternoon Tour",
      ar: "تراث مسقط ورحلة الغروب بالسفينة التقليدية: جولة مسائية خاصة",
    },
    slug: { en: "muscat-heritage-sunset-dhow-cruise", ar: "تراث-مسقط-ورحلة-الغروب" },
    summary: {
      en: "Al Alam Palace, the Jalali and Mirani forts, Bait Al Zubair and Mutrah Souq, crowned by a two-hour sunset cruise on a traditional Omani dhow.",
      ar: "قصر العلم وقلعتا الجلالي والميراني وبيت الزبير وسوق مطرح، ويتوّجها إبحار لساعتين عند الغروب على سفينة عُمانية تقليدية.",
    },
    description: {
      en: "Muscat is at its most beautiful in the late afternoon light. With an experienced Omani guide you explore Old Muscat, the Al Alam Palace and the twin Portuguese forts of Jalali and Mirani, then step into Bait Al Zubair Museum for the story of Omani dress, weapons and daily life. The highlight follows: a relaxing two-hour cruise from Marina Bandar Al Rowdha aboard a traditional wooden dhow, gliding past the cliffs and coves of the capital as the sun sets over the Sea of Oman, with Omani coffee and dates on deck. We end in Mutrah Souq as it lights up for the evening, with an optional dinner at Bait Al Luban to taste authentic shuwa.",
      ar: "تكون مسقط في أبهى صورها مع ضوء ما بعد الظهيرة. مع مرشد عُماني متمرّس تستكشف مسقط القديمة وقصر العلم وقلعتَي الجلالي والميراني البرتغاليتين، ثم تدخل متحف بيت الزبير لتتعرّف على قصة الزيّ والأسلحة والحياة اليومية في عُمان. ثم يأتي الجزء الأبرز: إبحار هادئ لساعتين من مرسى بندر الروضة على متن سفينة خشبية تقليدية، تمرّ بجروف العاصمة وخلجانها بينما تغرب الشمس فوق بحر عُمان، مع القهوة والتمر على السطح. ونختتم في سوق مطرح مع إضاءته المسائية، مع عشاء اختياري في بيت اللبان لتذوّق الشواء الأصيل.",
    },
    highlights: [
      { en: "Al Alam Palace and the Jalali & Mirani forts", ar: "قصر العلم وقلعتا الجلالي والميراني" },
      { en: "Bait Al Zubair Museum (entrance included)", ar: "متحف بيت الزبير (رسوم الدخول مشمولة)" },
      { en: "Two-hour sunset cruise on a traditional dhow", ar: "إبحار لساعتين عند الغروب على سفينة تقليدية" },
      { en: "Mutrah Souq by evening light", ar: "سوق مطرح في ضوء المساء" },
      { en: "Optional Omani dinner at Bait Al Luban", ar: "عشاء عُماني اختياري في بيت اللبان" },
    ],
    itinerary: [
      { time: "13:30", title: { en: "Pickup from Muscat", ar: "الاستلام من مسقط" }, body: { en: "Air-conditioned vehicle with your Omani guide.", ar: "سيارة مكيّفة مع مرشدك العُماني." } },
      { time: "14:00", title: { en: "Old Muscat", ar: "مسقط القديمة" }, body: { en: "Al Alam Palace, Jalali and Mirani forts (photo stops).", ar: "قصر العلم وقلعتا الجلالي والميراني (توقفات للتصوير)." } },
      { time: "14:45", title: { en: "Bait Al Zubair", ar: "بيت الزبير" }, body: { en: "One hour in the museum of Omani heritage.", ar: "ساعة في متحف التراث العُماني." } },
      { time: "16:15", title: { en: "Sunset dhow cruise", ar: "رحلة الغروب بالسفينة" }, body: { en: "Two hours from Marina Bandar Al Rowdha with coffee and dates on board.", ar: "ساعتان من مرسى بندر الروضة مع القهوة والتمر على المتن." } },
      { time: "18:30", title: { en: "Mutrah Souq & optional dinner", ar: "سوق مطرح وعشاء اختياري" }, body: { en: "Evening stroll in the souq; optional dinner at Bait Al Luban, then hotel drop-off.", ar: "جولة مسائية في السوق؛ عشاء اختياري في بيت اللبان ثم التوصيل إلى الفندق." } },
    ],
    inclusions: [
      { en: "Private air-conditioned vehicle", ar: "سيارة خاصة مكيّفة" },
      { en: "English-speaking Omani guide", ar: "مرشد عُماني يتحدث الإنجليزية" },
      { en: "Bait Al Zubair Museum entrance", ar: "رسوم دخول متحف بيت الزبير" },
      { en: "Two-hour dhow cruise with coffee and dates", ar: "رحلة سفينة لساعتين مع القهوة والتمر" },
      { en: "Hotel pickup and drop-off in Muscat", ar: "الاستلام والتوصيل من وإلى الفندق في مسقط" },
    ],
    exclusions: [{ en: "Dinner at Bait Al Luban (optional)", ar: "العشاء في بيت اللبان (اختياري)" }, ...commonExclusions],
    faqs: dayFaqs({
      question: { en: "Is the cruise suitable for children and seniors?", ar: "هل الرحلة البحرية مناسبة للأطفال وكبار السن؟" },
      answer: { en: "Yes. The dhow sails in sheltered water close to the coast, has shaded seating and life jackets for everyone, and the vehicle is wheelchair-friendly.", ar: "نعم. تبحر السفينة في مياه محمية قرب الساحل، وفيها مقاعد مظلّلة وسترات نجاة للجميع، والسيارة مناسبة للكراسي المتحركة." },
    }),
    category: "city_tours",
    secondaryCategories: ["boat", "cultural"],
    destinations: ["muscat"],
    durationLabel: { en: "6 hours", ar: "6 ساعات" },
    durationMinutes: 360,
    durationDays: 1,
    startTimes: ["13:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 1,
    maxGroup: 6,
    capacityPerSlot: 6,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 52,
    priceChildOmr: 26,
    childAgeMax: 11,
    usdReference: 135,
    depositPercent: 35,
    freeCancellationHours: 72,
    allowReserveNowPayLater: true,
    holdHours: 24,
    ratingAverage: 5,
    image: "muscat",
    isFeatured: false,
    tags: ["sunset", "dhow", "heritage", "evening", "private"],
    meetingPoint: hotelMuscat,
  },
];
