import { DAY, airportMuscat, commonExclusions, hotelMuscat, multiDayFaqs, type TourSeed } from "./tourSeedTypes";

/** Two- and three-day private journeys from Muscat (Viator catalogue, September 2026). */
export const shortJourneys: TourSeed[] = [
  {
    code: "OCT-007",
    viatorCode: "425555P24",
    kind: "tour",
    title: { en: "2-Day Jabal Akhdar Mountain Overnight – Private with Omani Guide", ar: "يومان في الجبل الأخضر مع مبيت: رحلة خاصة مع مرشد عُماني" },
    slug: { en: "jabal-akhdar-2-day-overnight", ar: "الجبل-الأخضر-يومان" },
    summary: {
      en: "Birkat Al Mouz, the villages and rose terraces of Jabal Akhdar, a mountain sunset and a 4-star hotel night, then Nizwa's souq, fort and the Oman Across Ages Museum.",
      ar: "بركة الموز وقرى الجبل الأخضر ومدرجات الورد وغروب جبلي وليلة في فندق أربع نجوم، ثم سوق نزوى وقلعتها ومتحف عُمان عبر الزمان.",
    },
    description: {
      en: "Give the Green Mountain the time it deserves. On day one we leave Muscat, pause at the old village and falaj of Birkat Al Mouz and climb by 4WD to the Saiq Plateau at about 2,300 m. Your guide leads you through Wadi Bani Habib, Al Ain and the historic village of Al Nakhar, into a traditional house where rosewater is distilled, and to a local shop selling mountain honey, walnuts and pomegranates. After lunch there is time to rest at your four-star hotel before a sunset over the terraces and dinner. Day two descends to Nizwa: the souq famous for some of the finest dates in the country, the round-towered fort, and finally the Oman Across Ages Museum for a deeper look at the nation's story before we return to Muscat.",
      ar: "امنح الجبل الأخضر الوقت الذي يستحقه. في اليوم الأول نغادر مسقط ونتوقف عند قرية بركة الموز القديمة وفلجها، ثم نصعد بالدفع الرباعي إلى هضبة سيق على ارتفاع نحو 2300 متر. يقودك مرشدك عبر وادي بني حبيب والعين وقرية النخر التاريخية، إلى بيت تقليدي يُقطَّر فيه ماء الورد، وإلى متجر محلي يبيع عسل الجبل والجوز والرمان. بعد الغداء متسع للراحة في فندقك ذي الأربع نجوم قبل غروب فوق المدرجات ثم العشاء. وفي اليوم الثاني ننزل إلى نزوى: السوق الشهير بأجود التمور في البلاد، والقلعة ذات البرج الدائري، وأخيرًا متحف عُمان عبر الزمان لنظرة أعمق على قصة الوطن قبل العودة إلى مسقط.",
    },
    highlights: [
      { en: "Birkat Al Mouz village and falaj", ar: "قرية بركة الموز وفلجها" },
      { en: "Wadi Bani Habib, Al Ain and Al Nakhar villages at 2,300 m", ar: "قرى وادي بني حبيب والعين والنخر على ارتفاع 2300 م" },
      { en: "Rosewater house and mountain-produce shop", ar: "بيت تقطير ماء الورد ومتجر منتجات الجبل" },
      { en: "Sunset and a night at a 4-star mountain hotel", ar: "غروب وليلة في فندق جبلي أربع نجوم" },
      { en: "Nizwa Souq, Nizwa Fort and the Oman Across Ages Museum", ar: "سوق نزوى وقلعة نزوى ومتحف عُمان عبر الزمان" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Muscat → Birkat Al Mouz → Jabal Akhdar", ar: "مسقط ← بركة الموز ← الجبل الأخضر" }, body: { en: "Pickup 08:30. Birkat Al Mouz (45 min), 4WD ascent, villages and rosewater house (3 h), lunch, hotel check-in, sunset viewpoint, dinner.", ar: "الاستلام 08:30. بركة الموز (45 دقيقة)، الصعود بالدفع الرباعي، القرى وبيت ماء الورد (3 ساعات)، الغداء، تسجيل الوصول، إطلالة الغروب، العشاء." } },
      { time: "Day 2", title: { en: "Nizwa → Muscat", ar: "نزوى ← مسقط" }, body: { en: "Breakfast, Nizwa Souq (1 h), Nizwa Fort (1 h, entrance included), Oman Across Ages Museum (2 h), return to Muscat by about 17:00.", ar: "الإفطار، سوق نزوى (ساعة)، قلعة نزوى (ساعة، الدخول مشمول)، متحف عُمان عبر الزمان (ساعتان)، العودة إلى مسقط نحو 17:00." } },
    ],
    inclusions: [
      { en: "Private 4WD with a licensed Omani guide for both days", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني مرخّص لليومين" },
      { en: "One night at a 4-star hotel on Jabal Akhdar (double room)", ar: "ليلة في فندق أربع نجوم في الجبل الأخضر (غرفة مزدوجة)" },
      { en: "Lunch, dinner and breakfast on day 1, lunch on day 2", ar: "غداء وعشاء وإفطار اليوم الأول، وغداء اليوم الثاني" },
      { en: "Nizwa Fort entrance and bottled water", ar: "رسوم دخول قلعة نزوى ومياه معبأة" },
      { en: "Pickup from any address in Muscat, including the airport", ar: "الاستلام من أي عنوان في مسقط بما في ذلك المطار" },
    ],
    exclusions: [{ en: "Oman Across Ages Museum entrance (about OMR 5)", ar: "رسوم دخول متحف عُمان عبر الزمان (نحو 5 ر.ع.)" }, ...commonExclusions],
    faqs: multiDayFaqs({
      question: { en: "Can we upgrade the hotel?", ar: "هل يمكننا ترقية الفندق؟" },
      answer: { en: "Yes. The price is based on a 4-star hotel such as Sahab Resort or dusitD2 Naseem; Anantara Al Jabal Al Akhdar and Alila Jabal Akhdar (5-star) are available for a supplement that we confirm before payment.", ar: "نعم. السعر على أساس فندق أربع نجوم مثل منتجع سحاب أو دوسيت دي2 نسيم؛ ويتوفر أنانتارا الجبل الأخضر وأليلا الجبل الأخضر (خمس نجوم) مقابل فرق نؤكده قبل الدفع." },
    }),
    category: "multi_day",
    secondaryCategories: ["mountain_wadi", "cultural"],
    destinations: ["nizwa", "jebel_akhdar"],
    durationLabel: { en: "2 days / 1 night", ar: "يومان / ليلة واحدة" },
    durationMinutes: 2 * DAY,
    durationDays: 2,
    startTimes: ["08:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 269,
    priceChildOmr: 190,
    childAgeMax: 11,
    usdReference: 1400,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    externalReviewCount: 8,
    image: "jebel-akhdar",
    isFeatured: true,
    featuredOrder: 7,
    tags: ["overnight", "mountains", "hotel", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-016",
    viatorCode: "425555P9",
    kind: "tour",
    title: { en: "2-Day Jabal Shams Grand Canyon Overnight – Nizwa, Misfat & Al Hoota Cave", ar: "يومان في أخدود جبل شمس مع مبيت: نزوى ومسفاة وكهف الهوتة" },
    slug: { en: "jabal-shams-2-day-overnight", ar: "جبل-شمس-يومان" },
    summary: {
      en: "Nizwa's souq and fort, the terraces of Misfat Al Abriyeen and a night on the rim of the Grand Canyon of Arabia, then off-road Wadi Ghul, Al Hoota Cave and Birkat Al Mouz.",
      ar: "سوق نزوى وقلعتها ومدرجات مسفاة العبريين وليلة على حافة أخدود الجزيرة العربية الكبير، ثم وادي غول الوعر وكهف الهوتة وبركة الموز.",
    },
    description: {
      en: "A private two-day journey to the roof of Oman with a skilled local guide. Day one explores old Nizwa, its souq of dates and silver and the fort that guarded the interior, then Misfat Al Abriyeen, where stone houses stand over terraces watered by an ancient falaj. Late afternoon we drive off-road up Jabal Shams to a viewpoint on the edge of Wadi Ghul, Oman's Grand Canyon, and check in to a mountain camp or resort for dinner under a sky full of stars. Day two follows the canyon rim into Wadi Ghul, descends to Al Hoota Cave in Al Hamra with its underground lake, and ends at Birkat Al Mouz beside a 2,000-year-old water channel still in use, with a coffee break in the ruins before the return to Muscat. Breakfast, lunch and dinner are included.",
      ar: "رحلة خاصة ليومين إلى سقف عُمان مع مرشد محلي متمرّس. يستكشف اليوم الأول نزوى القديمة وسوقها للتمور والفضة وقلعتها التي حرست الداخل، ثم مسفاة العبريين حيث تقف البيوت الحجرية فوق مدرجات يرويها فلج عريق. وفي وقت متأخر من العصر نقود على الطرق الوعرة صعودًا إلى جبل شمس حتى نقطة مشاهدة على حافة وادي غول، أخدود عُمان الكبير، ونسجّل الوصول في مخيم أو منتجع جبلي لعشاء تحت سماء مليئة بالنجوم. يتبع اليوم الثاني حافة الأخدود إلى وادي غول، ثم ينزل إلى كهف الهوتة في الحمراء ببحيرته الجوفية، وينتهي في بركة الموز بجوار قناة مياه عمرها ألفا عام ما زالت تعمل، مع استراحة قهوة بين الأطلال قبل العودة إلى مسقط. الإفطار والغداء والعشاء مشمولة.",
    },
    highlights: [
      { en: "Nizwa Souq and Nizwa Fort (entrance included)", ar: "سوق نزوى وقلعة نزوى (الدخول مشمول)" },
      { en: "Misfat Al Abriyeen terraces", ar: "مدرجات مسفاة العبريين" },
      { en: "Sunset and overnight on the rim of Wadi Ghul", ar: "غروب ومبيت على حافة وادي غول" },
      { en: "Al Hoota Cave (entrance included)", ar: "كهف الهوتة (الدخول مشمول)" },
      { en: "Birkat Al Mouz and its 2,000-year-old falaj", ar: "بركة الموز وفلجها العريق" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Nizwa, Misfat Al Abriyeen and Jabal Shams", ar: "نزوى ومسفاة العبريين وجبل شمس" }, body: { en: "Pickup 08:30. Nizwa Souq (1 h), Nizwa Fort (45 min), lunch, Misfat Al Abriyeen (1 h), off-road ascent to the canyon viewpoint, dinner and overnight at a classic mountain camp or resort.", ar: "الاستلام 08:30. سوق نزوى (ساعة)، قلعة نزوى (45 دقيقة)، الغداء، مسفاة العبريين (ساعة)، الصعود الوعر إلى إطلالة الأخدود، العشاء والمبيت في مخيم أو منتجع جبلي كلاسيكي." } },
      { time: "Day 2", title: { en: "Wadi Ghul, Al Hoota Cave and Birkat Al Mouz", ar: "وادي غول وكهف الهوتة وبركة الموز" }, body: { en: "Breakfast, canyon-rim drive into Wadi Ghul (1 h), Al Hoota Cave (1 h), Birkat Al Mouz ruins and coffee break, lunch, return to Muscat by about 17:00.", ar: "الإفطار، قيادة على حافة الأخدود إلى وادي غول (ساعة)، كهف الهوتة (ساعة)، أطلال بركة الموز واستراحة قهوة، الغداء، العودة إلى مسقط نحو 17:00." } },
    ],
    inclusions: [
      { en: "Private 4WD with an Omani guide for both days", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني لليومين" },
      { en: "One night at a classic or mid-range camp/resort on Jabal Shams (double room)", ar: "ليلة في مخيم أو منتجع كلاسيكي أو متوسط في جبل شمس (غرفة مزدوجة)" },
      { en: "Breakfast, lunch and dinner", ar: "الإفطار والغداء والعشاء" },
      { en: "Entrance to Nizwa Fort and Al Hoota Cave", ar: "رسوم دخول قلعة نزوى وكهف الهوتة" },
      { en: "Bottled water and hotel/airport pickup in Muscat", ar: "مياه معبأة والاستلام من الفندق أو المطار في مسقط" },
    ],
    exclusions: commonExclusions,
    faqs: multiDayFaqs(),
    category: "multi_day",
    secondaryCategories: ["mountain_wadi", "cultural"],
    destinations: ["nizwa", "jabal_shams"],
    durationLabel: { en: "2 days / 1 night", ar: "يومان / ليلة واحدة" },
    durationMinutes: 2 * DAY,
    durationDays: 2,
    startTimes: ["08:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 298,
    priceChildOmr: 210,
    childAgeMax: 11,
    usdReference: 1550,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    image: "jebel-akhdar",
    isFeatured: false,
    tags: ["overnight", "canyon", "cave", "4x4", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-017",
    viatorCode: "425555P10",
    kind: "tour",
    title: { en: "2-Day Wahiba Desert Camp Overnight – Wadi Bani Khalid & Nizwa", ar: "يومان في مخيم صحراء وهيبة مع مبيت: وادي بني خالد ونزوى" },
    slug: { en: "wahiba-desert-camp-2-day", ar: "مخيم-رمال-وهيبة-يومان" },
    summary: {
      en: "Swim in Wadi Bani Khalid, watch the sunset from the dunes and sleep at a desert camp with dinner and live entertainment, then explore Nizwa's souq and fort on the way home.",
      ar: "سباحة في وادي بني خالد، غروب من فوق الكثبان ومبيت في مخيم صحراوي مع عشاء وفعاليات، ثم سوق نزوى وقلعتها في طريق العودة.",
    },
    description: {
      en: "The desert deserves a night. We leave Muscat with an experienced Omani guide and reach the crystal-clear pools of Wadi Bani Khalid before the crowds, with time to swim and picnic in the shade. In the afternoon the 4WD rolls into the Wahiba Sands for a dune drive and a golden sunset from the top of the dunes. Your camp welcomes you with Arabian hospitality, a traditional dinner and live cultural entertainment under a sky crowded with stars; camel rides and quad biking can be added. After breakfast we cross to the historic city of Nizwa for its souq of dates, halwa and silver, its fort and the mud-brick villages and aflaj irrigation channels that UNESCO recognises as a masterpiece of engineering, before returning to Muscat.",
      ar: "تستحق الصحراء ليلة. نغادر مسقط مع مرشد عُماني متمرّس ونصل إلى برك وادي بني خالد الصافية قبل الزحام، مع وقت للسباحة ووجبة خفيفة في الظل. وبعد الظهر تدخل سيارة الدفع الرباعي رمال وهيبة لقيادة على الكثبان وغروب ذهبي من أعلاها. يستقبلك مخيمك بضيافة عربية وعشاء تقليدي وفعاليات ثقافية حية تحت سماء مكتظّة بالنجوم؛ ويمكن إضافة ركوب الإبل والدراجات الرباعية. وبعد الإفطار نعبر إلى مدينة نزوى التاريخية لسوقها بالتمور والحلوى والفضة، وقلعتها، وقرى الطوب الطيني وقنوات الأفلاج التي تعترف بها اليونسكو تحفةً هندسية، قبل العودة إلى مسقط.",
    },
    highlights: [
      { en: "Swim in the pools of Wadi Bani Khalid", ar: "سباحة في برك وادي بني خالد" },
      { en: "Dune drive and sunset in the Wahiba Sands", ar: "قيادة على الكثبان وغروب في رمال وهيبة" },
      { en: "Night at a desert camp with dinner and entertainment", ar: "ليلة في مخيم صحراوي مع عشاء وفعاليات" },
      { en: "Optional camel ride and quad biking", ar: "ركوب إبل ودراجات رباعية اختياريان" },
      { en: "Nizwa Souq, fort and UNESCO aflaj", ar: "سوق نزوى والقلعة وأفلاج اليونسكو" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Wadi Bani Khalid and the Wahiba Sands", ar: "وادي بني خالد ورمال وهيبة" }, body: { en: "Pickup 08:30. Wadi Bani Khalid (2 h), lunch, Wahiba Sands dune drive and sunset (2 h), check-in at a classic desert camp near Al Wasil, dinner and entertainment.", ar: "الاستلام 08:30. وادي بني خالد (ساعتان)، الغداء، قيادة على كثبان وهيبة وغروب (ساعتان)، تسجيل الوصول في مخيم صحراوي كلاسيكي قرب الواصل، العشاء والفعاليات." } },
      { time: "Day 2", title: { en: "Culture and traditions in Nizwa", ar: "الثقافة والتقاليد في نزوى" }, body: { en: "Sunrise over the dunes, breakfast, drive via Bidiyah to Nizwa Souq (45 min) and Nizwa Fort (45 min, entrance included), return to Muscat by about 16:00.", ar: "شروق فوق الكثبان، الإفطار، الطريق عبر بدية إلى سوق نزوى (45 دقيقة) وقلعة نزوى (45 دقيقة، الدخول مشمول)، العودة إلى مسقط نحو 16:00." } },
    ],
    inclusions: [
      { en: "Private 4WD with an Omani guide for both days", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني لليومين" },
      { en: "One night at a classic or mid-range desert camp (double room)", ar: "ليلة في مخيم صحراوي كلاسيكي أو متوسط (غرفة مزدوجة)" },
      { en: "Dinner and breakfast at the camp", ar: "العشاء والإفطار في المخيم" },
      { en: "Nizwa Fort entrance and bottled water", ar: "رسوم دخول قلعة نزوى ومياه معبأة" },
      { en: "Pickup from your hotel or the airport in Muscat", ar: "الاستلام من الفندق أو المطار في مسقط" },
    ],
    exclusions: [{ en: "Lunches, camel ride and quad biking (payable at the camp)", ar: "وجبات الغداء وركوب الإبل والدراجات الرباعية (تُدفع في المخيم)" }, ...commonExclusions],
    faqs: multiDayFaqs(),
    category: "multi_day",
    secondaryCategories: ["desert_4x4", "cultural"],
    destinations: ["wahiba", "nizwa"],
    durationLabel: { en: "2 days / 1 night", ar: "يومان / ليلة واحدة" },
    durationMinutes: 2 * DAY,
    durationDays: 2,
    startTimes: ["08:30"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "easy",
    pricingModel: "per_person",
    priceAdultOmr: 298,
    priceChildOmr: 210,
    childAgeMax: 11,
    usdReference: 1550,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    externalReviewCount: 4,
    image: "wahiba",
    isFeatured: false,
    tags: ["overnight", "desert", "camp", "4x4", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-018",
    viatorCode: "425555P13",
    kind: "tour",
    title: { en: "2-Day Beach Camping: Wadi Mibam, BBQ at Fins & Wadi Shab", ar: "يومان تخييم على الشاطئ: وادي مبام وشواء في فنس ووادي شاب" },
    slug: { en: "beach-camping-wadi-mibam-wadi-shab-2-day", ar: "تخييم-الشاطئ-وادي-مبام-ووادي-شاب" },
    summary: {
      en: "An afternoon in the pools of Wadi Mibam, a night in a tent on Fins beach with a barbecue under the stars, then Wadi Shab's waterfall cave and the Bimmah Sinkhole.",
      ar: "عصرٌ في برك وادي مبام، ليلة في خيمة على شاطئ فنس مع شواء تحت النجوم، ثم كهف شلال وادي شاب وحفرة بمة.",
    },
    description: {
      en: "Our favourite short escape for couples and friends who like to sleep close to nature. We leave Muscat after lunch and head to Wadi Mibam, a quiet wadi of palm gardens and natural pools where you swim and wander for three hours. As the light softens we set up camp on the white sand of Fins beach; your guide lights the barbecue and dinner is served under the stars, followed by a night in a tent for two beside the sea. After a sunrise breakfast we walk into Wadi Shab, cross by boat, hike past plantations and swim to the hidden waterfall cave, then lunch on fresh fish at a local restaurant in Tiwi and finish with a dip in the Bimmah Sinkhole on the way home.",
      ar: "هروبنا القصير المفضّل للأزواج والأصدقاء الذين يحبون النوم قريبًا من الطبيعة. نغادر مسقط بعد الغداء ونتوجّه إلى وادي مبام، وادٍ هادئ من بساتين النخيل والبرك الطبيعية تسبح فيه وتتجوّل ثلاث ساعات. ومع نعومة الضوء ننصب المخيم على رمال شاطئ فنس البيضاء؛ يشعل مرشدك الشواء ويُقدَّم العشاء تحت النجوم، ثم ليلة في خيمة لشخصين بجوار البحر. بعد إفطار الشروق نمشي إلى وادي شاب، ونعبر بالقارب، ونمرّ بالمزارع ونسبح إلى كهف الشلال المخفي، ثم نتغدّى سمكًا طازجًا في مطعم محلي في طيوي ونختتم بسباحة في حفرة بمة في طريق العودة.",
    },
    highlights: [
      { en: "Three hours of swimming in Wadi Mibam", ar: "ثلاث ساعات سباحة في وادي مبام" },
      { en: "Barbecue dinner and tent night on Fins beach", ar: "عشاء شواء وليلة في خيمة على شاطئ فنس" },
      { en: "Wadi Shab hike and waterfall cave swim", ar: "مسار وادي شاب وسباحة إلى كهف الشلال" },
      { en: "Fresh fish lunch in Tiwi", ar: "غداء سمك طازج في طيوي" },
      { en: "Bimmah Sinkhole swim", ar: "سباحة في حفرة بمة" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Wadi Mibam and camping at Fins", ar: "وادي مبام والتخييم في فنس" }, body: { en: "Pickup 13:00. Wadi Mibam swim and walk (3 h), camp set-up on Fins beach, barbecue dinner and a night by the sea.", ar: "الاستلام 13:00. سباحة وتمشٍّ في وادي مبام (3 ساعات)، نصب المخيم على شاطئ فنس، عشاء شواء وليلة بجوار البحر." } },
      { time: "Day 2", title: { en: "Wadi Shab and the Bimmah Sinkhole", ar: "وادي شاب وحفرة بمة" }, body: { en: "Sunrise breakfast, Wadi Shab (3 h, boat crossing included), lunch in Tiwi, Bimmah Sinkhole (1 h), back in Muscat by about 17:00.", ar: "إفطار الشروق، وادي شاب (3 ساعات، عبور القارب مشمول)، الغداء في طيوي، حفرة بمة (ساعة)، العودة إلى مسقط نحو 17:00." } },
    ],
    inclusions: [
      { en: "Private 4WD with a professional Omani guide", ar: "سيارة دفع رباعي خاصة مع مرشد عُماني محترف" },
      { en: "Tent, mattresses and camping gear for two on Fins beach", ar: "خيمة وفرشات ومعدات تخييم لشخصين على شاطئ فنس" },
      { en: "Barbecue dinner and breakfast", ar: "عشاء شواء وإفطار" },
      { en: "Wadi Shab boat crossing and bottled water", ar: "عبور القارب في وادي شاب ومياه معبأة" },
      { en: "Pickup from Muscat city hotels", ar: "الاستلام من فنادق مدينة مسقط" },
    ],
    exclusions: [{ en: "Lunch on day 2 (about OMR 3–5 per person)", ar: "غداء اليوم الثاني (نحو 3–5 ر.ع. للشخص)" }, ...commonExclusions],
    faqs: multiDayFaqs({
      question: { en: "What should we bring for the camping night?", ar: "ماذا نحضر لليلة التخييم؟" },
      answer: { en: "Swimwear, a towel, water shoes, a light jacket for the evening breeze, a torch and personal toiletries; everything else, including the tent and bedding, is provided.", ar: "ملابس سباحة ومنشفة وحذاءً مائيًا وسترة خفيفة لنسيم المساء ومصباحًا وأدوات النظافة الشخصية؛ وكل ما عدا ذلك، بما في ذلك الخيمة والفراش، متوفر." },
    }),
    category: "multi_day",
    secondaryCategories: ["hiking_camping", "mountain_wadi"],
    destinations: ["wadi_shab", "sur"],
    durationLabel: { en: "2 days / 1 night", ar: "يومان / ليلة واحدة" },
    durationMinutes: 2 * DAY,
    durationDays: 2,
    startTimes: ["13:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 144,
    priceChildOmr: 100,
    childAgeMax: 11,
    usdReference: 750,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    image: "wadi-shab",
    isFeatured: false,
    tags: ["camping", "beach", "swimming", "couples", "private"],
    meetingPoint: hotelMuscat,
  },
  {
    code: "OCT-008",
    viatorCode: "425555P20",
    kind: "tour",
    title: { en: "3-Day Oman Nature & Culture with an Omani Guide – 4WD", ar: "3 أيام في طبيعة عُمان وثقافتها مع مرشد عُماني بالدفع الرباعي" },
    slug: { en: "oman-nature-culture-3-day", ar: "عمان-3-أيام-طبيعة-وثقافة" },
    summary: {
      en: "Wadi Shab's waterfall cave, turtles nesting at Ras Al Jinz, the Wahiba dunes and a desert camp, then Nizwa and Jabal Akhdar — three days, two camps, one private 4WD.",
      ar: "كهف شلال وادي شاب، تعشيش السلاحف في رأس الجنز، كثبان وهيبة ومخيم صحراوي، ثم نزوى والجبل الأخضر؛ ثلاثة أيام ومخيمان وسيارة دفع رباعي خاصة.",
    },
    description: {
      en: "The best of eastern Oman in a compact circuit. Day one takes the coast road to the Bimmah Sinkhole and Wadi Shab, where you hike and swim to the waterfall cave, and ends at Ras Al Jinz, where after dark a ranger leads you to the beach to watch green turtles lay their eggs. Day two visits the dhow yard in Sur, swims in the pools of Wadi Bani Khalid and drives into the Wahiba Sands for sunset and a night at a desert camp beneath the stars. Day three crosses to Nizwa for the souq and fort, climbs Jabal Akhdar for terraced villages and mountain views, and returns you to Muscat. Two nights at carefully selected camps or resorts, an official Omani guide and a Mitsubishi Pajero 4WD are included.",
      ar: "أفضل ما في شرق عُمان في مسار مركّز. يسلك اليوم الأول الطريق الساحلي إلى حفرة بمة ووادي شاب حيث تمشي وتسبح إلى كهف الشلال، وينتهي في رأس الجنز حيث يقودك حارس المحمية بعد الغروب إلى الشاطئ لمشاهدة السلاحف الخضراء تضع بيضها. يزور اليوم الثاني ورشة السفن في صور، ويسبح في برك وادي بني خالد، ويدخل رمال وهيبة للغروب وليلة في مخيم صحراوي تحت النجوم. ويعبر اليوم الثالث إلى نزوى للسوق والقلعة، ويصعد الجبل الأخضر للقرى المدرّجة والإطلالات الجبلية، ثم يعيدك إلى مسقط. يشمل السعر ليلتين في مخيمات أو منتجعات مختارة بعناية ومرشدًا عُمانيًا رسميًا وسيارة ميتسوبيشي باجيرو.",
    },
    highlights: [
      { en: "Wadi Shab hike and waterfall cave, Bimmah Sinkhole", ar: "مسار وادي شاب وكهف الشلال وحفرة بمة" },
      { en: "Green turtles nesting at Ras Al Jinz", ar: "تعشيش السلاحف الخضراء في رأس الجنز" },
      { en: "Sur dhow yard and Wadi Bani Khalid", ar: "ورشة سفن صور ووادي بني خالد" },
      { en: "Sunset and desert camp in the Wahiba Sands", ar: "غروب ومخيم صحراوي في رمال وهيبة" },
      { en: "Nizwa Souq, fort and Jabal Akhdar", ar: "سوق نزوى والقلعة والجبل الأخضر" },
    ],
    itinerary: [
      { time: "Day 1", title: { en: "Wadi Shab, Bimmah Sinkhole and Ras Al Jinz", ar: "وادي شاب وحفرة بمة ورأس الجنز" }, body: { en: "Pickup from your hotel or the airport. Bimmah Sinkhole (30 min), Wadi Shab (3 h, entrance included), evening turtle-watching at Ras Al Jinz reserve (1 h). Overnight at a camp or resort in Ras Al Jinz / Ras Al Hadd; dinner.", ar: "الاستلام من الفندق أو المطار. حفرة بمة (30 دقيقة)، وادي شاب (3 ساعات، الدخول مشمول)، مشاهدة السلاحف مساءً في محمية رأس الجنز (ساعة). المبيت في مخيم أو منتجع في رأس الجنز / رأس الحد؛ العشاء." } },
      { time: "Day 2", title: { en: "Sur, Wadi Bani Khalid and the Wahiba Sands", ar: "صور ووادي بني خالد ورمال وهيبة" }, body: { en: "Breakfast, Sur dhow yard (45 min), Wadi Bani Khalid swim (2 h), dune drive and sunset in the Wahiba Sands. Overnight at a desert camp; dinner.", ar: "الإفطار، ورشة سفن صور (45 دقيقة)، سباحة في وادي بني خالد (ساعتان)، قيادة على الكثبان وغروب في رمال وهيبة. المبيت في مخيم صحراوي؛ العشاء." } },
      { time: "Day 3", title: { en: "Nizwa, Jabal Akhdar and return to Muscat", ar: "نزوى والجبل الأخضر والعودة إلى مسقط" }, body: { en: "Breakfast, Nizwa Souq (45 min), Nizwa Fort (45 min, entrance included), Jabal Akhdar viewpoints and villages (1 h), back in Muscat by about 18:00.", ar: "الإفطار، سوق نزوى (45 دقيقة)، قلعة نزوى (45 دقيقة، الدخول مشمول)، إطلالات وقرى الجبل الأخضر (ساعة)، العودة إلى مسقط نحو 18:00." } },
    ],
    inclusions: [
      { en: "Official English-speaking Omani guide", ar: "مرشد عُماني رسمي يتحدث الإنجليزية" },
      { en: "Mitsubishi Pajero 4WD (or similar) with fuel", ar: "سيارة ميتسوبيشي باجيرو (أو مماثلة) مع الوقود" },
      { en: "Two nights at selected camps/resorts (twin or double room)", ar: "ليلتان في مخيمات/منتجعات مختارة (غرفة مزدوجة)" },
      { en: "Two breakfasts and two dinners", ar: "إفطاران وعشاءان" },
      { en: "Entrance to Wadi Shab, Ras Al Jinz turtle reserve and Nizwa Fort", ar: "رسوم دخول وادي شاب ومحمية سلاحف رأس الجنز وقلعة نزوى" },
      { en: "Airport or hotel pickup and bottled water", ar: "الاستلام من المطار أو الفندق ومياه معبأة" },
    ],
    exclusions: [{ en: "Lunches (about OMR 3–6 per person at local restaurants)", ar: "وجبات الغداء (نحو 3–6 ر.ع. للشخص في مطاعم محلية)" }, ...commonExclusions],
    faqs: multiDayFaqs({
      question: { en: "When can we see the turtles?", ar: "متى يمكننا مشاهدة السلاحف؟" },
      answer: { en: "Green turtles nest at Ras Al Jinz all year, with the busiest months from June to September. The reserve visit is after dark and led by a ranger; photography without flash only.", ar: "تعشّش السلاحف الخضراء في رأس الجنز طوال العام، وتبلغ الذروة من يونيو إلى سبتمبر. تكون زيارة المحمية بعد الغروب بقيادة حارس؛ والتصوير بدون فلاش فقط." },
    }),
    category: "multi_day",
    secondaryCategories: ["desert_4x4", "mountain_wadi"],
    destinations: ["wadi_shab", "sur", "wahiba", "nizwa", "jebel_akhdar"],
    durationLabel: { en: "3 days / 2 nights", ar: "3 أيام / ليلتان" },
    durationMinutes: 3 * DAY,
    durationDays: 3,
    startTimes: ["09:00"],
    pickupIncluded: true,
    guideLanguages: ["en", "ar"],
    minGroup: 2,
    maxGroup: 4,
    capacityPerSlot: 4,
    difficulty: "moderate",
    pricingModel: "per_person",
    priceAdultOmr: 519,
    priceChildOmr: 360,
    childAgeMax: 11,
    usdReference: 2700,
    depositPercent: 35,
    freeCancellationHours: 720,
    allowReserveNowPayLater: true,
    holdHours: 48,
    ratingAverage: 5,
    externalReviewCount: 4,
    image: "wadi-shab",
    isFeatured: false,
    tags: ["multi-day", "turtles", "desert", "4x4", "private"],
    meetingPoint: airportMuscat,
  },
];
